### ISSUE TITLE
Feedback from the namespace propagation exercise

### ISSUE THREAD

**Issue by mikkokallioibm** [openshift-labs/learn-katacoda#1000]
Hello, 

One learner shared the following comment:

"This is such a great resource - thank you. I couldn't load kubedef. During namespace propagation exercise it returned this error: *Enabling namespaces is required so the KubeFed controller will propagate namespaces across the federated clusters. - Error: Error listing api resources: unable to retrieve the complete list of server APIs: servicecatalog.k8s.io/v1beta1: the server is currently unable to handle the request"

Thanks for looking into this.

**Comment by ryanj** [comment]
Thanks for reporting.

Given issue #1060, I've removed our KubeFed scenario from the index here: https://learn.openshift.com/introduction/ 

If I can find someone to fix the content, I'll add it back in
