### ISSUE TITLE
Lab environment is never available

### ISSUE THREAD

**Issue by mohdmujtabaa** [openshift-labs/learn-katacoda#1001]
https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-1

It just says the below and never come up.

Hang tight! We’re preparing the environment for you.

**Comment by JulianJason** [comment]
Ditto, I have been trying on 3 separate days.

**Comment by djberg96** [comment]
Seeing lots of "We are currently at capacity with no additional nodes available. Please check back in 10 minutes." for several days now.

**Comment by tmorik** [comment]
Same here. I'm trying to run **openup  GitOps Introduction with OpenShift** demo but never be available.

**Comment by ryanj** [comment]
Thank you for alerting.  Capacity issues should be resolved now.  

Feel free to reopen if you notice additional capacity issues!
