### ISSUE TITLE
oc new-app openshiftkatacoda/blog-django-py --name blog

### ISSUE THREAD

**Issue by jkachuck** [openshift-labs/learn-katacoda#1003]
Hello, 
I am sure others have commented:
#############
$ oc new-app openshiftkatacoda/blog-django-py --name blog
W0129 19:47:23.695224    1574 dockerimagelookup.go:236] container image registry lookup failed: docker.io/openshiftkatacoda/blog-django-py:latest: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
error:  local file access failed with: stat openshiftkatacoda/blog-django-py: no such file or directory
error: unable to locate any images in image streams, templates loaded in accessible projects, template files, local docker images with name "openshiftkatacoda/blog-django-py"

Argument 'openshiftkatacoda/blog-django-py' was classified as an image, image~source, or loaded template reference.

The 'oc new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet.

See 'oc new-app -h' for examples.
############

**Comment by cedricclyburn** [comment]
Hello! We've merged #1169 to address some problems with this lab, and you shouldn't expect to see the docker limit anymore. Feel free to try the lab again!
