### ISSUE TITLE
Using OpenShift - Lab 7: Introduction to Federated Cluster with KubeFed - joining clusters fails

### ISSUE THREAD

**Issue by aws-mike-ubeda** [openshift-labs/learn-katacoda#1005]
Upon running the "Introduction to Federated Cluster with KubeFed" in the Interactive Portal under the "Using Openshift" course an error occurs upon joining clusters.

Below is the executed command that causes the error:
`kubefedctl join cluster1 --host-cluster-context cluster1 --v=2 --kubefed-namespace=test-namespace`

Error:
`F0203 03:48:23.623377   32188 join.go:126] Error: Error retrieving KubeFedConfig "test-namespace/kubefed": no matches for kind "KubeFedConfig" in version "core.kubefed.k8s.io/v1beta1"`

Seems to be related to Issue #928

**Comment by ryanj** [comment]
Thanks for reporting.

Given issue #1060, I've removed it from the index here: https://learn.openshift.com/introduction/ 

If I can find someone to fix the content, I'll add it back in
