### ISSUE TITLE
Issues with Getting Started With Kubefed tutorial

### ISSUE THREAD

**Issue by donovat** [openshift-labs/learn-katacoda#1008]
When you get to **Step 3 - Registering Clusters** part of the course that defines the clusters; 
i.e. 
 _oc --context=cluster1 get kubefedclusters -n test-namespace_

you get the following error;
**error: the server doesn't have a resource type "kubefedclusters"**

After that nothing then works.

**Comment by ryanj** [comment]
Thanks for reporting.

Given issue #1060, I've removed it from the index: https://learn.openshift.com/introduction/ 

If I can find someone to fix the content, I'll add it back in
