### ISSUE TITLE
Lack of resources in all labs

### ISSUE THREAD

**Issue by alexxspb** [openshift-labs/learn-katacoda#1019]
Hello!
Last 4 days I'm having problems with all labs on the interactive learning portal https://learn.openshift.com/.
Sometimes I have to wait too long to get fully functional cluster for the lab, sometimes I have got an warning about high load and one advise about trying again  after 10 minutes later.

![image](https://user-images.githubusercontent.com/50702135/107914283-248bdc80-6f73-11eb-93a0-d1589990637e.png)

**Comment by ryanj** [comment]
Sorry about that!  Thanks for reporting

We should be back in operation.  Feel free to open a new ticket if you spot another capacity issue
