### ISSUE TITLE
Minor typos in container orchestration module

### ISSUE THREAD

**Issue by robertsawko** [openshift-labs/learn-katacoda#1024]
Hello,

Just going through the fundamental course. In the fifth lab [here](https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-5)

#### Step 2

```
you created a multi-teir web application
                    ----
```

and later:
```
so it's useful poke -> so it's useful to poke
```

#### Step 3
```
how your current Apache installation perform -> how your current Apache installation performs > 
```
and later:
```
Take not of the following sections in the output: -> Take note ...
```
and two typos later:
```
The reuqests are bing sent -> The requests are being sent
```

#### Step 5

```
You can execute commands in a sinlge pod -> You can execute commands in a single pod
```

**Comment by robertsawko** [comment]
I just created a [pull request](https://github.com/openshift-labs/learn-katacoda/pull/1026). I run the markdown files through a spellcheck and found a few more.

**Comment by cedricclyburn** [comment]
Thank you @robertsawko for reporting and the fixes!
