### ISSUE TITLE
Trying to pull registry.access.redhat.com/fedora: Repo not found

### ISSUE THREAD

**Issue by alexxspb** [openshift-labs/learn-katacoda#1025]
![image](https://user-images.githubusercontent.com/50702135/108229356-c9afdc00-7150-11eb-894e-1956d4811e9f.png)
https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-1

**Comment by ryanj** [comment]
Content updated. Thanks for reporting
https://github.com/openshift-labs/learn-katacoda/commit/518faacd022cac0eb0a3c857d55e0746ee27fbe1
