### ISSUE TITLE
Unable to access Getting Started with OpenShift for Developers

### ISSUE THREAD

**Issue by arunkargutkar** [openshift-labs/learn-katacoda#1034]
Hi Team,
               Demo courses on https://learn.openshift.com/introduction/getting-started/ not working since it encountered with error 

Your Interactive Learning Environment Bash Terminal

Oops! Sorry, we had a problem. Please refresh and try again. We are sorry but we encountered a problem with the connection.
Please refresh and try again. Mon Feb 22 2021 16:54:04 GMT+0530 (India Standard Time)
io server disconnect

**Comment by ryanj** [comment]
Thanks for reporting - Should be fixed
