### ISSUE TITLE
operator-sdk create api --helm-chart=cockroachdb --helm-chart-repo=https://kubernetes-charts.storage.googleapis.com --helm-chart-version=3.0.7 failed

### ISSUE THREAD

**Issue by kvv67** [openshift-labs/learn-katacoda#1037]
$ operator-sdk create api --helm-chart=cockroachdb --helm-chart-repo=https://kubernetes-charts.storage.googleapis.com --helm-chart-version=3.0.7
Error: failed to create API with version "3-alpha": failed to fetch chart: looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
Usage:
  operator-sdk create api [flags]

Examples:
  $ operator-sdk create api \
      --group=apps --version=v1alpha1 \
      --kind=AppService

  $ operator-sdk create api \
      --group=apps --version=v1alpha1 \
      --kind=AppService \
      --helm-chart=myrepo/app

  $ operator-sdk create api \
      --helm-chart=myrepo/app

  $ operator-sdk create api \
      --helm-chart=myrepo/app \
      --helm-chart-version=1.2.3

  $ operator-sdk create api \
      --helm-chart=app \
      --helm-chart-repo=https://charts.mycompany.com/

  $ operator-sdk create api \
      --helm-chart=app \
      --helm-chart-repo=https://charts.mycompany.com/ \
      --helm-chart-version=1.2.3

  $ operator-sdk create api \
      --helm-chart=/path/to/local/chart-directories/app/

  $ operator-sdk create api \
      --helm-chart=/path/to/local/chart-archives/app-1.2.3.tgz

Flags:
      --group string                resource group
      --version string              resource version
      --kind string                 resource kind
      --helm-chart string           helm chart
      --helm-chart-repo string      helm chart repository
      --helm-chart-version string   helm chart version (default: latest)
      --crd-version string          crd version to generate (default "v1")
  -h, --help                        help for api

Global Flags:
      --verbose   Enable verbose logging

FATA[0000] failed to create API with version "3-alpha": failed to fetch chart: looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden 
$

**Comment by sseitzfis** [comment]
Hi,
I had the exact same problem. Got around it by using:
_operator-sdk create api --helm-chart=cockroachdb --helm-chart-repo=https://charts.helm.sh/stable_

**Comment by madorn** [comment]
@sseitzfis @kvv67 fixed. Thanks.

**Comment by cedricclyburn** [comment]
Thanks for the fix @madorn! Updating the scenario to 4.7 currently and I'll close this one out :)
