### ISSUE TITLE
tkn pipeline start build-and-deploy failed

### ISSUE THREAD

**Issue by kvv67** [openshift-labs/learn-katacoda#1039]
$ tkn pipeline start build-and-deploy -w name=shared-workspace,claimName=source-pvc -p deployment-name=vote-api -p git-url=https://github.com/openshift-pipelines/vote-api.git -p IMAGE=image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/vote-api --showlog
PipelineRun started: build-and-deploy-run-pq927
Waiting for logs to be available...
[fetch-repository : clone] + CHECKOUT_DIR=/workspace/output/
[fetch-repository : clone] + [[ true == \t\r\u\e ]]
[fetch-repository : clone] + cleandir
[fetch-repository : clone] + [[ -d /workspace/output/ ]]
[fetch-repository : clone] + rm -rf '/workspace/output//*'
[fetch-repository : clone] + rm -rf '/workspace/output//.[!.]*'
[fetch-repository : clone] + rm -rf '/workspace/output//..?*'
[fetch-repository : clone] + test -z ''
[fetch-repository : clone] + test -z ''
[fetch-repository : clone] + test -z ''
[fetch-repository : clone] + /ko-app/git-init -url https://github.com/openshift-pipelines/vote-api.git -revision master -refspec '' -path /workspace/output/ -sslVerify=true -submodules=true -depth 1
[fetch-repository : clone] {"level":"info","ts":1614336994.3530445,"caller":"git/git.go:157","msg":"Successfully cloned https://github.com/openshift-pipelines/vote-api.git @ 6e8ec09aaf6ca6f1be0250a32f27a9d063720901 (grafted, HEAD, origin/master) in path /workspace/output/"}
[fetch-repository : clone] {"level":"info","ts":1614336994.515361,"caller":"git/git.go:198","msg":"Successfully initialized and updated submodules in path /workspace/output/"}
[fetch-repository : clone] + cd /workspace/output/
[fetch-repository : clone] ++ git rev-parse HEAD
[fetch-repository : clone] + RESULT_SHA=6e8ec09aaf6ca6f1be0250a32f27a9d063720901
[fetch-repository : clone] + EXIT_CODE=0
[fetch-repository : clone] + '[' 0 '!=' 0 ']'
[fetch-repository : clone] + echo -n 6e8ec09aaf6ca6f1be0250a32f27a9d063720901
[fetch-repository : clone] + echo -n https://github.com/openshift-pipelines/vote-api.git

[build-image : build] + buildah --storage-driver=overlay bud --format=oci --tls-verify=false --no-cache -f ./Dockerfile -t image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/vote-api .
[build-image : build] STEP 1: FROM image-registry.openshift-image-registry.svc:5000/openshift/golang:latest AS builder
[build-image : build] Getting image source signatures
[build-image : build] Copying blob sha256:1d72f48b3d14f64a70c8eb92dff736969b510ddcf2da89fac058c5c03ba41c58
[build-image : build] Copying blob sha256:506b188c0abe2ae3c1561bbff7ce50284de2a241eff5da6f528a3a024871c606
[build-image : build] Copying blob sha256:8a2b38c5dec5b8ce451a3f3a29f9b52803c756a49beb04e04244c66c399ef242
[build-image : build] Copying blob sha256:dcc691b92f82cdd39913b5e0015b5b648656608e0b9768aa4907a2420a0bcd03
[build-image : build] Copying blob sha256:a4d9907173f48ee257a0d6c451d530a2ec4088c38908b2ec48e3bc8dc66c6d21
[build-image : build] Copying config sha256:2b397b46f0d6f8c0703e32687427247b582896d56ec5130c4ddc64871e49e5ac
[build-image : build] Writing manifest to image destination
[build-image : build] Storing signatures
[build-image : build] STEP 2: WORKDIR /build
[build-image : build] STEP 3: ADD . /build/
[build-image : build] STEP 4: RUN export GARCH="$(uname -m)" && if [[ ${GARCH} == "x86_64" ]]; then export GARCH="amd64"; fi && GOOS=linux GOARCH=${GARCH} CGO_ENABLED=0 go build -mod=vendor -o api-server .
[build-image : build] /bin/sh: go: command not found
[build-image : build] subprocess exited with status 127
[build-image : build] subprocess exited with status 127
[build-image : build] error building at STEP "RUN export GARCH="$(uname -m)" && if [[ ${GARCH} == "x86_64" ]]; then export GARCH="amd64"; fi && GOOS=linux GOARCH=${GARCH} CGO_ENABLED=0 go build -mod=vendor -o api-server .": exit status 127

failed to get logs for task build-image : container step-build has failed  : [{"key":"StartedAt","value":"2021-02-26T10:56:58.568Z","resourceRef":{}}]
$

**Comment by ryanj** [comment]
Thanks for reporting - This should be fixed now!
