### ISSUE TITLE
Openshift Pipelines Tutorial Bug

### ISSUE THREAD

**Issue by lorsal** [openshift-labs/learn-katacoda#1041]
When doing the Openshift Pipelines tutorial, the build step of the backend pipeline fails with exit status 127.

/bin/sh: go: command not found
![OpenshiftPipelinesError](https://user-images.githubusercontent.com/79901914/109621575-70c24980-7b3b-11eb-9f0b-a922c115de6c.PNG)

**Comment by ryanj** [comment]
Thanks for reporting - This should be fixed now!
