### ISSUE TITLE
Command at https://learn.openshift.com/introduction/transferring-files/ do not work

### ISSUE THREAD

**Issue by catonice** [openshift-labs/learn-katacoda#1042]
Following the steps I get these errors at Step 2:

`$ oc rollout status dc/blog`
`Error from server (NotFound): deploymentconfigs.apps.openshift.io "blog" not found`
`$ oc get pods --selector deploymentconfig=blog`
`No resources found in myproject namespace.`

And then cannot complete the rest of the tutorial.

Some more context:

`$ oc get pods`
NAME                           READY   STATUS             RESTARTS   AGE
blog-5dc99d7545-jvffz          1/1     Running            0          17m
django-psql-example-1-4q972    1/1     Running            0          15m
django-psql-example-1-build    0/1     Completed          0          17m
django-psql-example-1-deploy   0/1     Completed          0          15m
hello-node-855447ffcc-tzwvx    0/1     ImagePullBackOff   0          17m
postgresql-1-deploy            0/1     Completed          0          17m
postgresql-1-rjrws             1/1     Running            0          17m

**Comment by Raaveni** [comment]
Still doesn't work. 

You can replace dc with deployment to get through this command, but it doesn't help later on.

**Comment by cedricclyburn** [comment]
Thanks @catonice and @Raaveni for the report and workaround! I've just merged a fix with #1169 which solves this issue, feel free to try the lab again!
