### ISSUE TITLE
Connection to cluster not working for lecture 1

### ISSUE THREAD

**Issue by pdemeulenaer** [openshift-labs/learn-katacoda#1045]
"Logging in to an OpenShift Cluster" lecture (https://learn.openshift.com/introduction/cluster-access/) not loading. Here is error message:

Oops! Sorry, we had a problem. Please refresh and try again.
We are sorry but we encountered a problem with the connection.
Please refresh and try again.
Tue Mar 09 2021 16:34:59 GMT+0200 (Eastern European Standard Time)
io server disconnect

**Comment by ryanj** [comment]
Thanks for the alert. It seems to be working again
