### ISSUE TITLE
https://learn.openshift.com/playgrounds

### ISSUE THREAD

**Issue by jameswsp** [openshift-labs/learn-katacoda#1048]
https://learn.openshift.com/playgrounds

The tutorial ends up  after 1 page (https://learn.openshift.com/playgrounds/openshift46/) show.

**Comment by ryanj** [comment]
Hello @jameswsp.  Thanks for reaching out.
Our "playground" learning scenarios are not really intended to provide any content.  The purpose for those scenarios is merely to provide a quick way to access an OpenShift cluster for one hour.

There is one page of example commands, to help users authenticate with the cluster - but I like to think of the playground scenarios as minimalistic "Choose your own Adventure" content. ;)
Any of the other section areas (outside of the playground) should include several pages of content per scenario.

Feel free to reopen this issue if you think we need to refresh the content to clarify these expectations for new users.
