### ISSUE TITLE
Error in Tutorial: Deploying Applications From Source

### ISSUE THREAD

**Issue by teddybeaker** [openshift-labs/learn-katacoda#1054]
Hi

I worked through the tutorial "Deploying Applications From Source". In step 6 (deploying from comand line), when I run the command
`oc new-app python:latest~https://github.com/openshift-katacoda/blog-django-py`, i get this error.

```
error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/app-root/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-djrh846u/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-djrh846u/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ra4lq_2o/install-record.txt --single-version-externally-managed --compile --install-headers /opt/app-root/include/site/python3.8/psycopg2 Check the logs for full command output.
WARNING: You are using pip version 19.3.1; however, version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
subprocess exited with status 1
subprocess exited with status 1
error: build error: error building at STEP "RUN /tmp/scripts/assemble": exit status 1
```

Since _latest_ is now 3.8 and the tutorial refers to latest as 3.6, I tried running `oc new-app python:3.6~https://github.com/openshift-katacoda/blog-django-py` instead. I get an error and a suggestion to add a --strategy (source or docker) but if I pick one of those I get a different error.

```
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/.local'
Check the permissions.

subprocess exited with status 1
subprocess exited with status 1
error: build error: error building at STEP "RUN /tmp/scripts/assemble": exit status 1
```

Since I am currently learning OpenShift I have no further approaches on how to resolve the issue and continue with the tutorial.

Kind regards,
Stefani

**Comment by based3** [comment]
from #1088
workaround:
git clone https://github.com/based3/blog-django-py

**Comment by cedricclyburn** [comment]
Hello @teddybeaker! Thanks for reporting this issue, we've gone ahead and merged a PR to fix the Django blog, feel free to try the scenario again now! Closing for now 👍
