### ISSUE TITLE
Pulling image error

### ISSUE THREAD

**Issue by kotlincook** [openshift-labs/learn-katacoda#1064]
[INFO] F8: pulling image error : open /etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt: no such file or directory
[INFO] F8: error: build error: unable to get registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.3
Trying internal type for name:Build
[ERROR] F8: Failed to execute the build [Unable to build the image using the OpenShift build service]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 39.560 s
[INFO] Finished at: 2021-03-21T21:42:44+00:00
[INFO] Final Memory: 51M/688M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.40:build (fmp) on project fruits: Failed to execute the build: Unable to build the image using the OpenShift build service: OpenShift Build fruits-s2i-1 error: Failed: PullBuilderImageFailed -> [Help 1]

**Comment by blues-man** [comment]
Hi @kotlincook, which Lab?

**Comment by jamesfalkner** [comment]
Fixed (by updating to jkube) with https://github.com/openshift-katacoda/rhoar-getting-started/commit/9f76a139d86d771380d00dace6154d6adce56f04#diff-02a4a41955a42b9a7528b145a8240fec3c59d217261c66397e738c9bcd8626fc
