### ISSUE TITLE
Debizium lab is not starting.

### ISSUE THREAD

**Issue by bobbyjohnstx** [openshift-labs/learn-katacoda#1069]
The Debizium labs is not starting.
![Screen Shot 2021-03-31 at 11 55 58 AM](https://user-images.githubusercontent.com/22921029/113182156-34f0d180-9218-11eb-84b5-f3e5d40749f4.png)

**Comment by ryanj** [comment]
Thanks for reporting the issue, @bobbyjohnstx

This one should be working: https://learn.openshift.com/middleware/courses/middleware-kafka/

Feel free to reopen if you find any issues there
