### ISSUE TITLE
Error from server (NotFound)

### ISSUE THREAD

**Issue by davebrownrational** [openshift-labs/learn-katacoda#1072]
I'm an IBMer in the Interactive Learning Portal.
Working on the 2nd scenario: Transferring Files in and out of Containers
Having a problem on step 2 (and step 4), with the command "oc rollout status dc/blog".  The response is "Error from server (NotFound): deploymentconfigs.apps.openshift.io "blog" not found".  Same thing is step 4.  Doesn't recognize dc/blog.
I can just go around this in step 2.  But in step 4 dc/blog is used to set an environment variable and restart the service.  Don't know how to work around that.

**Comment by davebrownrational** [comment]
And the following command "oc get pods --selector deploymentconfig=blog" results in "No resources found in myproject namespace."
This one was harder to work around, I had to go to the console and copy the pod name, and then use it in the later command that sets the $POD variable.

**Comment by davebrownrational** [comment]
This is the command in step 4 that fails "oc set env dc/blog MOD_WSGI_RELOAD_ON_CHANGES=1" with "Error from server (NotFound): deploymentconfigs.apps.openshift.io "blog" not found".
I can't figure out how to set this environment variable in the pod.

**Comment by davebrownrational** [comment]
Searching around quite a bit on the console, I found where I could set the environment variable.  This worked and got me through step 4.  But there is something wrong with the instructions the way they are.

**Comment by davebrownrational** [comment]
Having the same problem in step 5 with dc/dummy.  Command "oc set volume dc/dummy --add --name=tmp-mount --claim-name=data --type pvc --claim-size=1G --mount-path /mnt" results in "Error from server (NotFound): deploymentconfigs.apps.openshift.io "dummy" not found".
The following command - rollout status, also fails because it can't find dummy.
But amazingly, the next command "oc get pvc" results in:
NAME   STATUS   VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data   Bound    pv0013   100Gi      RWO,ROX,RWX                   2m48s
Since the name=data, this looks right, but the size is 100Gi, instead of 1G.
Looks like the mount didn't work, because the tar fails, can't create directories.

**Comment by cedricclyburn** [comment]
Hey @davebrownrational, closing this issue due to the #1169 merge! Again, thank you for bringing this to our attention :)
