### ISSUE TITLE
Issue with learn.openshift.com

### ISSUE THREAD

**Issue by mattganis** [openshift-labs/learn-katacoda#1078]
I think there's an issue with the site.   I'm using the course "Developing on OpenShift" and the scenario "Getting started with OpenShift for developers" - and when I do - I don't need to login (usually it's with developer/developer) - but I get placed into terminal mode immediately as root

Seems there is a little issue....

-Matt Ganis
ganis@us.ibm.com

**Comment by ryanj** [comment]
Thanks for reporting!  We had an outage on Monday, but the issue seems to be resolved now
