### ISSUE TITLE
error: no match for "jboss-eap72-openshift:1.0"

### ISSUE THREAD

**Issue by smarcioj** [openshift-labs/learn-katacoda#1079]
I got an error at https://learn.openshift.com/middleware/middleware-javaee8/ on creating a new-build:

oc new-build jboss-eap72-openshift:1.0 --binary=true --name=weather-app
error: Errors occurred while determining argument types:

jboss-eap72-openshift:1.0 as a Git repository URL:  ssh: Could not resolve hostname jboss-eap72-openshift: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

jboss-eap72-openshift:1.0 as a local directory pointing to a Git repository:  stat jboss-eap72-openshift:1.0: no such file or directory

Errors occurred during resource creation:
error: no match for "jboss-eap72-openshift:1.0"

**Comment by jamesfalkner** [comment]
Fixed with an update to latest EAP and OpenShift in https://github.com/openshift-labs/learn-katacoda/commit/c6bab3d14777c1f74750b013b2418131644e1e1c
