### ISSUE TITLE
Missing dc/dummy

### ISSUE THREAD

**Issue by twsc8004** [openshift-labs/learn-katacoda#1081]
In the following training: 
https://learn.openshift.com/introduction/transferring-files/
the deployment of a new pod does not seem to trigger the creation of a deployment config. 
All commands refering to dc/dummy are invalid.

**Comment by based3** [comment]
Same issue:
aftersuccessful:
Topic 5 - Copying Files to a Persistent Volume

oc run dummy --image centos/httpd-24-centos7

oc get all --selector run=dummy -o name
pod/dummy

i have an error with:
oc set volume dc/dummy --add --name=tmp-mount --claim-name=data --type pvc --claim-size=1G --mount-path /mnt

**Comment by davebrownrational** [comment]
I have the same problem with 
"
oc set volume dc/dummy --add --name=tmp-mount --claim-name=data --type pvc --claim-size=1G --mount-path /mnt

Error from server (NotFound): deploymentconfigs.apps.openshift.io "dummy" not found
"

Is there a known solution?

**Comment by davebrownrational** [comment]
@ryanj any help here would be appreciated.

**Comment by cedricclyburn** [comment]
Closing due to #1169 merge, thank you for the report!
