### ISSUE TITLE
"oc new-app" build failure on postgresql-client (psycopg2) - Deploying Applications From Source/Topic 6 - Deploying Using the Command Line

### ISSUE THREAD

**Issue by based3** [openshift-labs/learn-katacoda#1088]
https://github.com/openshift-katacoda/blog-django-py/issues/7

**Comment by based3** [comment]
workaround:
git clone https://github.com/based3/blog-django-py

**Comment by cedricclyburn** [comment]
Hello @based3! Thanks for bringing up the Django blog issue, we've gone ahead and merged a PR to fix this issue! Closing for now 👍
