### ISSUE TITLE
Missing `weather-app` in Getting Started with JBoss EAP on OpenShift

### ISSUE THREAD

**Issue by rakhmad** [openshift-labs/learn-katacoda#1089]
I am trying the **Getting Started with JBoss EAP on OpenShift**, but repository for `weather-app` is not available. I can't continue the module because no code to modify. 

![image](https://user-images.githubusercontent.com/195559/115424760-2f8c1300-a229-11eb-902e-8dcdc37ddf0b.png)

**Comment by jamesfalkner** [comment]
Fixed in https://github.com/openshift-labs/learn-katacoda/commit/c6bab3d14777c1f74750b013b2418131644e1e1c
