### ISSUE TITLE
oc rollout status dc/blog -> Error from server (NotFound): deploymentconfigs.apps.openshift.io "blog" not found

### ISSUE THREAD

**Issue by based3** [openshift-labs/learn-katacoda#1091]
**In what katacoda scenario did this bug occur?**
Red Hat OpenShift / Transferring Files in and out of Containers / Topic 2 - Downloading Files from a Container

**At what step of the scenario did this happen?**
If you can't remember the exact step, try to explain where in the scenario did the bug happen

**Describe the bug**
oc rollout status dc/blog 
-> Error from server (NotFound): deploymentconfigs.apps.openshift.io "blog" not found

**Logs or error messages**
Error from server (NotFound): deploymentconfigs.apps.openshift.io "blog" not found

**Screenshots**
N/A

**Additional context**
Workaround:
oc rollout status deployment/blog

**Comment by ryanj** [comment]
Thanks for reporting, and for including a workarond!

**Comment by cedricclyburn** [comment]
Hey @based3, thanks again for your fix! Closing now due to #1169 merge 👍
