### ISSUE TITLE
Build Fails: Deploying Applications From Source scenario

### ISSUE THREAD

**Issue by davebrownrational** [openshift-labs/learn-katacoda#1092]
I'm going through the Deploying Applications From Source scenario on the Interactive Learning Portal: https://learn.openshift.com/using-the-cluster/
Step 3 says to look at the log and see that the build completed successfully.
The log indicates that there was an error and the command exited with a status of 1

ERROR: Command errored out with exit status 1: /opt/app-root/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hsqopyr9/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hsqopyr9/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-64q5zloo/install-record.txt --single-version-externally-managed --compile --install-headers /opt/app-root/include/site/python3.8/psycopg2 Check the logs for full command output.
WARNING: You are using pip version 19.3.1; however, version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
subprocess exited with status 1
subprocess exited with status 1
error: build error: error building at STEP "RUN /tmp/scripts/assemble": exit status 1

Step 4 says to wait for the build to complete, and then use the url to visit the blog.  That fails because the image is not deployed.

In step 5, when you are deleting the app, I can see that there are hundreds of replicaset.apps "blog-django-py-xxxxxxxx

**Comment by based3** [comment]
you may check #1088

workaround:
git clone https://github.com/based3/blog-django-py

**Comment by davebrownrational** [comment]
This work around worked for me.
Will you be updating the scenario?

**Comment by cedricclyburn** [comment]
Hey @davebrownrational! Just doing some cleanup here, looks like a PR was merged to fix this issue and the lab runs as normal again! Thanks for bringing this up!

**Comment by davebrownrational** [comment]
Yep, I was able to complete this scenario after I saw your changes.
Still stuck on the "How to set up Prometheus and Grafana on OpenShift" scenario.  Please see https://github.com/openshift-labs/learn-katacoda/issues/1098.  Is that one on you priority list?

**Comment by cedricclyburn** [comment]
@davebrownrational Sweet! Yup, adding the Prometheus scenario to my list to work on next 👍
