### ISSUE TITLE
oc get pods --selector deploymentconfig=blog -> No resources found in myproject namespace.

### ISSUE THREAD

**Issue by based3** [openshift-labs/learn-katacoda#1093]
**In what katacoda scenario did this bug occur?**
Transferring Files in and out of Containers / Topic 2 - Downloading Files from a Container

**At what step of the scenario did this happen?**
If you can't remember the exact step, try to explain where in the scenario did the bug happen

**Describe the bug**
oc get pods --selector deploymentconfig=blog
>
No resources found in myproject namespace.

**Logs or error messages**
No resources found in myproject namespace.

**Screenshots**
N/A

**Additional context**
workaround
oc get pods -o 'name'
> pod/blog-5dc99d7545-q2tzk

POD=`oc get pods -o 'name'`; echo $POD

**Comment by cfergeau** [comment]
I also had this issue, I can't check know how I fixed it, but with `oc describe pod/blog-5dc99d7545-q2tzk` I found a different selector I could use (from memory, `deployment` rather than `deploymentconfig`).

**Comment by cedricclyburn** [comment]
Hello @based3 and @cfergeau! Thank you for the report and workaround, we've merged a fix through #1169, and now the scenario is functional again :)
