### ISSUE TITLE
Error retrieving KubeFedConfig

### ISSUE THREAD

**Issue by davebrownrational** [openshift-labs/learn-katacoda#1097]
**In what katacoda scenario did this bug occur?**
Introduction to Federated Clusters with Kubefed

**At what step of the scenario did this happen?**
Step 3 - Registering Clusters

**Describe the bug**
The commands to register the clusters generate errors, and later the command to verify the clusters have been registered, also produces an error, and does not show any registered clusters.

**Logs or error messages**
$ kubefedctl join cluster1 --host-cluster-context cluster1 --v=2 --kubefed-namespace=test-namespace
I0426 20:58:02.657120    9014 join.go:147] Defaulting cluster context to joining cluster name cluster1
I0426 20:58:02.657345    9014 join.go:159] Args and flags: name cluster1, host: cluster1, host-system-namespace: test-namespace, kubeconfig: , cluster-context: cluster1, secret-name: , dry-run: false
F0426 20:58:02.720304    9014 join.go:126] Error: Error retrieving KubeFedConfig "test-namespace/kubefed": no matches for kind "KubeFedConfig" in version "core.kubefed.k8s.io/v1beta1"

$ kubefedctl join cluster2 --host-cluster-context cluster1 --v=2 --kubefed-namespace=test-namespace
I0426 21:06:10.088554   21043 join.go:147] Defaulting cluster context to joining cluster name cluster2
I0426 21:06:10.088665   21043 join.go:159] Args and flags: name cluster2, host: cluster1, host-system-namespace: test-namespace, kubeconfig: , cluster-context: cluster2, secret-name: , dry-run: false
F0426 21:06:10.144409   21043 join.go:126] Error: Error retrieving KubeFedConfig "test-namespace/kubefed": no matches for kind "KubeFedConfig" in version "core.kubefed.k8s.io/v1beta1"

$ oc --context=cluster1 get kubefedclusters -n test-namespace
error: the server doesn't have a resource type "kubefedclusters"

**Screenshots**

**Additional context**

**Comment by davebrownrational** [comment]
@ryanj not seeing anything helpful at this label.  Is there any way to get some help?

**Comment by ryanj** [comment]
@davebrownrational Thanks for reporting

I added the label as a triage step, but we ended up removing the kubefed scenario because it didn't have a maintainer.  Sorry about that!

I hope that we will eventually be able to add new content to address this gap.  Closing for now
