### ISSUE TITLE
Various commands did not work in Transferring Files in and out of Containers...

### ISSUE THREAD

**Issue by richard-shannon** [openshift-labs/learn-katacoda#1100]
Here are 3 issues that I ran into using the Transferring Files in and out of Containers learning lab:
1. Commands that reference "dc" for deployment config did not work.  I had to change it to use the word "deployment".
2. Commands to get the pod name did not work.  I had to use `oc get pods` instead, and then use export POD= to set that variable.
3. In the last part, the command was to use `oc run`; however, I could not find the deployment config for that.  I changed to use `oc new-app` instead and then used what I learned from above.

I completed the labs after using these work arounds.

**Comment by cedricclyburn** [comment]
Hello @richard-shannon, just merged #1169 using your fixes, thank you for the heads up :)
