### ISSUE TITLE
oc login not working

### ISSUE THREAD

**Issue by DanRCoda** [openshift-labs/learn-katacoda#1114]
This may totally be user error, but when I perform the oc login command in the terminal I get the following: https://oauth-openshift-2886795280-443-hazel04.environments.katacoda.com/oauth/token/request

When I go to that url the error is this site can't be reached.

Thanks!

**Comment by DanRCoda** [comment]
I'm unable to reach the page to download the CLI tools as well

**Comment by alv1234** [comment]
I experience the same bug.

**Comment by azaceta** [comment]
same here

**Comment by azaceta** [comment]
I think it's the documentation that is wrong. If you just go with
```oc login```
it comes back asking for the token, while if you login using 
```oc login --username developer --password developer```
it just logs in!!

**Comment by ryanj** [comment]
You shouldn't need to log in or download any CLI tools in order to use katacoda (unless the content specifically calls for it)

**Comment by azaceta** [comment]
This is not downloading the CLI but using ```oc``` from the scenario/lab terminal window

**Comment by ryanj** [comment]
Thanks for the details on how to repro - This should be fixed now

Feel free to reopen if you hit the same issue
