### ISSUE TITLE
'host01' is inaccessible in the Ansible Review lab

### ISSUE THREAD

**Issue by jason-i-smith** [openshift-labs/learn-katacoda#1115]
The [Ansible Review lab](https://learn.openshift.com/ansibleop/ansible-refresher/) makes several references to a 'host01' server.  I cannot ping or ssh 'host01' within the KataKoda environment.

**Comment by dolph** [comment]
Duplicate with https://github.com/openshift-labs/learn-katacoda/issues/1120

**Comment by jdob** [comment]
Agreed, this is a duplicate, closing.
