### ISSUE TITLE
OpenShift Playground Issue

### ISSUE THREAD

**Issue by kumaranraj2895** [openshift-labs/learn-katacoda#1122]
Interactive Learning Environment is not working from few hours.
Error message: We are currently at capacity with no additional nodes available. Please check back in 10 minutes.
![Screenshot from 2021-05-26 11-37-23](https://user-images.githubusercontent.com/34240244/119610743-52f14180-be17-11eb-96ec-18fb47673ace.png)

**Comment by ryanj** [comment]
Looks like we're back.  Thanks for reporting!

**Comment by kumaranraj2895** [comment]
Its Working. Thank you so much
