### ISSUE TITLE
Wrong resource in "Step 2 -Downloading Files from a Container"

### ISSUE THREAD

**Issue by tdaleibm** [openshift-labs/learn-katacoda#1124]
In https://learn.openshift.com/introduction/transferring-files/ Step 2 , the command `oc rollout status dc/blog` is suggested however there is no deploymentconfig resource created. Instead I believe the command should be `oc rollout status deployment/blog` .
```

$ oc get dc
No resources found in myproject namespace.
$ oc rollout status dc/blog
Error from server (NotFound): deploymentconfigs.apps.openshift.io "blog" not found
$ oc get deployments
NAME   READY   UP-TO-DATE   AVAILABLE   AGE
blog   1/1     1            1           3m44s
$ oc rollout status deployment/blog
deployment "blog" successfully rolled out
```

Throughout the entire rest of the tutorial Step 2,3,4&5 pages there are multiple commands that use the "deploymentconfig" or "dc" object which should instead be "deployment" . Needed to change commands to successfully go through tutorial.

**Comment by cedricclyburn** [comment]
Hello @tdaleibm! Thank you for the report, we've merged a fix using `deployment` instead of `dc` in #1169, feel free to try the scenario again :)
