### ISSUE TITLE
Operator Workshop - June 4th, 9:00am to 6:00pm US Eastern

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#1126]
Operator Workshop - June 4th, 9:00am to 6:00pm US Eastern

20 attendees
Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

@gsoria
@jdob
@btannous
@BenHall
@ryanj

**Comment by gsoria** [comment]
Hi folks!, The workshop has been scheduled.

- Friday 04-06-2021 at 14:00 UTC until Friday 04-06-2021 at 22:00 UTC
- Number of expected attendees: 20
- Environment: openshift-4-5
- No password required.
- Attendees can access the course and the environments via https://learn.openshift.com/training/operator-framework-04
