### ISSUE TITLE
Operator Workshop - June 6th,  June 8th, June 10th, 9pm to 1am Eastern Time

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#1127]
Operator Workshop - June 6th, 8th, and 10th, 9pm to 1am Eastern Time

20 attendees
Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

@gsoria
@jdob
@btannous
@BenHall
@ryanj

**Comment by madorn** [comment]
Hi @gsoria @ryanj 

Checking on status of this request.  Thank you.

**Comment by ryanj** [comment]
Scheduled 20 for Wednesday 09-06-2021 at 01:00 UTC until Wednesday 09-06-2021 at 05:00 UTC

Number of expected attendees: 20

Environments: openshift-4-5, openshift-4-7

No password required.

Attendees can access the course and the environments via: https://learn.openshift.com/training/operator-framework-05

**Comment by ryanj** [comment]
Scheduled 20 for Friday 11-06-2021 at 01:00 UTC until Friday 11-06-2021 at 05:00 UTC

Number of expected attendees: 20

Environment: openshift-4-5, openshift-4-7

No password required.

Attendees can access the course and the environments via https://learn.openshift.com/training/operator-framework-06
