### ISSUE TITLE
Operator Workshop - June 14th to 16th 7:00am to  1:30pm US Eastern Time

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#1128]
Operator Workshop - June 14th to 16th 7:00am to  1:30pm US Eastern Time

70 attendees
Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

@gsoria
@jdob
@btannous
@BenHall
@ryanj

**Comment by mrhillsman** [comment]
@komish @rocrisp @acmenezes

**Comment by mrhillsman** [comment]
@komish
@acmenezes
@rocrisp

**Comment by ryanj** [comment]
Monday 14-06-2021 at 12:00 UTC until Monday 14-06-2021 at 18:30 UTC

Number of expected attendees: 70

Environment: openshift-4-5

Attendees can access the course and the environments via https://learn.openshift.com/training/operator-framework-07

**Comment by ryanj** [comment]
Tuesday 15-06-2021 at 12:00 UTC until Tuesday 15-06-2021 at 18:30 UTC

Number of expected attendees: 70

Environment: openshift-4-5

Attendees can access the course and the environments via https://learn.openshift.com/training/operator-framework-08
