### ISSUE TITLE
We are currently at capacity with no additional nodes available. Please check back in 10 minutes.

### ISSUE THREAD

**Issue by csasaki** [openshift-labs/learn-katacoda#1129]
I've retried the interactive page portal several times today, but every time it says that "We are currently at capacity with no additional nodes available. Please check back in 10 minutes."

**Comment by ryanj** [comment]
Thanks for reporting, @csasaki.  Which learning scenario was this?

**Comment by csasaki** [comment]
It was the Linux Container Internals 2.0 - Lab 1: Introduction to Containers scenario.  It looks like it's back working now though.
