### ISSUE TITLE
unable to use oc login in Getting Started with OpenShift for Developers

### ISSUE THREAD

**Issue by anupamshahi** [openshift-labs/learn-katacoda#1130]
unable to use oc login in Getting Started with OpenShift for Developers, when logging in through demo command oc login it is asking to obten a token

You must obtain an API token by visiting https://oauth-openshift-2886795274-443-kota01.environments.katacoda.com/oauth/token/request

and when i am trying to go to url https://oauth-openshift-2886795274-443-kota01.environments.katacoda.com/oauth/token/request this is giving error

**Comment by toshirov** [comment]
I have the same problem
