### ISSUE TITLE
Getting Started with OpenShift Pipelines faild deploying backend app due deployment name changed in git repo

### ISSUE THREAD

**Issue by neyder** [openshift-labs/learn-katacoda#1131]
This commit changed name of k8s objects.

https://github.com/openshift/pipelines-vote-api/commit/966a38560d56eca370d68de444cb2f02412b240d

now https://learn.openshift.com/middleware/pipelines/ fails in first deployment.

**Comment by ryanj** [comment]
Thanks for the alert!  I've deployed a potential fix via #1121

Feel free to reopen this issue if the patch isn't working as expected
