### ISSUE TITLE
unknown flag: --s2i

### ISSUE THREAD

**Issue by mtbroekman** [openshift-labs/learn-katacoda#1136]
Running the command `odo create java:openjdk-11-ubi8 backend --s2i --binary target/wildwest-1.0.jar --app=app` in the training material here --> https://learn.openshift.com/introduction/developing-with-odo/

And getting an error message of "unknown flag: --s2i" 
I cannot progress any further. Your help would be appreciated

**Comment by ryanj** [comment]
Thanks for reporting!
Looks like we're running on an outdated release of `odo`

This should be easy to resolve by installing a new release.  I'll double-check the build script and make sure we're staging up a newer release version.

**Comment by cedricclyburn** [comment]
+1 Thanks for reporting, just merged a PR to fix the issue.
