### ISSUE TITLE
Pipelines Operator not working on 4.7 image

### ISSUE THREAD

**Issue by blues-man** [openshift-labs/learn-katacoda#1154]
**In what katacoda scenario did this bug occur?**

1. Using OpenShift Pipelines
2. OpenShift 4.7 Playground

**At what step of the scenario did this happen?**
Operator installation

**Describe the bug**
The Pipeline Operator 1.4.1 from `stable` channel on CRC 4.7 fails to install all required pods in `openshift-pipelines` project.

**Logs or error messages**
```
MountVolume.SetUp failed for volume "config-trusted-cabundle-volume" : configmap references non-existent config key: ca-bundle.crt 
```
**Screenshots**
![image (3)](https://user-images.githubusercontent.com/1446126/121070070-8bf1c480-c7ce-11eb-8ac1-53a8db22f0c9.png)
![image (4)](https://user-images.githubusercontent.com/1446126/121070078-8eecb500-c7ce-11eb-8de6-1eb0c8c69c67.png)

**Additional context**
Channel `ocp-4.6` does not have this issue

**Comment by namloc2001** [comment]
I believe I have found a workaround, see #1164...
