### ISSUE TITLE
Issues with OpenShift Pipelines scenario - operator channel, deployment names

### ISSUE THREAD

**Issue by kwkoo** [openshift-labs/learn-katacoda#1156]
This issue relates to the [OpenShift Pipelines](https://learn.openshift.com/middleware/pipelines/) scenario.

1. The current stable version (early June 2021) of the pipelines operator does not work on learn.openshift.com - it would only work when I set the update channel to ocp-4.6.

2. In step 6, the instructions say to start the pipelines with `-p deployment-name=vote-api` and `-p deployment-name=vote-ui`. These should be updated to [`-p deployment-name=pipelines-vote-api`](https://github.com/openshift/pipelines-vote-api/blob/1f296ba6a03e9bcef6fbef131d50b8fbfc2f6173/k8s/deployment.yaml#L6) and [`-p deployment-name=pipelines-vote-ui`](https://github.com/openshift/pipelines-vote-ui/blob/50a81cebc618bbd3c5c0e9510a977464adcd18e8/k8s/deployment.yaml#L6) respectively.

**Comment by cedricclyburn** [comment]
Thanks for reporting this! We're working on it with #1166, should be merged soon!
