### ISSUE TITLE
Operator Workshop - July 12th to 14th 11:30am to 4:00pm US Eastern Time

### ISSUE THREAD

**Issue by mrhillsman** [openshift-labs/learn-katacoda#1157]
Operator Workshop - July 12th to 14th 11:30am to 4:00pm US Eastern Time

70 attendees
Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

@gsoria
@jdob
@btannous
@BenHall
@ryanj
@madorn

**Comment by jdob** [comment]
Can you scope this to smaller than a 2 day window? The cost is prohibitively expensive to schedule for that long.

**Comment by mrhillsman** [comment]
@jdob request is 11:30am to 4:00pm US Eastern each day 7/12, 7/13, and 7/14

**Comment by jdob** [comment]
These have been scheduled, please close this ticket when they are complete.
