### ISSUE TITLE
Operator Workshop - August 9th to 11th 6:00am to 10:30am US Eastern Time

### ISSUE THREAD

**Issue by mrhillsman** [openshift-labs/learn-katacoda#1159]
Operator Workshop - August 9th to 11th 6:00am to 10:30am US Eastern Time

80 attendees
Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

@gsoria
@jdob
@btannous
@BenHall
@ryanj
@madorn

**Comment by mrhillsman** [comment]
@jdob

**Comment by jdob** [comment]
These have been scheduled, please close this issue once the workshops are done.
