### ISSUE TITLE
Getting Started with OpenShift pipelines: Wrong deployment name in step 6 and 7

### ISSUE THREAD

**Issue by azaceta** [openshift-labs/learn-katacoda#1165]
Both pipeline runs fail, using the provided example, due to passing a wrong deployment-name parameter.
In both the API and the UI deployments, deployment name should be preceded by `pipelines-`, resulting in:
`deployment-name=pipelines-vote-api` for the API deployment and
`deployment-name=pipelines-vote-ui` for the UI deployment.

Full command lines would be, for the API:
`tkn pipeline start build-and-deploy -w name=shared-workspace,claimName=source-pvc -p deployment-name=pipelines-vote-api -p git-url=https://github.com/openshift/pipelines-vote-api.git -p IMAGE=image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/vote-api --showlog`
and for the UI:
`tkn pipeline start build-and-deploy -w name=shared-workspace,claimName=source-pvc -p deployment-name=pipelines-vote-ui -p git-url=https://github.com/openshift/pipelines-vote-ui.git -p IMAGE=image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/vote-ui --showlog`

This change makes the pipelines succeed.
`NAME                         STARTED          DURATION    STATUS
build-and-deploy-run-xh2jk   5 minutes ago    1 minute    Succeeded
build-and-deploy-run-h7bcq   7 minutes ago    1 minute    Succeeded`

**Comment by azaceta** [comment]
Step 7 also has a wrong name in the example
Where it says
`oc get route vote-ui --template='http://{{.spec.host}}'`
it should say
`oc get route pipelines-vote-ui --template='http://{{.spec.host}}'`

**Comment by blues-man** [comment]
Thanks for reporting it, working on a fix, this comes from this change: https://github.com/openshift/pipelines-vote-api/commit/966a38560d56eca370d68de444cb2f02412b240d
