### ISSUE TITLE
Capacity issue - container-internals-lab-2-0-part-1

### ISSUE THREAD

**Issue by nhatchman78** [openshift-labs/learn-katacoda#1176]
Tried couple times over past few days to start lab, but getting capacity limit error each time. Does the environment get re-started at certain times ?

**Comment by cedricclyburn** [comment]
Hello @nhatchman78! Thank you for the report, we're currently working on logging these issues to ensure greater availability of our labs. May I ask approximately what date/time you encountered the error?

**Comment by nhatchman78** [comment]
Hi Cedric. Was between 14.00-17.00 BST last Thur 10th and Friday 11th June. I had same error yesterday morning too.

________________________________

**Comment by ryanj** [comment]
Thanks for reporting - it seems like the subsystems and istio sections are experiencing an outage

**Comment by ryanj** [comment]
Should be fixed now. Feel free to reopen if you hit this issue again
