### ISSUE TITLE
Operator Workshop - June 21st to 23rd 10:00am to 5:00pm US Eastern Time

### ISSUE THREAD

**Issue by mrhillsman** [openshift-labs/learn-katacoda#1184]
Operator Workshop - June 21st to 23rd 10:00am to 5:00pm US Eastern Time

30 attendees
Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

@gsoria
@jdob
@btannous
@BenHall
@ryanj
@madorn 
@acmenezes

**Comment by mrhillsman** [comment]
@gsoria 
@btannous 
@jdob 
@ryanj 
@BenHall 

We have not got confirmation on this and class starts Monday so bumping.

**Comment by btannous** [comment]
Monday 21-06-2021 at 13:30 UTC until Monday 21-06-2021 at 21:30 UTC

Number of expected attendees: 30
Environment: openshift-4-5


Attendees can access the course and the environments via https://learn.openshift.com/training/operator-framework-a0

**Comment by btannous** [comment]
Tuesday 22-06-2021 at 13:30 UTC until Tuesday 22-06-2021 at 21:30 UTC

Number of expected attendees: 30
Environment: openshift-4-5

Attendees can access the course and the environments via https://learn.openshift.com/training/operator-framework-a1

**Comment by btannous** [comment]
Wednesday 23-06-2021 at 13:30 UTC until Wednesday 23-06-2021 at 21:30 UTC

Number of expected attendees: 30
Environment: openshift-4-5

Attendees can access the course and the environments via https://learn.openshift.com/training/operator-framework-a2

**Comment by btannous** [comment]
@mrhillsman should be good now.

**Comment by mrhillsman** [comment]
thx @btannous
