### ISSUE TITLE
Transferring Files in and out of Containers - blog deployment is wrong type

### ISSUE THREAD

**Issue by andy-fry** [openshift-labs/learn-katacoda#1196]
Trying to follow the steps in "Transferring Files in and out of Containers" and the commands fail.

The blog container is not a deploymentconfig it's a service

![image](https://user-images.githubusercontent.com/26530166/122497161-18508280-d02c-11eb-87a3-ce3211c26cf1.png)

**Comment by andy-fry** [comment]
duplicate of #1100

**Comment by cedricclyburn** [comment]
Hey @andy-fry! Just fixed this issue with the deployment config thru #1169, feel free to run through the scenario now :)
