### ISSUE TITLE
Reactive Streams with Quarkus and Kafka: no matches for kind "Kafka"

### ISSUE THREAD

**Issue by Gene-R-Pool** [openshift-labs/learn-katacoda#1197]
I am working through the openshift lab Reactive Streams with Quarkus and Kafka. When I get to page 6 the lab asks me to run the command: "oc apply -f src/main/kubernetes/kafka-names-cluster.yaml" to which I receive this error: "error: unable to recognize "src/main/kubernetes/kafka-names-cluster.yaml": no matches for kind "Kafka" in version "kafka.strimzi.io/v1beta1"". Relevant tweet: https://twitter.com/IanColdwater/status/1213607102595424258

**Comment by jamesfalkner** [comment]
Fixed in https://github.com/openshift-katacoda/rhoar-getting-started/commit/27cecc44da512f096ec2518947bd0ecec25aa94f
