### ISSUE TITLE
FIS2 Scenario - Hawtio Console not showing message count

### ISSUE THREAD

**Issue by LutzLange** [openshift-labs/learn-katacoda#120]
I did the FIS 2.0 Scenario today using F26 and Google Chrome 62.0.3202.94. 
See https://learn.openshift.com/middleware/fis-deploy-app/

I was unable to see any message counts in step 4. Switching to other tabs in the Java Console did not help.

The inflight tab did not show anything besides a rotating circle. Route Diagram did not show message counts at all.

**Comment by mhausenblas** [comment]
@BenHall any idea?

**Comment by jorgemoralespou** [comment]
Seems like websockets are not working for any reason in this console. The scenario works, you can see the table count updated only if you refresh the console, but not real-time.

If you clik on the "+" sign and select "View HTTP port on Server 1" it will open the dashboard in a new browser tab. And everything works fine here.

![image](https://user-images.githubusercontent.com/78350/35058555-9cb03544-fbb8-11e7-8364-b16f17113dd0.png)

**Comment by mhausenblas** [comment]
Seems stale, please re-open if it persists.
