### ISSUE TITLE
Transferring Files In and Out of Containers - Sample application still refers to Origin

### ISSUE THREAD

**Issue by jdob** [openshift-labs/learn-katacoda#1203]
**In what katacoda scenario did this bug occur?**
Transferring Files In and Out of Containers

**At what step of the scenario did this happen?**
Step 4

**Describe the bug**
The sample application has verbiage about Origin, which is no longer a product.

**Logs or error messages**
None

**Screenshots**
None

**Additional context**
None

**Comment by cedricclyburn** [comment]
Hello @jdob! I created a PR to change the verbiage here: https://github.com/openshift-katacoda/blog-django-py/pull/15, should be resolved soon. Thank you for the report :)

**Comment by cedricclyburn** [comment]
Thank you @jamesfalkner for merging https://github.com/openshift-katacoda/blog-django-py/pull/15, closing now due to external fix.
