### ISSUE TITLE
Developing APIs using Red Hat OpenShift and JBoss Fuse: build brocken

### ISSUE THREAD

**Issue by rbaumgar** [openshift-labs/learn-katacoda#122]
on page 2 of 5:
$ oc start-build mypeopleservice
The ImageStreamTag "fis-java-openshift:2.0" is invalid: from: Error resolving ImageStreamTag "fis-java-openshift:2.0" in namespace openshift: unable to find latest tagges image

**Comment by thesteve0** [comment]
FYI


---------- Forwarded message ----------

**Comment by mhausenblas** [comment]
Seems stale, please re-open if it persists.
