### ISSUE TITLE
Operator Workshop - July 4th, July 6th, July 8th 10:00pm to 12:00am US Eastern Time

### ISSUE THREAD

**Issue by mrhillsman** [openshift-labs/learn-katacoda#1223]
Operator Workshop - July 4th, July 6th, July 8th 10:00pm to 12:00am US Eastern Time

25 attendees
Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

@jdob
@btannous
@ryanj
@madorn

**Comment by jdob** [comment]
These have been scheduled. Please close this issue once the event is over.
