### ISSUE TITLE
Reactive Streams with Quarkus and Kafka: no matches for kind "Kafka"

### ISSUE THREAD

**Issue by cedricclyburn** [openshift-labs/learn-katacoda#1224]
**In what katacoda scenario did this bug occur?**
Reactive Streams with Quarkus and Kafka (Believe it's due to #1143 refresh)

**At what step of the scenario did this happen?**
Step 6: Deploying Kafka to OpenShift

**Describe the bug**
Not able to create a new Kafka object within the cluster

**Logs or error messages**
`error: unable to recognize "src/main/kubernetes/kafka-names-cluster.yaml": no matches for kind "Kafka" in version "kafka.strimzi.io/v1beta1"`

Screenshots
![image](https://user-images.githubusercontent.com/54345140/123866354-f3e18980-d8fa-11eb-854a-382a9df6e4cb.png)

**Comment by cedricclyburn** [comment]
It may be a super quick fix with syncing the strimzi and kafka versions up, will look into it later and provide update.

**Comment by jamesfalkner** [comment]
This was fixed with https://github.com/openshift-katacoda/rhoar-getting-started/commit/27cecc44da512f096ec2518947bd0ecec25aa94f
