### ISSUE TITLE
Quarkus for Spring Boot Developers: Missing Photo

### ISSUE THREAD

**Issue by cedricclyburn** [openshift-labs/learn-katacoda#1232]
**In which scenario did this bug occur?**

Quarkus for Spring Boot Developers

**At what step of the scenario did this happen?**

Step 6: Scale the app

**Describe the bug**

scaling_spring.png is scaling_spring_.png, thus not visible

**Logs or error messages**

N/A

**Screenshots**

![image](https://user-images.githubusercontent.com/54345140/124094226-921e3e00-da26-11eb-8f68-4e72583a53d7.png)

**Additional context**

N/A

**Comment by jamesfalkner** [comment]
Fixed in https://github.com/openshift-labs/learn-katacoda/commit/f5cb7eb88aad33f83a1b3d68205dc2f122a457b1
