### ISSUE TITLE
Multi-user Workspace Using JupyterHub

### ISSUE THREAD

**Issue by blues-man** [openshift-labs/learn-katacoda#1245]
Depends on https://github.com/openshift-labs/learn-katacoda/issues/1244

**Comment by jdob** [comment]
Can you put some detail in here on what the actual bug/issue is? It doesn't serve much use in tracking or reporting unless the issue describes what is going on.

**Comment by blues-man** [comment]
This was blocked by the change needed in #1244, now solved with the migration to  https://github.com/openshift-katacoda
