### ISSUE TITLE
Operator Workshop - July 28, 29, and 30th - 10:00AM UTC to 3:00PM UTC

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#1263]
Operator Workshop - July 26, 27, 28, 29, and 30th - 10:00AM UTC to 3:00PM UTC

50 attendees.

Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

@gsoria
@jdob
@btannous
@BenHall
@ryanj

**Comment by jdob** [comment]
These have been scheduled. Please close this ticket after the workshop.

**Comment by skattoju** [comment]
@jdob I didn't receive a link to the provisioned environments where can I find this information ?

**Comment by jdob** [comment]
Closing per Matt's comment.
