### ISSUE TITLE
authentication required

### ISSUE THREAD

**Issue by shancz** [openshift-labs/learn-katacoda#1275]
**In which scenario did this bug occur?**

Name the katacoda you were using

**At what step of the scenario did this happen?**

If you can't remember the exact step, try to explain where in the scenario did the bug happen

**Describe the bug**

A clear and concise description of what the bug is

**Logs or error messages**

Paste in any error message you got

**Screenshots**

If applicable, add screenshots to help explain your problem

**Additional context**

Add any other context about the problem

**Comment by shancz** [comment]
While doing the lab located here:

https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-5

The build is failing with the following error message:

  5m            4m              4       kubelet, 622f423b394d   spec.containers{mysql}  Normal          Pulling                 pulling image "openshift3/mysql-55-rhel7"
  5m            4m              4       kubelet, 622f423b394d   spec.containers{mysql}  Warning         Failed                  Failed to pull image "openshift3/mysql-55-rhel7": rpc error: code = 2 desc = unauthorized: authentication required

**Comment by madorn** [comment]
Fixed in #1290.

**Comment by jdob** [comment]
Closing per Matt's comment.
