### ISSUE TITLE
Operator Framework exercises using 4-5 image showing auth errors

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#1276]
The openshift-4-5 image has some misconfiguration that is causing authentication errors on any exercises requiring `exec` or `logs`:

i.e. https://learn.openshift.com/operatorframework/etcd-operator/, step 3.

`$ oc logs $ETCD_OPERATOR_POD -f`
`error: You must be logged in to the server (the server has asked for the client to provide credentials ( pods/log etcd-operator-84cf65cb74-n582j))`

`$ oc rsh etcd-operator-84cf65cb74-n582j`
`error: unable to upgrade connection: Unauthorized`

To resolve this issue, we should bump the remaining operator-framework exercises to 4-7. Will need to update exercises as well as 4-7 image ships with operator-sdk 1.8.0.

**Comment by madorn** [comment]
Fixed in #1290.

**Comment by jdob** [comment]
Closing per Matt's comment.
