### ISSUE TITLE
Unauthorized error during Kubernetes API Fundamentals scenario

### ISSUE THREAD

**Issue by mamurak** [openshift-labs/learn-katacoda#1277]
**In which scenario did this bug occur?**

Kubernetes API Fundamentals

**At what step of the scenario did this happen?**

Step 1: Kubernetes Manifests

**Describe the bug**

The scenario contains instructions to execute shell sessions within the created pod:

`oc exec -it my-two-container-pod -c server -- /bin/sh` and
`oc exec -it my-two-container-pod -c side-car -- /bin/sh`

However, these instructions fail with an Unauthorized error.

**Logs or error messages**

`error: unable to upgrade connection: Unauthorized`

**Comment by madorn** [comment]
Please see https://github.com/openshift-labs/learn-katacoda/issues/1276.

**Comment by madorn** [comment]
Fixed in #1290.

**Comment by jdob** [comment]
Closing per Matt's comment.
