### ISSUE TITLE
Etcd Operator: Can't open remote shell

### ISSUE THREAD

**Issue by mamurak** [openshift-labs/learn-katacoda#1279]
**In which scenario did this bug occur?**

Etcd Operator 

**At what step of the scenario did this happen?**

Step 5: Interacting with a Live Etcd Cluster

**Describe the bug**

The scenario instructs the user to execute a shell session within the created `etcdclient` pod:

`oc rsh etcdclient`

However, this instruction fail with an Unauthorized error.

**Logs or error messages**

`error: unable to upgrade connection: Unauthorized`

**Comment by madorn** [comment]
Please see https://github.com/openshift-labs/learn-katacoda/issues/1276

**Comment by madorn** [comment]
Fixed in #1289

**Comment by jdob** [comment]
Closing per Matt's comment.
