### ISSUE TITLE
Operator Lifecycle Manager: Error accessing logs

### ISSUE THREAD

**Issue by mamurak** [openshift-labs/learn-katacoda#1282]
**In which scenario did this bug occur?**

Operator Lifecycle Manager

**At what step of the scenario did this happen?**

Step 5: Reviewing the InstallPlan and Installing the Operator

**Describe the bug**

The user is instructed to display the logs of the newly created ArgoCD operator pod using
```
ARGOCD_OPERATOR=`oc get pods -o jsonpath={$.items[0].metadata.name}`
oc logs $ARGOCD_OPERATOR
```

However, this command fails due to missing credentials.

**Logs or error messages**

`error: You must be logged in to the server (the server has asked for the client to provide credentials ( pods/log argocd-operator-77b476dd6c-2rpc7))`

**Comment by madorn** [comment]
Please see https://github.com/openshift-labs/learn-katacoda/issues/1276

**Comment by jdob** [comment]
Closing per Matt's comment.
