### ISSUE TITLE
Operator SDK with Helm: Wrong CR file reference

### ISSUE THREAD

**Issue by mamurak** [openshift-labs/learn-katacoda#1285]
**In which scenario did this bug occur?**

Operator SDK with Helm

**At what step of the scenario did this happen?**

Step 4: Apply the CockroachDB Custom Resource

**Describe the bug**

The scenario instructs the user to update the CockroachDB CR at
`go/src/github.com/redhat/cockroachdb-operator/deploy/crds/charts.helm.k8s.io_v1alpha1_cockroachdb_cr.yaml`.

However, this location does not exist. Instead, the instruction should refer the user to
`config/samples/charts_v1alpha1_cockroachdb.yaml`.

**Comment by madorn** [comment]
Fixed in #1290.

**Comment by jdob** [comment]
Closing per Matt's comment.
