### ISSUE TITLE
operatorframework/k8s-api-fundamentals/ scenario1 is erroring out at a step

### ISSUE THREAD

**Issue by KR411-prog** [openshift-labs/learn-katacoda#1288]
**In which scenario did this bug occur?**

https://learn.openshift.com/operatorframework/k8s-api-fundamentals/

**At what step of the scenario did this happen?**

Scenario 1

**Describe the bug**

oc exec -it my-two-container-pod -c server -- /bin/sh
error: unable to upgrade connection: Unauthorized

**Logs or error messages**

error: unable to upgrade connection: Unauthorized

**Screenshots**

<img width="613" alt="image" src="https://user-images.githubusercontent.com/14121261/129489782-576d83c1-8180-43b1-b1ef-0fca3446da19.png">

**Comment by madorn** [comment]
Please see https://github.com/openshift-labs/learn-katacoda/issues/1276

**Comment by madorn** [comment]
Fixed in #1290.

**Comment by jdob** [comment]
Closing per Matt's comment.
