### ISSUE TITLE
Deploying a Jupyter Notebook Image - Not working

### ISSUE THREAD

**Issue by alanmarazzi** [openshift-labs/learn-katacoda#1325]
**In which scenario did this bug occur?**

https://learn.openshift.com/ai-machine-learning/jupyter-notebooks/

**At what step of the scenario did this happen?**

Step 1

**Describe the bug**

When trying to run the suggested commands the result is always: `error: the server doesn't have a resource type "imagestream"`

**Logs or error messages**

error: the server doesn't have a resource type "imagestream"

**Screenshots**

![shot](https://user-images.githubusercontent.com/14168642/139071989-c20962a1-c21a-4c27-9e32-f7fef88eb72c.png)

**Additional context**

...

**Comment by joshix** [comment]
This appears to be a transient error with the environment loading. I am not able to reproduce it (see attached screenshot). Please open a new session and try again
<img width="512" alt="Screen Shot 2021-10-30 at 15 10 04" src="https://user-images.githubusercontent.com/72905/139557306-9cee71e7-f6da-424e-9c8b-6018a882bdcb.png">
.
