### ISSUE TITLE
New build of the openshift-middleware image

### ISSUE THREAD

**Issue by tqvarnst** [openshift-labs/learn-katacoda#140]
Hi Ben,
Just merged a change to the openshift-middleware build scripts. Can you trigger a new build?

Best regards
Thomas

**Comment by mhausenblas** [comment]
Please complete or move to Trello.

**Comment by tqvarnst** [comment]
@mhausenblas Are you asking me or @BenHall?

**Comment by mhausenblas** [comment]
@tqvarnst I was asking @BenHall :)

Sorry if that wasn't clear from the context.

**Comment by DuncanDoyle** [comment]
Has this been done already? I need that image to speed up the startup time of my Decision Manager 7 scenario in this PR: https://github.com/openshift-labs/learn-katacoda/pull/143

**Comment by BenHall** [comment]
@DuncanDoyle It was just rolled out. We've also made improves that will speed up future builds.
