### ISSUE TITLE
typos and grammatical errors

### ISSUE THREAD

**Issue by perkinss** [openshift-labs/learn-katacoda#144]
What means this?

> One this that differs slightly is the pom.xml. Please open the and examen it a bit closer (but do not change anything at this time)

This is in the Spring boot demo

**Comment by mhausenblas** [comment]
Thanks, yeah bad grammar. Want to send in a PR?

**Comment by perkinss** [comment]
Sure! What’s that?

**Comment by mhausenblas** [comment]
Essentially, sending in a patch with a suggested update for that sentence. See [Pull Request](https://help.github.com/articles/creating-a-pull-request/) (PR for short) for further infos. Thank you!
