### ISSUE TITLE
Support asciidoc for content

### ISSUE THREAD

**Issue by thesteve0** [openshift-labs/learn-katacoda#15]

**Comment by lincolnthree** [comment]
Hey @thesteve0, did you ever figure out if this is possible? We're looking into this as well.

**Comment by thesteve0** [comment]
LINCOLN!!!!! Nope - this belongs to @BenHall to implement. I am not am not sure if any current customers are asking for it. Best to just talk to him about it

**Comment by lincolnthree** [comment]
@thesteve0 STEVE!!! Our paths cross again :) Thanks!
