### ISSUE TITLE
Trello board is private

### ISSUE THREAD

**Issue by jdob** [openshift-labs/learn-katacoda#154]
The instructions in the README say, for contributions, to create a card on the Trello board. The Trello board is private, so clicking the link shows an error message.

**Comment by mhausenblas** [comment]
It's by design private. Please shoot me a mail, I'll get you access …

**Comment by kaovilai** [comment]
It should at least be mentioned that one must contact someone to get trello access.

**Comment by mhausenblas** [comment]
I'm afraid I don't work at Red Hat anymore and can't help :(

**Comment by BenHall** [comment]
Please speak with @jorgemoralespou

**Comment by kaovilai** [comment]
@BenHall 
> Please speak with @jorgemoralespou

Do you mind adding this to readme?

I can submit a pull request if you want.

**Comment by BenHall** [comment]
@kaovilai Already done https://github.com/openshift-labs/learn-katacoda/commit/bd626f3c5db3220fbb03941989b86b0bc3988e23
