### ISSUE TITLE
Trying to access Katacoda course for OpenShift/Istio/Envoy

### ISSUE THREAD

**Issue by douglasawoods** [openshift-labs/learn-katacoda#157]
Cannot access this course at this time, was working before. https://learn.openshift.com/middleware/resilient-apps/

Katacoda Has A Small Tear
Sorry, it looks like something has gone wrong inside the Katacoda.

**Comment by GrahamDumpleton** [comment]
Would suggest just keep trying. It works for me, but my location means I often seem to get the system different to everyone else. That is, at least two machines hosting this and which you get often depends on where you are located from what I have seen. One of them may be having temporary issues or they may be doing an update.

**Comment by douglasawoods** [comment]
Graham,
It is working this am, thanks.

Doug

**Comment by mhausenblas** [comment]
We're re-organizing things ATM, apologies. Should all be fixed by end of day, might see some more issues here before everything is working as it should be, again.
