### ISSUE TITLE
image link broken and do i really need 4k screen resolution to use https://learn.openshift.com/middleware/debezium-getting-started/

### ISSUE THREAD

**Issue by maxandersen** [openshift-labs/learn-katacoda#161]
tried https://learn.openshift.com/middleware/debezium-getting-started/ but image link is broken and can't see what is on the screen terminal.

![2018-03-16_09-36-03](https://user-images.githubusercontent.com/54129/37511047-abf3bd88-28fd-11e8-9792-37bf73201f16.png)

**Comment by BenHall** [comment]
If you click start scenario the you should be able to begin and access the scenario.

We'll look into fixing the image path.
