### ISSUE TITLE
Log In WebConsole

### ISSUE THREAD

**Issue by steinerdani** [openshift-labs/learn-katacoda#163]
User credentials as presented in the documentaion are not working:
 Could not check CSRF token. Please try again.

**Comment by BenHall** [comment]
Thank you for letting us know. We'll investigate.

To help us, which browser version are you running? Do you have multiple tabs of the site open?

**Comment by steinerdani** [comment]
Thank you for the Feedback. It's working fine now. It's opening now a complete new tab, before it was just the tab inside the learing portal. I'm using IE11
