### ISSUE TITLE
Problem Scheduling Trainings

### ISSUE THREAD

**Issue by fatherlinux** [openshift-labs/learn-katacoda#165]
I have played with scheduling an environment for training, but am having trouble understanding the custom URL and pathway stuff. Is there any documentation anywhere on how to set up an example? Where does the "Pathway" file come from, etc? Also, it seems like there is an openshift 3.6 image, but no way to select the new one from the 3.7 playground?

![screenshot from 2018-03-20 13-38-22](https://user-images.githubusercontent.com/117605/37672420-4ca4af78-2c44-11e8-985a-4321ad075790.png)

**Comment by fatherlinux** [comment]
Tagging in @BenHall

**Comment by mhausenblas** [comment]
@fatherlinux please use Trello for this, that's internal stuff :(

**Comment by fatherlinux** [comment]
@mhausenblas sorry about that, I didn't realize he was in our Trello. Closing this....
