### ISSUE TITLE
openshift is horrible!!

### ISSUE THREAD

**Issue by rafaelmadakis** [openshift-labs/learn-katacoda#171]
OpenShift in my opnion is the worst place to deploy the application, only the Jboss POD works and stays active, all others with errors like for example: in Mysql (Crash Loop Back-off) the redhat-openjdk18-openshift also never stays active, always the error, here in Brazil the Jelastic service is very much much better and a java application with mysql, can do deploy in about 3 minutes, in openshift I am three days trying, very very weak documentation, unsuccessful . I do not understand how they intend to sell an extremely poor service. My choice to deploy 33 applications will be the Jelastic by ease.

**Comment by mhausenblas** [comment]
You're being very rude and off topic. Your rant has nothing to do with the content of learn.openshift.com and I will not feed a troll. Bye.
