### ISSUE TITLE
“Getting Started with OpenShift for Developers” Step 6.6 Doesn't Work

### ISSUE THREAD

**Issue by mangaku** [openshift-labs/learn-katacoda#175]
When attempting to "create" the image, after a long freeze, I'm logged out. When I back in my project created in the previous steps is gone.

**Comment by GrahamDumpleton** [comment]
You may have been affected by some updates being made to the platform which resulted in a restart. Can only suggest you try again. The way the environment works does mean that you will need start over as the environment you get is temporary.
