### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by nikelmark** [openshift-labs/learn-katacoda#180]
Hi,

When logging in as a developer the error occurs. (showed on screenshot)
![issue](https://user-images.githubusercontent.com/24637862/39124955-a2f6ba6e-46fd-11e8-8fe5-327b66ac4dca.jpg)

**Comment by BenHall** [comment]
Thanks @nikelmark we'll investigate this.

If you return to the console and attempt to login again, does that work?

**Comment by nikelmark** [comment]
No, same issue.

**Comment by BenHall** [comment]
@nikelmark Which OS / Browser are you running?

**Comment by nikelmark** [comment]
Windows/Chrome Browser.
