### ISSUE TITLE
environment fails to launch correctly

### ISSUE THREAD

**Issue by cjaecker** [openshift-labs/learn-katacoda#188]
Hi,
I get the following error accessing from Australia:

$ ~/.launch.sh
Starting OpenShift
Waiting for OpenShift to start... This may take a couple of moments
OpenShift started.
Configuring... OpenShift Ready
$ login
Connection to host01 closed.

The environment has expired.

Please refresh to get a new environment.

We encountered a problem with the connection.
This may have been due to the internet connection dropping.

Please refresh and try again.

This is happening accros multiple exercises and after closing and reopening the browser. I have successfully accessed before, so presume the error is on your side (my internet connection is fine)

Best wishes

**Comment by BenHall** [comment]
Thanks for letting us know. We've extended the timeout for each environment so hopefully this will be fixed.
