### ISSUE TITLE
Getting Started with OpenShift for Developers | Step 5 | create route link

### ISSUE THREAD

**Issue by thomaspeklak** [openshift-labs/learn-katacoda#192]
The first screenshot and it's description are not correct anymore. I had to click the expand arrow to see the 'create route' link. The bad thing was that I was not aware that the arrow was there to expand the service, so I tried around a bit until I found the solution

**Comment by GrahamDumpleton** [comment]
We can perhaps explain again that part of the navigation, but how to expand it was described in step 3.

> This should bring you back to the Overview page where summary information about the application you just deployed will be displayed. If only the summary for the deployment is shown on the Overview page, select the arrow to the left of the deployment name, to expand the full detail.

**Comment by thomaspeklak** [comment]
Ok. I agree that this was mentioned and I forgot about this. Then the only irritating thing is the screenshot. I just wanted to mention with this ticket that I had a short moment of disorientation. I would either update the screenshot or leave it out, but this is totally on your side. For me it is fine if you just close this issue.

**Comment by GrahamDumpleton** [comment]
We need to revise the whole scenario to update it from OpenShift 3.6 to latest OpenShift version, so we can look at changes then. We are going to have to update the screenshots then anyway as web console has changed.
