### ISSUE TITLE
Deploying Apps From Source Step 3/7 Build Failure

### ISSUE THREAD

**Issue by hjared** [openshift-labs/learn-katacoda#216]
The error I am running into in the tutorial is classified as a Build failure under the module “Foundations of OpenShift”-- “Deploying Applications From Source”-- Step 3/7, Topic 3- Viewing Builder Logs.  While it does allow me to see the log, the attempt to build from the Git Repository URL fails. It seems to download and copy completely fine until trying to “collect gyp==0.1 (from requirements.txt (line 6))”. 

[$R57TC6T.log](https://github.com/openshift-labs/learn-katacoda/files/2090296/R57TC6T.log)
![ry22mse](https://user-images.githubusercontent.com/40173510/41236816-8f1cbb7e-6d81-11e8-9fe9-05c13ccae95f.PNG)

**Comment by GrahamDumpleton** [comment]
The Python package list being used was possibly generated using ``pip freeze`` when using an older version of Django. At the time that resulted in the ``gyp`` package being included. For whatever reason, the downloadable package file for ``gyp`` has been removed from the Python package repository (PyPi), even though the release entry for that package version still exists. Removing packages from PyPi would generally only be done in extreme circumstances as removing packages can be break lots of stuff, so I have no idea why the package has been removed. I have removed the ``gyp`` package entry from the package list and should all work fine now.
