### ISSUE TITLE
missing video

### ISSUE THREAD

**Issue by jgershater** [openshift-labs/learn-katacoda#261]
this lesson
https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-7
states
'Once you have watched the background video,"

there is no video to view

**Comment by BenHall** [comment]
Thanks for letting us know. /cc @fatherlinux

**Comment by fatherlinux** [comment]
@jgershater roger that. I am actually recording new versions of all of the videos. The videos for hosts, images, and orchestration are actually a bit out of date, so I am going to record them all from scratch. Just haven't quite had time yet :-)
