### ISSUE TITLE
Quota issues in "Foundations of OpenShift > Getting Started with OpenShift for Developers" class.

### ISSUE THREAD

**Issue by tombenninger** [openshift-labs/learn-katacoda#270]
During section 6 of "Getting Started with OpenShift for Developers", when I was trying to launch the second application with in the project, I received two errors:

```
Failed to list resourcequotas/v1 (502)
Failed to list appliedclusterresourcequotas/v1 (502)
```

From the overview, it looked like the pod was spun up, but I was then unable to fully access the web service through the route; the page would start to load, but never load the actual map.

I started the learning scenario over, and saw the same issue.

**Comment by BenHall** [comment]
The scenario has recently been updated to OpenShift 3.11 so this should no longer be an issue
