### ISSUE TITLE
Broken link to OpenShift plugin for Eclipse page

### ISSUE THREAD

**Issue by fraik** [openshift-labs/learn-katacoda#274]
Greetings,

On the [first page](https://learn.openshift.com/introduction/getting-started/) of the getting started tutorial of the OpenShift Interactive Learning Portal there is a broken link to the OpenShift plugin for Eclipse page.

### Description
The anchor-element is the following:
`<a href="JBoss Tools" target="_blank" rel="nofollow">https://tools.jboss.org/features/openshift.html</a>`

The hyperlink "JBoss Tools" points towards https://katacoda.com/embed/openshift/courses/introduction/getting-started/JBoss%20Tools, which gives the disappointing message: **"Scenario not found. Please check your embedding code configuration."** 

Ofcourse it's pretty clear where to go for more info (the anchor-element text property says https://tools.jboss.org/features/openshift.html...) but it might be a good idea to check whether more links are pointing elsewhere and have a good possibility to further tune your link checkers.

### Environment
- Browser: Google Chrome Version 70.0.3538.110 (Official Build) (64-bit)
- OS: Mac OS X 10.13.6

Kind regards,
Freek

**Comment by BenHall** [comment]
Thanks for letting us know! @mhausenblas could you let the team know please?
