### ISSUE TITLE
Unable to launch apps using odo in 3.11 playground

### ISSUE THREAD

**Issue by jankleinert** [openshift-labs/learn-katacoda#276]
I've been working on an updated scenario for odo. 
I am working off the openshift-3-11 image and I see this behavior both in my fork and if I just try it in the 3.11 playground. These same steps work without any issues on openshift online pro and on another openshift cluster, but I consistently get this error in the katacoda environment.

Steps to reproduce:
1. Go to https://learn.openshift.com/playgrounds/openshift311/ and wait for the environment to be ready (sometimes this is taking 7-8 minutes - is that normal?)
2. `odo login -u developer -p developer  <whatever the host is>.environments.katacoda.com`
3. `odo project create myproject`
4. `odo app create wildwest`
5. `git clone https://github.com/openshift-evangelists/Wild-West-Frontend ~/frontend`
6. `cd frontend`
7. `odo create nodejs frontend`

At this point, if you run `oc get pods` you'll see something like this:

```
NAME                         READY     STATUS                  RESTARTS   AGE
frontend-wildwest-1-deploy   1/1       Running                 0          1m
frontend-wildwest-1-hxtnb    0/1       Init:CrashLoopBackOff   2          1m
```

I'm getting this Init:CrashLoopBackOff for anything I try to deploy with odo on the 3.11 playground, but the same steps work on other openshift environments. We think it may possibly be an issue with available memory / limits. Running `free -m` gives the following:

```
             total        used        free      shared  buff/cache   available
Mem:           7983        2710         127           8        5144        4862
Swap:             0           0           0
```
 
Please let me know if there's any other info I can provide. We'd really like to get odo working with katacoda 3.11 for KubeCon next week :)

**Comment by BenHall** [comment]
The container is crashing due to file permissions.
```
45f3bc494569        docker-registry.default.svc:5000/openshift/nodejs@sha256:3cc041334eef8d5853078a0190e46a2998a70ad98320db512968f1de0561705e    "sh -c '\nSRC=/opt/..."   34 seconds ago      Exited (1) 32 seconds ago                        k8s_copy-files-to-volume_frontend-wildwest-1-2k8dx_myproject_9a3b13cf-f743-11e8-9a72-0242ac110029_6

$ docker logs 45f3bc494569
mkdir: cannot create directory '/mnt/app-root.setup-volume': Permission denied
tar: /mnt/app-root.setup-volume: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
mv: cannot stat '/mnt/app-root.setup-volume': No such file or directory
```

The PVs are mounted to /data on the host and configured via https://github.com/openshift-labs/learn-katacoda/blob/master/playgrounds/openshift311/env-init.sh#L3-L5

```
$ pwd
/data
$ ls -lha
total 48K
drwxr-xr-x. 12 root root 4.0K Dec  3 21:30 .
dr-xr-xr-x. 20 root root 4.0K Dec  3 21:30 ..
drwxrwxrwx.  2 root root 4.0K Dec  3 21:30 pv-01
drwxrwxrwx.  2 root root 4.0K Dec  3 21:30 pv-02
drwxrwxrwx.  2 root root 4.0K Dec  3 21:30 pv-03
drwxrwxrwx.  2 root root 4.0K Dec  3 21:30 pv-04
drwxrwxrwx.  2 root root 4.0K Dec  3 21:30 pv-05
drwxrwxrwx.  2 root root 4.0K Dec  3 21:30 pv-06
drwxrwxrwx.  2 root root 4.0K Dec  3 21:30 pv-07
drwxrwxrwx.  2 root root 4.0K Dec  3 21:30 pv-08
drwxrwxrwx.  2 root root 4.0K Dec  3 21:30 pv-09
drwxrwxrwx.  2 root root 4.0K Dec  3 21:30 pv-10
```

**Comment by BenHall** [comment]
Thanks for the tips @GrahamDumpleton 

It's related to not having `svirt_sandbox_file_t` set on the directory. I've updated the initial script to create the PV, please update in your own scenario - https://github.com/openshift-labs/learn-katacoda/commit/cde4314c345ef643eb4b2a98fbe6bccd167d497f#diff-9c561a5570484df2060eb2a995991208R4

```
$ chcon -t svirt_sandbox_file_t /data/pv-*
$ oc rsh blog-django-py-1-nhssb
(app-root)sh-4.2$ ls -lha /opt/app-root/src/media
total 8.0K
drwxrwxrwx.  2 default root 4.0K Dec  4 05:59 .
drwxrwxr-x. 11 default root 4.0K Dec  4 06:03 ..
```

It seems to fix ODO

```
$ oc get pods -w
NAME                         READY     STATUS     RESTARTS   AGE
frontend-wildwest-1-bb566    0/1       Init:0/2   0          5s
frontend-wildwest-1-deploy   1/1       Running    0          8s
frontend-wildwest-1-bb566   0/1       Init:1/2   0         30s
frontend-wildwest-1-bb566   0/1       PodInitializing   0         30s
frontend-wildwest-1-bb566   1/1       Running   0         32s
frontend-wildwest-1-deploy   0/1       Completed   0         35s
```

**Comment by GrahamDumpleton** [comment]
Any idea about why ``oc rsh`` was failing?
