### ISSUE TITLE
oc rsh not working in openshift-3-11 image

### ISSUE THREAD

**Issue by jankleinert** [openshift-labs/learn-katacoda#278]
Similar to what was reported in https://github.com/openshift-labs/learn-katacoda/issues/233, oc rsh isn't working in the openshift-3-11 image.

example:

```
$ oc get pods
NAME                       READY     STATUS    RESTARTS   AGE
backend-wildwest-1-lr8l8   1/1       Running   0          37m
$ oc rsh backend-wildwest-1-lr8l8
error: unable to upgrade connection: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 400 (Bad Request)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>400.</b> <ins>That’s an error.</ins>
  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins>
```

**Comment by BenHall** [comment]
The reason this sometimes works and doesn't depends on if the user has logged into the developer account, and as such set the URL to the master. 

For example: https://access.redhat.com/solutions/2212131

The workaround to ensure it consistently works is `oc --server https://master:8443 rsh`

**Comment by GrahamDumpleton** [comment]
Are you saying in your setup you use Apache in front of OpenShift? It is not part of the normal OpenShift setup to have Apache involved.

**Comment by BenHall** [comment]
No, because of the lack of public IP addresses, environments.katacoda.com goes via a Google LB which doesn't support SPYD

**Comment by BenHall** [comment]
The reason we need to login with the public_master_url is because the signer hasn't added got master (hostname of the environment) as a valid url

```
$ curl -k -v -XHEAD  'https://master:443/'
* About to connect() to master port 443 (#0)
*   Trying 127.0.0.1...
* Connected to master (127.0.0.1) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=*.2886795306-80-cykoria05.environments.katacoda.com
*       start date: Dec 05 03:02:28 2018 GMT
*       expire date: Dec 04 03:02:29 2020 GMT
*       common name: *.2886795306-80-cykoria05.environments.katacoda.com
*       issuer: CN=openshift-signer@1543978699
```

**Comment by GrahamDumpleton** [comment]
Sounds like the set up of the environment should use ``oc config set-cluster`` to created a context which is linked to the server address if must use ``https://master:8443``. Once context is created  set that as the one to use. Having to pass it as an argument to ``oc login`` or ``oc rsh`` commands is a clumsy way of handling it. Also doesn't explain why this was never a problem before 3.9.

**Comment by BenHall** [comment]
With 3.9, the login / auth workflow changed with the x509 being checked.

**Comment by BenHall** [comment]
We use watch frequently. Thanks for the repo steps, I'll take a look and see

**Comment by jankleinert** [comment]
Thanks for helping us investigate this! To make sure I'm understanding
correctly, it sounds like there is not a  quick way to get this working,
particularly for the odo commands. Is that right? I want to be sure I can
set accurate expectations around whether or not I'll be able to have an
updated odo katacoda scenario live by the end of this week.

**Comment by BenHall** [comment]
@jankleinert Give me an hour to explore. We might be able to have a temporary solution in place

**Comment by BenHall** [comment]
@jankleinert  Could you try this please?

```
curl -LO https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem
oc login -u developer -p developer https://master:8443 --certificate-authority=lets-encrypt-x3-cross-signed.pem
```

**Comment by jankleinert** [comment]
@BenHall Yes, that works! Thank you!

**Comment by BenHall** [comment]
@jankleinert Great. I'll see if I can make some of this happen automatically, but at least in the meantime we have something to proceed with.
