### ISSUE TITLE
OpenShift Playground 3.11 isn't loading

### ISSUE THREAD

**Issue by jankleinert** [openshift-labs/learn-katacoda#284]
I haven't been able to get the 3.11 playground to successfully load today. I've tried several times over the past ~6 hours or so and it never successfully gets past this:

```
$ launch.sh
Starting OpenShift
Waiting for OpenShift to start... This may take a couple of minutes
..........................................................................................................................................................................................................................................................................................................................................................................................................
```

**Comment by BenHall** [comment]
I thought we had rolledback... we had an issue with expired SSL certs and
then network manager taking too long to start. Sorry about this. I will
check.

**Comment by BenHall** [comment]
We had only rolled back half the changes :(

The new image with 0.17 is just being deployed

**Comment by BenHall** [comment]
OK, the issue was related to setting the context to have the default letsencrypt cert used.

It should be back to normal now and we'll investigate again tomorrow.
