### ISSUE TITLE
Istio 1.0.X workshopm: Monitoring and Tracing -> Custom Metric istioctl command not found

### ISSUE THREAD

**Issue by soheilade** [openshift-labs/learn-katacoda#285]
I am following this workshop from openshift 
Monitoring and Tracing -> Custom Metric

when running this command
istioctl create -f istiofiles/recommendation_requestcount.yml -n istio-system

I get the error 
 istioctl command not found
any idea?

**Comment by soheilade** [comment]
After running  ./install-microservices.sh in other tutorials, when running 
curl http://customer-tutorial.2886795269-80-kitek03.environments.katacoda.com
I also get the error that Application is not available in an html file. 
any help here is also appreciated.

**Comment by BenHall** [comment]
Thanks for letting us know about this. We've attempted to debug and isolated the issue a couple of times but we haven't been able to. 

Could you please try again and let us know if you continue to have issues?

I'm closing this for now but please reopen if you continue to have problems.

**Comment by merusso** [comment]
I ran into this same issue. Apparently, istioctl wasn't added to the path in this tutorial. The following command fixes the issue:

`export PATH=$PATH:/root/installation/istio-1.0.2/bin`
