### ISSUE TITLE
Openshift Interactive learning not responding 

### ISSUE THREAD

**Issue by rameshgowru** [openshift-labs/learn-katacoda#290]
Hi Team, 

could not start interactive learning . I have pasted screenshot below and help me to start course . 

![image](https://user-images.githubusercontent.com/14900900/49713166-a8a2f500-fc82-11e8-97b7-bdddfe49339b.png)

Thanks
Ramesh

**Comment by mhausenblas** [comment]
Thanks @rameshgowru and we're on it.

**Comment by BenHall** [comment]
Thanks for letting us know. This has been resolved.

Sorry for any inconvenience.
