### ISSUE TITLE
Bug in Interactive learning portal - transferring files in and out of containers - part 5

### ISSUE THREAD

**Issue by torefredriksen** [openshift-labs/learn-katacoda#308]
Hi, I think there is a bug with creating a pvc in the lab environment
When I run the command : 

`
oc set volume dc/dummy -add --name=tmp-mount --claim-name=data --type=pvc --claim-size=1G --mount-path=/mnt

oc rollout status dc/dummy
`
It is unable to create the volume...

> no persistent volumes available for this claim and no storage class is set

**Comment by BenHall** [comment]
Hi @torefredriksen 

Thanks for letting us know. We'll investigate now.
