### ISSUE TITLE
The ImageStreamTag "fis-java-openshift:2.0" is invalid: from

### ISSUE THREAD

**Issue by jmanuelcalvo** [openshift-labs/learn-katacoda#309]
In the LAB Developing APIs using Red Hat OpenShift and JBoss Fuse Step 2 of 5 when I execute the command  oc start-build mypeopleservice I have the following error:

$ oc start-build mypeopleservice
The ImageStreamTag "fis-java-openshift:2.0" is invalid: from: Error resolving ImageStreamTag fis-java-openshift:2.0 in namespace openshift: unable to find latest tagged image

When I 

$ oc get is -n openshift | grep fis
fis-java-openshift             172.30.205.13:5000/openshift/fis-java-openshift             2.0,1.0
fis-karaf-openshift            172.30.205.13:5000/openshift/fis-karaf-openshift            2.0,1.0

$ oc describe is fis-java-openshift -n openshift
Name:                   fis-java-openshift
Namespace:              openshift
Created:                About an hour ago
Labels:                 <none>
Annotations:            openshift.io/display-name=Red Hat Fuse 6.3 Java
                        openshift.io/image.dockerRepositoryCheck=2019-01-09T15:40:37Z
                        openshift.io/provider-display-name=Red Hat, Inc.
Docker Pull Spec:       172.30.205.13:5000/openshift/fis-java-openshift
Image Lookup:           local=false
Unique Images:          0
Tags:                   2

2.0
  tagged from registry.redhat.io/jboss-fuse-6/fis-java-openshift:2.0
    prefer registry pullthrough when referencing this tag

  Red Hat Fuse 6.3 Java S2I images.
  Tags: builder, jboss-fuse, java, xpaas, hidden
  Supports: jboss-fuse:6.3.0, java:8, xpaas:1.2

  ! error: Import failed (InternalError): Internal error occurred: Get https://registry.redhat.io/v2/jboss-fuse-6/fis-java-openshift/manifests/2.0: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/articles/3399531
      About an hour ago

1.0
  tagged from registry.redhat.io/jboss-fuse-6/fis-java-openshift:1.0
    prefer registry pullthrough when referencing this tag

  Red Hat Fuse 6.2.1 Java S2I images.
  Tags: builder, jboss-fuse, java, xpaas, hidden
  Supports: jboss-fuse:6.2.1, java:8, xpaas:1.2

  ! error: Import failed (InternalError): Internal error occurred: Get https://registry.redhat.io/v2/jboss-fuse-6/fis-java-openshift/manifests/1.0: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/articles/3399531
      About an hour ago
$

**Comment by BenHall** [comment]
Sorry for the delay on this @jmanuelcalvo. I've confirmed the issue and investigating a solution.

**Comment by ryanj** [comment]
Thanks for reporting, @jmanuelcalvo.  

I think we have removed all Fuse content from the site index, so I don't expect new users to encounter this issue.

Feel free to reopen if needed.
