### ISSUE TITLE
jq command not available

### ISSUE THREAD

**Issue by shaneboulden** [openshift-labs/learn-katacoda#311]
A couple of steps in the `Kubernetes API Fundamentals` lab use `jq` for parsing the API output, though it isn't available from the CLI.

The entire command output is below:
```
$ curl http://localhost:8001/apis/rd.example.com/v1alpha1 | jq
bash: jq: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   461  100   461    0     0   114k      0 --:--:-- --:--:-- --:--:--  150k
(23) Failed writing body
```
A screenshot is available [here](https://i.imgur.com/63YNYal.png)

**Comment by BenHall** [comment]
Hi @shaneboulden - Thanks for letting us know. We've fixed the issue.
