### ISSUE TITLE
text not appearing in box, "Copy to Editor" button partially hidden

### ISSUE THREAD

**Issue by mhrivnak** [openshift-labs/learn-katacoda#312]
In the "Ansible Kubernetes Module" content, the text for the very first gray box that has a "Copy to Editor" button is in the wrong place. The text is appearing under the box, and the box itself is so short that the button is mostly hidden.

The source is here, but the bug isn't obvious to me at first glance: https://github.com/openshift-labs/learn-katacoda/blob/master/ansibleop/ansible-k8s-modules/step1.md

![ansible_k8s_module_bug](https://user-images.githubusercontent.com/53091/51063140-ac020700-15c7-11e9-853e-3066c302de3b.png)

**Comment by BenHall** [comment]
Thank you for reporting! This looks like a potential browser / OS issue. Could you tell us what you are running so we can try and reproduce?

**Comment by mhrivnak** [comment]
I'm on Fedora 29 with Chrome "Version 71.0.3578.98 (Official Build) (64-bit)"

I see the same behavior with Firefox 64.0 (firefox-64.0-4.fc28.x86_64 to be specific).

**Comment by BenHall** [comment]
Firefox on Fedora?

**Comment by mhrivnak** [comment]
Yes, all on the same Fedora 29 machine.

**Comment by BenHall** [comment]
OK, let me get Fedora setup and try. Thanks!

**Comment by mhrivnak** [comment]
Just for fun, I loaded that page in Chrome on my Pixel 3. Same issue. Of course the site doesn't render well on a phone, but I think this bug may not be Fedora-specific.

**Comment by BenHall** [comment]
Thanks for your help with this @mhrivnak - This issue has now been fixed.

**Comment by mhrivnak** [comment]
Thanks!
