### ISSUE TITLE
Tutorial won't login

### ISSUE THREAD

**Issue by TimMurnaghan** [openshift-labs/learn-katacoda#313]
https://learn.openshift.com/introduction/getting-started/

Second screen of the getting started tutorial trying to log in to the dashboard:

Could not check CSRF token. Please try again.

**Comment by BenHall** [comment]
Hi @TimMurnaghan 
Sorry for the issue you faced. We see CSRF errors occur if the dashboard login page is opened in two separate tabs or if a proxy is modifying network requests.

Could either of those be the case here?


Ben
