### ISSUE TITLE
Kubernetes API step 3 of 5 specify default namespace

### ISSUE THREAD

**Issue by hupiper** [openshift-labs/learn-katacoda#317]
For replica sets, the first command is oc get pods in default. We aren't in default at this point in the lab, and running oc get pods returns nothing (we just deleted our pod in the previous step). 

It might be better to specify the namespace: oc get pods -n default, or switch to the default project.

**Comment by BenHall** [comment]
Thanks for the suggestion @hupiper. Let me share this with the content creator @madorn for their thoughts...

**Comment by hupiper** [comment]
or, if the default namespace is actually myproject, then maybe we should show that it is empty.

**Comment by madorn** [comment]
@hupiper @benHall, thanks! Fixed in #319.
