### ISSUE TITLE
Etcd Operator -  step 3 of 8 - use oc get pods 

### ISSUE THREAD

**Issue by hupiper** [openshift-labs/learn-katacoda#324]
After deploying the etcd operator, we verify the deployment was created, and verify the pods are running. The same command (oc get deploy) is incorrectly used for both in the lab:

`Verify the Etcd Operator Deployment was successfully created:

oc get deploy

Verify the Etcd Operator Deployment pods are running:

oc get deploy`

The second command should be `oc get pods`

**Comment by madorn** [comment]
@hupiper thanks! Fixed in #325. Additional errors found in other steps and submitting PRs for them now.
