### ISSUE TITLE
Visual editor not matching up with files on disk

### ISSUE THREAD

**Issue by djwhatle** [openshift-labs/learn-katacoda#336]
## _Issue Update_ Jan 26
This often occurs when two files sharing the same name and are opened simultaneously in the visual editor. In this example, having two different `main.yml` files open at the same time can exhibit the issue. 

_It is possible to work around this by exiting all open tabs in the visual editor._

## Issue Summary
I'm working on the __[Ansible Operator Overview](https://learn.openshift.com/ansibleop/ansible-operator-overview/)__ scenario, and found that it's possible for the visual editor to get out of sync with the files on the disk viewed through the CLI (when viewed with cat/vim/whatever)

I have a _slight hunch_ this might have to do with changing a file from the CLI while it's open in the visual editor, but I haven't done the research to totally back this up.

**Edit: The reproducer below doesn't reliably reproduce the issue, but did work for me several times.** 

## Reproducer steps (following steps from sidebar):

1. Run `operator-sdk new memcached-operator --api-version=cache.example.com/v1alpha1 --kind=Memcached --type=ansible --skip-git-init`
2. Run `cd memcached-operator`
3. Run `ansible-galaxy install dymurray.memcached_operator_role -p ./roles`
4. Run `rm -rf ./roles/Memcached`
5. Move to Step 6 of the scenario
6. Open `memcached-operator/watches.yaml` in visual editor
7. Click "Copy to Editor" button at the bottom of Step 6
9. Use the provided `oc login` command on Step 7
10. Run `oc create -f deploy/crds/cache_v1alpha1_memcached_crd.yaml --as system:admin`
11. Run `operator-sdk build memcached-operator:v0.0.1`
12. Run `oc new-project tutorial`
13. Open `memcached-operator/deploy/operator.yaml` in the visual editor
14. Run `sed -i 's|REPLACE_IMAGE|memcached-operator:v0.0.1|g' deploy/operator.yaml`
15. Run `sed -i 's|Always|Never|g' deploy/operator.yaml`
16. Run `cat deploy/operator.yaml`
17. Open/re-open `memcached-operator/deploy/operator.yaml` in the visual editor`

18. Notice how the visual editor and the result from the cat command don't match

## Workaround
1. Make _any_ edit to `operator.yaml` in the visual editor, and it will persist to disk as expected. Running `cat operator.yaml` after editing manually in the visual editor seems to get things back in sync.

## Annotated screenshot of issue occurring
![image](https://user-images.githubusercontent.com/7576968/51405374-309ed900-1b24-11e9-9e2b-af66c844421f.png)

**Comment by djwhatle** [comment]
Updated the main comment, mirroring here as a new comment:

---

**This often occurs when two files sharing the same name and are opened simultaneously in the visual editor. In this example, having two different main.yml files open at the same time can exhibit the issue.**

**It is possible to work around this by exiting all open tabs in the visual editor.**

**Comment by BenHall** [comment]
Thanks @djwhatle for the update. We'll investigate a longer term solution.
