### ISSUE TITLE
Getting Started with OpenShift for Developers - Console does not open

### ISSUE THREAD

**Issue by gene8084** [openshift-labs/learn-katacoda#339]
Step 2, Exploring the Console does nothing.  

Instructions.
To begin, click on the Dashboard tab in the console frame of this browser window. This will open the web console link in another tab or window of your browser. (Does not happen)
You should see an OpenShift Origin window with Username and Password forms, similar to this one:
(Nope)

Also tried selecting the + and picking the first option. 
View HTTP port 8443 on Host 1

MSG
This page isn’t working 2886795416-8443-simba02.environments.katacoda.com is currently unable to handle this request.

**Comment by BenHall** [comment]
@gene8084 Sorry about the interruption. It should be accessible again, we had to perform some short maintenance on a core component.
