### ISSUE TITLE
etcd operator - Step 1 out of 8 - oc get etcdcluster

### ISSUE THREAD

**Issue by DirectedSoul1** [openshift-labs/learn-katacoda#344]
After deploying a CRD for the etcd operator, crd will successfully created
` $ oc get crd`

NAME                                    CREATED AT
alertmanagers.monitoring.coreos.com     2019-01-24T16:24:45Z
bundlebindings.automationbroker.io      2019-01-24T16:29:20Z
bundleinstances.automationbroker.io     2019-01-24T16:29:19Z
bundles.automationbroker.io             2019-01-24T16:29:21Z
etcd-hegde.database.coreos.com          2019-01-24T18:42:48Z
etcdclusters.etcd.database.coreos.com   2019-01-24T18:48:16Z
prometheuses.monitoring.coreos.com      2019-01-24T16:24:46Z
prometheusrules.monitoring.coreos.com   2019-01-24T16:24:46Z
servicemonitors.monitoring.coreos.com   2019-01-24T16:24:46Z
 
However after issuing the command 

`$ oc get etcdcluster
No resources found.`

Instead the etcdcluster should be listed

**Comment by cooktheryan** [comment]
i believe the command should be 

```
$ oc get crd/etcdclusters.etcd.database.coreos.com
NAME                                    CREATED AT
etcdclusters.etcd.database.coreos.com   2019-01-24T19:44:58Z
```

**Comment by DirectedSoul1** [comment]
The above command works. Thanks for the edit @cooktheryan

**Comment by DirectedSoul1** [comment]
The following scenario needs the same modification; https://learn.openshift.com/operatorframework/go-operator-podset/ **Scenario 2 out of 7** ; after creation of podsets.app.example.com crd , the command as mentioned as ```oc get podset``` needs to be changes as ```$ oc get crd/podsets.app.example.com``` 

NAME                      CREATED AT
podsets.app.example.com   2019-01-24T21:38:12Z
