### ISSUE TITLE
Spring Boot development on OpenShift bug

### ISSUE THREAD

**Issue by Bertrand67** [openshift-labs/learn-katacoda#345]
Hello,

In tutorial "Spring Boot development on OpenShift" the step 5 doesn't work.
After command line "oc rollout status dc/fruits", pod crashes with error : "Cannot determine embedded database driver class for database type NONE".

It's the second time a tutorial doesn't work, you should update them more frequently...

Regards,

Bertrand

**Comment by jankleinert** [comment]
Closing this since there haven't been any updates in over 1 year and I was unable to reproduce the error. Please open a new issue if this persists.
