### ISSUE TITLE
OpenShift Commons London Operator-Framework Workshop

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#347]
Red Hat will be hosting another live Operator Framework Workshop in London on Wednesday, January 30th, 2019, 8am to 12pm GMT.

I wanted to open this issue in case we anticipate an issue with 50 attendees simultaneously hitting https://learn.openshift.com/operatorframework modules.

https://www.eventbrite.com/e/kubernetes-operators-framework-workshop-openshift-commons-gathering-tickets-54133545893

Thanks!

@BenHall @mhausenblas

**Comment by mhausenblas** [comment]
Yes, we'll have to ask @BenHall nicely to provision the training ;)

**Comment by BenHall** [comment]
This has been scheduled. I'll send you dedicated link privately.
