### ISSUE TITLE
Environment should come with a project selected other than default

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift-labs/learn-katacoda#35]
This is related to #34 where if the user logged is by default is system:admin, the project used by default is "default".

When testing an scenario I did not select a project or a user, as I was validating the instructions, and I did a deployment that I wanted to delete. I did:

````
$ oc delete all --all
$ oc delete all --all
buildconfig "zerodowntime-talk" deleted
imagestream "zerodowntime-talk" deleted
deploymentconfig "docker-registry" deleted
deploymentconfig "router" deleted
deploymentconfig "zerodowntime-talk" deleted
service "docker-registry" deleted
service "kubernetes" deleted
service "router" deleted
service "zerodowntime-talk" deleted
````

As you can see, I deleted the router and the registry, making that instance unusable from that moment.

**Comment by jorgemoralespou** [comment]
Opinions?

cc/ @marekjelen @mhausenblas @gshipley @thesteve0 @GrahamDumpleton @Charlaxy

**Comment by thesteve0** [comment]
Commented in the other thread

On Thu, Jun 22, 2017 at 8:58 AM, Jorge Morales Pou <notifications@github.com

**Comment by mhausenblas** [comment]
Seems stale, please re-open if it persists.
