### ISSUE TITLE
wrong version of operator-sdk is present in environment

### ISSUE THREAD

**Issue by mhrivnak** [openshift-labs/learn-katacoda#350]
Version 0.3.0 of operator-sdk is supposed to be installed with openshift 3.11, by virtue of this: https://github.com/openshift-labs/learn-katacoda/blob/master/environments/openshift-3-11/scripts/10_op-sdk-setup.sh#L35

But in this exercise, I see 0.2.0 is present: https://learn.openshift.com/ansibleop/ansible-operator-overview/

This mis-match is causing parts of the exercise to fail. It seems like the environment image is not reflecting what's in the script. Maybe an old image is being used for some reason?

Another observation is that we did not encounter this particular problem recently despite using this exercise regularly. Even earlier today, in the dedicated training infrastructure you kindly provided, this problem did not occur. I didn't explicitly check the version, but I did not see the failures and thus assume it was 0.3.0.

**Comment by BenHall** [comment]
So you are only seeing this in the ondemand?

**Comment by mhrivnak** [comment]
> So you are only seeing this in the ondemand? We'll double check and redeploy the environment

Yes. The "training" env is expired at this point, so I can't check there, but I ran the entire exercise this morning without problem in the training env. That would not have been possible if it had this older versin of `operator-sdk`.

**Comment by mhrivnak** [comment]
> So you are only seeing this in the ondemand? We'll double check and redeploy the environment

And even in the on-demand infra, this has been working fine recently. It seems like something regressed quite recently.

**Comment by BenHall** [comment]
How can we check the installed version? :)

**Comment by mhrivnak** [comment]
```
$ operator-sdk --version
operator-sdk version v0.3.0
```

Looks like it's fixed? I reloaded the environment and ran that just now.

**Comment by BenHall** [comment]
We made a mistake last night when prepping the workshop. Sorry about that. We'll create an additional check for image<>build<>live version of the operator-sdk version.
