### ISSUE TITLE
dashbord problem

### ISSUE THREAD

**Issue by erdembngl** [openshift-labs/learn-katacoda#352]

**Comment by erdembngl** [comment]
interactive learning does not work on Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by BenHall** [comment]
Sorry about this. Could you please give an indication of the error / problem you are seeing? A screenshot would be great.

**Comment by BenHall** [comment]
Closing, but if you are still having problems please let us know.
