### ISSUE TITLE
Citrus tutorial is not linked / shown on learn.openshift.com

### ISSUE THREAD

**Issue by tnobody** [openshift-labs/learn-katacoda#353]
@mhausenblas 
The recently added tutorial for citrus-framework with openhift  (external/citrus/intro) is not shown on the website (learn.openshift.com)

**Comment by mhausenblas** [comment]
Thanks @tnobody.

@BenHall can we make it so that is accessible up via https://learn.openshift.com/external/citrus/intro but not in one of the existing top-level categories (we've yet to come up with something there)?

**Comment by BenHall** [comment]
Two files need to be created.

1) `external-pathway.json` in the root of the repository. This will point to the partner content, in this case citrus. Copy the subcourse approach from https://github.com/openshift-labs/learn-katacoda/blob/master/middleware-pathway.json#L5-L11

2) `citruis-pathway.json` in the external directory. This will point to which scenarios we want to be accessible. See the related example at https://github.com/openshift-labs/learn-katacoda/blob/master/middleware/middleware-spring-boot-pathway.json

**Comment by mhausenblas** [comment]
Thanks, @BenHall. @tnobody can you PR this please?
