### ISSUE TITLE
Operator-Framework Workshop for APAC

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#358]
Red Hat will be hosting another live Operator Framework Workshop on:

Tuesday, February 19th, 6:30pm to 3:00am CST
Wednesday, February 20th, 6:30pm to 3:00am CST

We anticipate 50 attendees simultaneously hitting https://learn.openshift.com/operatorframework modules.

Thanks!

@BenHall @mhausenblas

**Comment by BenHall** [comment]
This has been scheduled. 

I think I've converted the time to UTC correctly. 

Wednesday 20-02-2019 at 00:30 UTC until Wednesday 20-02-2019 at 09:00 UTC
Thursday 21-02-2019 at 00:30 UTC until Thursday 21-02-2019 at 09:00 UTC
