### ISSUE TITLE
OpenShift web console not working

### ISSUE THREAD

**Issue by ga2tuaz** [openshift-labs/learn-katacoda#361]
Hi there

There seems to be an issue with the OpenShift learning platform web console. It basically just hangs and is completely unusable :( Please can you advise?

Thanks,
Fiona

**Comment by BenHall** [comment]
Hi @ga2tuaz 

Sorry you are experiencing issues with the web console. Could you tell us which scenario you are completing and we'll investigate.

Thanks

**Comment by ga2tuaz** [comment]
Hi Ben

Thanks for the speed reply. 

I'm on the "getting started for developers" step 2. I've tried IE and firefox. And the essential reboot of course ;) Am on a MacBook. 

Thanks,
Fiona

**Comment by BenHall** [comment]
Hi,

Thanks for trying those things. Are you still seeing issues? We seem to be able to load it here.

Could you confirm your region (US, Europe, Asia etc) increase it's a connectivity issue.

Ben

**Comment by ga2tuaz** [comment]
Hey,

Ah, no it loaded straight away this time - excellent! Sorry to have wasted your time and many thanks for the help :)

Fiona

**Comment by BenHall** [comment]
Great news! I'm guessing connectivity issue. We'll keep an eye on it.

Let us know if you need anything else.

**Comment by ga2tuaz** [comment]
Will do, thanks again!
