### ISSUE TITLE
{{execute}} suddenly adding extra spaces

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#363]
Hi,

It appears that the execute tag is now adding extra spaces when pasting into the terminal.

This is causing the commands the include EOF to not work properly.

Here is an example:

Step 1 of 5: https://learn.openshift.com/operatorframework/k8s-api-fundamentals/

Source: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework/k8s-api-fundamentals/step1.md

**Comment by BenHall** [comment]
Thanks and sorry for the issue. A combination of the multi-line code snippets (```) and some changes we made caused the issue.

It's been fixed and we've added additional tests covering the ``` syntax used.
