### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by Voigtus** [openshift-labs/learn-katacoda#364]
Hey,

I finished the lesson for Spring-Rest-Services on OpenShift. I was interested in the Snowdrop project, but could not access the site, as you can see in the attached screenshot.

- URL of the tutorial: https://learn.openshift.com/middleware/courses/middleware-spring-boot/spring-rest-services
- URL provided by tutorial: https://snowdrop.me/

I just want to give you a heads up.
Have a nice day.

![snowdropdown](https://user-images.githubusercontent.com/21288767/53414501-33b4a100-39cf-11e9-8a03-24922e408002.PNG)

**Comment by BenHall** [comment]
Thanks, it looks like the HTTPS version is down but you can access the HTTP version - http://snowdrop.me/

We'll get this updated.

/cc @marekjelen Could you let the snowdrop team know about the HTTPS routing issue please?

**Comment by gytis** [comment]
https://snowdrop.me is not working

**Comment by marekjelen** [comment]
it seems to work now
