### ISSUE TITLE
Web Accessible Actions on OCF Step 2

### ISSUE THREAD

**Issue by Voigtus** [openshift-labs/learn-katacoda#365]
Hey,

I was on a good run with some more tutorials, but encountered (maybe) a bug in the [Serverless action tutorial](https://learn.openshift.com/serverless/3-web-accessible-actions). When I try to deploy the action with the given OpenWhisk command it fails.
```
$ wsk -i action create --web=true my-echo target/my-echo.jar --main com.example.FunctionApp
error: The API host is not valid: An API host must be provided.
```
In case of an error on my side I restarted the tutorial and had to stop at the same step, but had another error.
```
$ wsk -i action create --web=true my-echo target/my-echo.jar --main com.example.FunctionApp
error: Unable to create action 'my-echo': Put https://openwhisk-faas.2886795285-80-frugo02.environments.katacoda.com/api/v1/namespaces/_/actions/my-echo?overwrite=false: stopped after 10 redirects
```
It seems like when I restarted the lesson some folders weren't created.
The absent folders were:
- incubator-openwhisk-devtools
- istio-tutorial
- rhoar-getting-started

I tested it in a Firefox and a Chrome and both didn't create the folders after a restart of the lesson. The only fix was to close and reopen the browser.

If this problem occurs because of an error on my side I would really appreciate a hint how to solve this.

**Comment by marekjelen** [comment]
@jimcurtis
