### ISSUE TITLE
Spring getting started tutorial wrong Spring Boot Version

### ISSUE THREAD

**Issue by AFrappeM** [openshift-labs/learn-katacoda#370]
Hello

I'm learning OpenShift with Spring  Boot and I realized that the code in the examples is written for Spring Boot 2, and the pom.xml uses Spring Boot 1.5

After reading some other guide, I guessed what to change to make the tutorial work.

Here:
[pom.xml.zip](https://github.com/openshift-labs/learn-katacoda/files/2918292/pom.xml.zip)

https://learn.openshift.com/middleware/courses/middleware-spring-boot/spring-getting-started

**Comment by marekjelen** [comment]
@jamesfalkner

**Comment by jamesfalkner** [comment]
Spring boot version was updated:

```xml
    <spring-boot.version>2.1.2.RELEASE</spring-boot.version>
```

in https://github.com/openshift-labs/learn-katacoda/commit/6333ec48ae315209c08dea0defba31ebfb8573f8
