### ISSUE TITLE
Spring Boot Getting Started step 5

### ISSUE THREAD

**Issue by AFrappeM** [openshift-labs/learn-katacoda#371]
At https://learn.openshift.com/middleware/courses/middleware-spring-boot/spring-getting-started

In step 5, running the command: 
`mvn package fabric8:deploy -Popenshift -DskipTests`

I got:
```
[INFO] F8: Waiting for build fruits-s2i-2 to complete...
[INFO] F8: pulling image error : open /etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt: nosuch file or directory
[INFO] F8: error: build error: unable to get registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.3
```

It seems like https://github.com/minishift/minishift-centos-iso/issues/235

**Comment by marekjelen** [comment]
@jamesfalkner

**Comment by jamesfalkner** [comment]
This should be resolved, just tried it and it works well. There is a lot of magic happening under the hood to execute scripts like https://github.com/openshift-labs/learn-katacoda/blob/master/middleware/middleware-spring-boot/spring-getting-started/env-init.sh where the workaround is employed.
