### ISSUE TITLE
Two Upcoming Workshops for Operator-Framework Modules - Scale Conference and OpenShift Commons

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#372]
Red Hat will be running two Operator-Framework workshops:

Scale Conference, Pasadena, CA; Thursday, March 7th, 12pm to 6:00pm PT = 50 to 100 attendees.
OpenShift Commons, Santa Clara, CA; Monday, March 11th, 12pm to 6:00pm PT = 50 to 100 attendees.

Thanks!

@BenHall @mhausenblas @jmckind

**Comment by mhausenblas** [comment]
Thanks @madorn. I've handed over my responsibilities concerning Katacoda from our end to @marekjelen so, going forward, please tag him where so far you'd have tagged me ;)

All the best with the workshops!

**Comment by BenHall** [comment]
These have been scheduled.
