### ISSUE TITLE
Openshift Spring MVC scenario dependency error

### ISSUE THREAD

**Issue by AFrappeM** [openshift-labs/learn-katacoda#388]
Hello.

Following the Spring MVC scenario, the code does not run.

Looking in depth I removed the version tag of     
<dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-thymeleaf</artifactId>
</dependency>

And it works!

Please fix it up

**Comment by jankleinert** [comment]
Cannot reproduce this. Please reopen if it persists.
