### ISSUE TITLE
Compile error in Spring Boot Rest API learning module

### ISSUE THREAD

**Issue by shinta4ever** [openshift-labs/learn-katacoda#389]
ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /root/projects/rhoar-getting-started/spring/spring-rest-services/src/main/java/com/example/service/FruitController.java:[21,30] method findOne in interface org.springframework.data.repository.query.QueryByExampleExecutor<T> cannot be applied to given types;
  required: org.springframework.data.domain.Example<S>
  found: java.lang.Long
  reason: cannot infer type-variable(s) S
    (argument mismatch; java.lang.Long cannot be converted to org.springframework.data.domain.Example<S>)

**Comment by willowmck** [comment]
Use findById(id).get()

**Comment by jankleinert** [comment]
Cannot reproduce this issue.
