### ISSUE TITLE
can't open yaml in the editor (Simple Routing scenario)

### ISSUE THREAD

**Issue by biloussi** [openshift-labs/learn-katacoda#395]
In the "Istio 1.0.x workshop: Simple Routing" scenario yaml files do not open in editor. When link is clicked, editor creates new tab but then closes it immediately. This happens on Steps 2, 3 and 5.

I went through the scenario twice to check this. Browsers: Chrome 73.0.3683.86, Firefox 60.3.0esr (32-bit).

**Comment by btannous** [comment]
Closing, i believe these are fixed. please let me know if not.
