### ISSUE TITLE
Operator Framework Workshop - 4/1/2019 - 8am to 5pm Central Time

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#399]
Sorry for Late Notice - we have an Operator Framework Workshop scheduled for tomorrow and Wednesday, 4/2 and 4/3 - 8am to 5pm Central Time. 

Thank you!

**Comment by BenHall** [comment]
How many people?

**Comment by madorn** [comment]
25 attendees.

**Comment by madorn** [comment]
Just a note that we also want to include the new Operator SDK with Helm module on the workshop launch page. Thank you!

**Comment by BenHall** [comment]
Ready.
