### ISSUE TITLE
unable to authenticate fuse hello world tutorial

### ISSUE THREAD

**Issue by jazzdup** [openshift-labs/learn-katacoda#403]
https://learn.openshift.com/middleware/fuse-hello-world/?extIdCarryOver=true&sc_cid=701f2000001OH7EAAW

tried twice but auth failure also 2nd time with new url & token values e.g.
`-Dkubernetes.master=https://2886795343-8443-simba02.environments.katacoda.com/
-Dkubernetes.namespace=fuselab
-Dkubernetes.auth.token={{Vcye_JnjdwLnu5K4-AMJT7gXPD_MCCU9bFdCmBYe3KI}}
-Dfabric8.mode=openshift
-Dkubernetes.trust.certificates=true
-Dfabric8.build.strategy=s2i
-Dkubernetes.auth.tryServiceAccount=false
-Dfabric8.generator.from=registry.access.redhat.com/fuse7/fuse-java-openshift
-Dfabric8.generator.fromMode=docker
-Dkubernetes.auth.tryKubeConfig=false`

ERROR] Failed to execute goal org.jboss.redhat-fuse:fabric8-maven-plugin:7.2.0.fuse-720020-redhat-00001:build (default) on project camel-ose-springboot-xml: Failed to execute the build: Unable to build the image using the OpenShift build service: Failure executing: GET at: https://2886795343-8443-simba02.environments.katacoda.com/apis/build.openshift.io/v1/namespaces/fuselab/buildconfigs/camel-ose-springboot-xml-s2i. Message: Unauthorized
[ERROR] .
[ERROR] -> [Help 1]

**Comment by jankleinert** [comment]
Closing as this is >1 year old. Please open a new issue if this still persists.
