### ISSUE TITLE
SpringBoot Restful API scenario failing

### ISSUE THREAD

**Issue by rafaeltuelho** [openshift-labs/learn-katacoda#409]
The step "Step 2 Create REST services for the fruit web application" is failing due a compilation error after adding the "GET Mappings"

```java
        @GetMapping("/{id}")
        public Fruit getFruit(@PathVariable("id") Long id) {
            return repository.findOne(id);
        }
```

maven error output:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project rhoar-training: Compilation failure
[ERROR] /root/projects/rhoar-getting-started/spring/spring-rest-services/src/main/java/com/example/service/FruitController.java:[21,26] method findOne in interface org.springframework.data.repository.query.QueryByExampleExecutor<T> cannot be applied to given types;
[ERROR] required: org.springframework.data.domain.Example<S>
[ERROR] found: java.lang.Integer
[ERROR] reason: cannot infer type-variable(s) S
[ERROR] (argument mismatch; java.lang.Integer cannot be converted to org.springframework.data.domain.Example<S>)
[ERROR] -> [Help 1]
```

**Comment by rafaeltuelho** [comment]
It appears this issue is related to this: https://stackoverflow.com/questions/49316751/spring-data-jpa-findone-change-to-optional-how-to-use-this/49317013

So, my workaround was:

```java
    @GetMapping("/{id}")
    public Fruit getFruit(@PathVariable("id") Long id) {
        Fruit f = new Fruit();
        f.setId(id);
        Example<Fruit> e = Example.of(f); 
        return repository.findOne(e).get();
    }
```

**Comment by willowmck** [comment]
It appears that the code should use the method getOne(id) rather than findOne(id) as the JpaRepository does not define findOne(id).

See https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/JpaRepository.html

**Comment by willowmck** [comment]
> It appears that the code should use the method getOne(id) rather than findOne(id) as the JpaRepository does not define findOne(id).
> 
> See https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/JpaRepository.html

Actually, looking into this further, rafaeltuelho is correct.  You need a get() after findOne().

**Comment by jankleinert** [comment]
Can no longer reproduce this issue.
