### ISSUE TITLE
Suggestion: Spring boot init should point to snowdrop.me

### ISSUE THREAD

**Issue by alberttwong** [openshift-labs/learn-katacoda#413]
In step 1 of https://learn.openshift.com/middleware/courses/middleware-spring-boot/spring-getting-started, it points to Spring Initializr.     In the lab, it uses snowdrop.   Instead of pointing to Spring Initializr, shouldn't it point to snowdrop.me?

**Comment by BenHall** [comment]
Thanks for the feedback. I believe this was implemented a while ago
