### ISSUE TITLE
Problem with tutorial on RedHat Openshift Learning: Developing with odo

### ISSUE THREAD

**Issue by ModernCrusaders** [openshift-labs/learn-katacoda#423]
Hi, I've got some issues while trying to follow this tutorial on Openshift Learning

I run this:

$ odo create java backend --binary target/wildwest-1.0.jar

I get this:

x checking component
ERR invalid component type: java
Run 'odo catalogo list components' for a list of supported component types

I run that code, and I noticed there is no java as an available component. There is nodejs, though. What should I do to continue the tutorial?

**Comment by BenHall** [comment]
This tutorial was recently updated and appears to be working as expected.

If you still encounter problems, please let me know.
