### ISSUE TITLE
Environment expiration

### ISSUE THREAD

**Issue by jesusmah** [openshift-labs/learn-katacoda#424]
The environment I was using for the course: `Getting Started with Spring` expired before I finished the course. I understand there must be a time out for recycling environments. However, if someone like me needs more time between steps (as there is a lot of Java/Spring code I really wanted to understand such as the Spring/Spring Boot annotations) will not have enough time to finish.

Having to re-start the course is not desirable.

Thank you.

PS: I would suggest using a longer timeout and reset that time out when the user interacts with the environment. Since I started the course I took long time to understand it in detail but I didn't took long time between interactions which means I was following the course (but a slower pace).

**Comment by BenHall** [comment]
Thanks for the feedback. We are always looking at ways to improve the Katacoda and how we can address this. We've added some changes and will continue to look at how we can support all learning styles.
