### ISSUE TITLE
403 (FORBIDDEN) when trying to reach microsservice

### ISSUE THREAD

**Issue by herbae** [openshift-labs/learn-katacoda#427]
I followed the instructions of the Istio workshop -> Deploy microservices scenario. On step 3, I get a 403 error when trying to curl the recently created service.

`curl http://customer-tutorial.2886795293-80-frugo02.environments.katacoda.com`

**Comment by BenHall** [comment]
Hi @herbae 

Sorry, we were attempting to fix an issue with our Europe region and locked down the cluster too much. This has been resolved.
