### ISSUE TITLE
ansible refresher ssh permission denied

### ISSUE THREAD

**Issue by mhrivnak** [openshift-labs/learn-katacoda#428]
The [ansible refresher exercise](https://learn.openshift.com/ansibleop/ansible-refresher/) is failing on the first page because it can't ssh to `host01`.

```
$ ansible all -i myhosts -m ping
host01 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n",    
    "unreachable": true
}
```

It appears that `/home/cent/.ssh/id_rsa.pub` does not exist:

```
$ ls -l /home/cent/.ssh/
total 8
-rw-r--r--. 1 root root  745 Nov 19  2017 authorized_keys
-rw-------. 1 root root 1675 May  2 02:45 id_rsa
```

Which causes [this setup line](https://github.com/openshift-labs/learn-katacoda/blob/7e56521/ansibleop/ansible-refresher/env-init.sh#L4) to not do anything. Thus, the [generated ssh key](https://github.com/openshift-labs/learn-katacoda/blob/7e56521/ansibleop/ansible-refresher/env-init.sh#L2) is not valid for authenticating as user `cent`.

I'm not sure why `/home/cent/.ssh/id_rsa.pub` doesn't exist. It does exist in `/root/.ssh/`, and it appears that it [should have been copied](https://github.com/openshift-labs/learn-katacoda/blob/7e56521/ansibleop/ansible-refresher/env-init.sh#L3).

**Comment by kaovilai** [comment]
@jorgemoralespou

**Comment by jorgemoralespou** [comment]
@kaovilai I'm not the maintainer of this specific lab but rather @mhrivnak and his team

**Comment by kaovilai** [comment]
@jorgemoralespou oops. How do I know who maintain what?

**Comment by jorgemoralespou** [comment]
By looking at who contributed it, or by asking. I don't know all of them
myself, but that's how I would do.
