### ISSUE TITLE
Add citrus tutorial to homepage?

### ISSUE THREAD

**Issue by ZNicoZ** [openshift-labs/learn-katacoda#434]
Hi there,

we created the citrus tutorial [here](https://github.com/openshift-labs/learn-katacoda/tree/master/external), it can be started with this [deeplink](https://learn.openshift.com/external/courses/citrus/intro/)
By now, the tutorial is not shown on learn.openshift but should be integrated into a new "box" called external (or something like that).

What do we need to do / how do we need to adapt the JSON pathway file to accomplish this?

Kind regards
Nico

**Comment by BenHall** [comment]
This is a question for @jorgemoralespou

**Comment by ZNicoZ** [comment]
Hi @jorgemoralespou, any update about this?

**Comment by jdob** [comment]
Closing this out due to inactivity. If you still wish to contribute this, please update the scenario to the 4.7 image or later and open a PR to where you think it should be added.
