### ISSUE TITLE
x509 certificate signed by unknown authority

### ISSUE THREAD

**Issue by ZNicoZ** [openshift-labs/learn-katacoda#435]
Hi,

we are using openshift-3-11 image for the citrus [tutorial](https://github.com/openshift-labs/learn-katacoda/tree/master/external) tutorial.

Trying to login using 
`oc login -u developer -p developer{{execute}}`

throws the following error:
`$ oc login -u developer -p developer
error: x509: certificate signed by unknown authority`

What should we do?

Kind regards
Nico

**Comment by BenHall** [comment]
``oc login -u developer -p developer  [[HOST_SUBDOMAIN]]-8443-[[KATACODA_HOST]].environments.katacoda.com``{{execute}}

Use the playground as an example - https://github.com/openshift-labs/learn-katacoda/blob/master/playgrounds/openshift311/tips.md

**Comment by ZNicoZ** [comment]
Thanks, we´ll try - our approach worked in the past btw :)

**Comment by BenHall** [comment]
It worked with 3.6/3.7 but not with 3.10 or 3.11
