### ISSUE TITLE
Underlying HTML changes on every page refresh

### ISSUE THREAD

**Issue by wgordon17** [openshift-labs/learn-katacoda#448]
Loading https://learn.openshift.com will load 1 HTML page, and refreshing it will cause different HTML pages to load, specifically the assets called in the `<head>` tag. 

The correct assets should be what's provided in https://github.com/openshift-labs/learn-katacoda/blob/master/branded-ui/katacoda/templates/header.html.

Additionally, the text in the squares are being loaded with "Open Sans". Are we able to update this text to use "RedHatText"? The "RedHatText" `font-family` is defined in https://assets.openshift.net/content/subdomain.css

**Comment by wgordon17** [comment]
@BenHall are you able to review this?

**Comment by BenHall** [comment]
Thanks @wgordon17 I'm not able to reproduce this. Could you send me a screenshot of the two versions you are seeing please?

**Comment by wgordon17** [comment]
@BenHall Well, looks like it's been resolved. Weird, I was able to induce it just yesterday! Oh well 🤷‍♂ 

Are you able to help at all with the font family that's loaded within the Katacoda iframe?

**Comment by BenHall** [comment]
@wgordon17 I added a custom CSS which should be applying the font now.

**Comment by wgordon17** [comment]
Wonderful! Ty sir 👍
