### ISSUE TITLE
Can not open dashboard

### ISSUE THREAD

**Issue by SharpRazor** [openshift-labs/learn-katacoda#450]
<img width="1623" alt="Screen Shot 2019-05-17 at 11 07 59 AM" src="https://user-images.githubusercontent.com/25785609/57900669-5ea6e680-7894-11e9-8bc6-679735dd2e2a.png">

Just as the picture shows, I can not open my dashboard and I also tried "view HTTP port 8443 on Host 1". Both of them are not working. 

My browser is Chrome and I also tried Firefox, not working too.

So the problem is the OS? or something else?

**Comment by SharpRazor** [comment]
<img width="1352" alt="Screen Shot 2019-05-17 at 11 26 45 AM" src="https://user-images.githubusercontent.com/25785609/57901231-c100e680-7896-11e9-83fb-791cb65ea6b8.png">

Another picture for your reference.

**Comment by BenHall** [comment]
Thanks for the information. It looks to be working at the moment but we'll check the logs and see if there was any networking issues.

Could you please tell us which region you are in so we can see if it's a geo-located related issue?

**Comment by SharpRazor** [comment]
> Thanks for the information. It looks to be working at the moment but we'll check the logs and see if there was any networking issues.
> 
> Could you please tell us which region you are in so we can see if it's a geo-located related issue?

Hi sorry for the late response, my location is Beijing, China.

**Comment by barata0** [comment]
Just happened to me. (BAD GATEWAY)
![Capture](https://user-images.githubusercontent.com/461378/61175784-91ffac00-a58b-11e9-86a5-811286e6e27e.PNG)

Some dashboards open and some don't.
The lesson "Deploying Applications from Images" is not working.
The previous lesson worked fine.

This happened on My Android phone and on my windows 10 laptop (both using crhome). I'm in Brazil

**Comment by dread-uo** [comment]
I'm having some issues too. I'm trying this using Firefox, while in Brazil.
![image](https://user-images.githubusercontent.com/7685154/64139013-d104ed80-cdd5-11e9-95d7-916d440d8e9a.png)
When I click to refresh the dashboard, the following error shows up on the console:
```
The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.
```

**Comment by BenHall** [comment]
We are sorry for the issues related to loading of the dashboard.

We've made various changes that will hopefully fix the issues related to the 502 error.

In terms of accessing the platform from China. We are still investigating how we can make this possible. Part of the Katacoda infrastructure is running on top of Google Cloud, meaning it can sometimes be blocked. 

If anyone continues to have issues, please let me know.
