### ISSUE TITLE
Introduction - Developing with Odo

### ISSUE THREAD

**Issue by mashiro-paradeis** [openshift-labs/learn-katacoda#457]
I have an error while running the instruction 'odo login -u developer -p developer'
The output should be 'Login successful.

You have one project on this server: "default"

Using project "default".'
But what I get is 'x509: certificate signed by unknown authority'

**Comment by danielhelfand** [comment]
@mashiro-paradeis I think there were issues earlier in the week with katacoda properly setting up the environment for the tutorial. I believe it should be working now and sorry for any inconvenience. Feel free to open this issue again if you experience something similar.
