### ISSUE TITLE
Introduction - Deploying Applications From Source

### ISSUE THREAD

**Issue by mashiro-paradeis** [openshift-labs/learn-katacoda#458]
I think there's a kind of issue in this tutorial too. In the step "You should be presented with the catalog browser." in the section myproject -> Add to project, I am not presented to any catalog browser. Even today in the morning there were options displayed in this part of the tutorial, but now there's an error. I hope you can help me because I find these turorials very useful.
![justagirl](https://user-images.githubusercontent.com/48811979/58055976-1e11cc00-7b25-11e9-8923-20a742ddb115.png)

**Comment by danielhelfand** [comment]
This has been resolved and the tutorial is behaving as expected now. Closing this for now, but it's likely that the site experienced issues with exceeding user capacity.
