### ISSUE TITLE
kubefedctl: command not found (https://learn.openshift.com/introduction/federated-clusters/)

### ISSUE THREAD

**Issue by nebijju** [openshift-labs/learn-katacoda#462]
https://learn.openshift.com/introduction/federated-clusters/ 
Experienced issue with executing the command for kubefedctl version
URL: https://learn.openshift.com/introduction/federated-clusters/

<img width="1516" alt="Screen Shot 2019-05-22 at 7 11 04 PM" src="https://user-images.githubusercontent.com/49096638/58214894-7f70a100-7cc5-11e9-9b17-b10dc1f68c4b.png">

**Comment by BenHall** [comment]
Thanks. @mvazquezc Could you investigate. How does the binary get deployed/installed?

**Comment by mvazquezc** [comment]
The binary is download directly from the source repository and place it in /usr/local/bin.

```curl -LOs https://github.com/kubernetes-sigs/kubefed/releases/download/v0.0.10/kubefedctl.tgz```

I just tried the scenario and it worked fine, maybe it failed to download because of network issues or something, I'm going to code a retry logic and will send a PR.

**Comment by BenHall** [comment]
Thanks for checking. Github is sometimes super slow to download from. 

Could you raise a PR that extends the environment (https://github.com/openshift-labs/learn-katacoda/tree/master/environments/openshift-3-11/scripts) to include the binary by default? Add a script called `13_kubefed.sh` and it will be picked up. If you need anything else, this is a good place to include it,

**Comment by mvazquezc** [comment]
> https://github.com/openshift-labs/learn-katacoda/tree/master/environments/openshift-3-11/scripts

Hi Ben,

The PR is ready: https://github.com/openshift-labs/learn-katacoda/pull/463

Thanks,

**Comment by nebijju** [comment]
Thank you for your fast action to resolve the issue.

Have a great day!

Best,
Balaram Tidhi

On May 23, 2019, at 3:42 AM, Ben Hall <notifications@github.com> wrote:

Thanks for checking. Github is sometimes super slow to download from.

Could you raise a PR that extends the environment (https://github.com/openshift-labs/learn-katacoda/tree/master/environments/openshift-3-11/scripts) to include the binary by default? Add a script called 13_kubefed.sh and it will be picked up. If you need anything else, this is a good place to include it,
