### ISSUE TITLE
site is unencrypted

### ISSUE THREAD

**Issue by jijodv** [openshift-labs/learn-katacoda#464]
learn.openshift.com site is unencrypted. It would be too good if at least lets encrypt is used for https connection.

**Comment by GrahamDumpleton** [comment]
It is encrypted when access https://learn.openshift.com. Looks like it just lacks a redirect from http to https. If you click on any scenarios you are then directed to https version.

**Comment by jijodv** [comment]
> It is encrypted when access https://learn.openshift.com. Looks like it just lacks a redirect from http to https. If you click on any scenarios you are then directed to https version.
Thanks Graham! Yes, just saw that its only the redirection that's needed.

**Comment by BenHall** [comment]
Thanks for highlighting this. We recently moved to GCPLB so it was
geo-located but that doesn't automatically redirect http requests.  We'll
get this patched

**Comment by jijodv** [comment]
Thanks Ben!
