### ISSUE TITLE
Missing or incomplete configuration info - /operatorframework

### ISSUE THREAD

**Issue by kaovilai** [openshift-labs/learn-katacoda#468]
Tested on

- https://learn.openshift.com/operatorframework/k8s-api-fundamentals/
- https://learn.openshift.com/operatorframework/go-operator-podset/

This is the output from the terminal when performing `oc status` after initialization.

```
cd ~/tutorial
$
$ cd ~/tutorial
$ oc status
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.
$
```

This issue wasn't present when I was doing this workshop yesterday.

**Comment by kaovilai** [comment]
Trying to open dashboard results in HTTP 503.

**Comment by kaovilai** [comment]
Update, opening dashboard  now gets me error 502.

I assume the issue is from the server not responding and not necessarily the script itself since it did work before.

**Comment by BenHall** [comment]
Thanks. This happens when OpenShift is still starting.

We'll get the scenarios updated to provide the user with some additional context.

**Comment by kaovilai** [comment]
resolved

**Comment by BenHall** [comment]
We've made changes that ensure users are always connected to a running environment, or displayed a message saying why. This should make the environments consistent.
