### ISSUE TITLE
Error using 

### ISSUE THREAD

**Issue by gearoidibm** [openshift-labs/learn-katacoda#469]
Using Firefox with https://learn.openshift.com/operatorframework/helm-operator/
Get the following error at step 1.
```
$ oc new-project myproject
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.
$
```

**Comment by kaovilai** [comment]
See #468 
For my case it took a 5 min wait but eventually the command will work. Just wait a bit.

**Comment by BenHall** [comment]
We've made changes that ensure users are always connected to a running environment, or displayed a message saying why. This should make the environments consistent.
