### ISSUE TITLE
There is no "java" component which caused a failure with "odo create java backend"

### ISSUE THREAD

**Issue by kenuenoibm** [openshift-labs/learn-katacoda#473]
$ odo catalog list components
NAME        PROJECT       TAGS
dotnet      openshift     2.0,latest
httpd       openshift     2.4,latest
nginx       openshift     1.10,1.12,1.8,latest
nodejs      openshift     0.10,10,4,6,8,8-RHOAR,latest
perl        openshift     5.16,5.20,5.24,5.26,latest
php         openshift     5.5,5.6,7.0,7.1,latest
python      openshift     2.7,3.3,3.4,3.5,3.6,latest
ruby        openshift     2.0,2.2,2.3,2.4,2.5,latest
wildfly     openshift     10.0,10.1,11.0,12.0,13.0,8.1,9.0,latest
$

**Comment by danielhelfand** [comment]
@kenuenoibm Hi, the issue you are seeing is related to the environment not being loaded properly. This has been raised as an [issue](https://github.com/openshift-labs/learn-katacoda/issues/461) and there is a temporary workaround included in the issue. Apologies for the inconvenience in using `Developing with odo` tutorial. We're working on how to address issues with properly loading environments for the tutorials.

**Comment by kenuenoibm** [comment]
@danielhelfand 
Hi.  I took a look at the issue #461 and ran the command which was mentioned.
Then, I got the following error message.  Could you please help me on it?

$ curl -kL https://gist.github.com/jorgemoralespou/033c27a354406d7c5111711346e79b01/raw 2> /dev/null | oc apply -n openshift --as system:admin -f -
error: unable to recognize "STDIN": no matches for kind "ImageStream" in version "image.openshift.io/v1"
$

**Comment by danielhelfand** [comment]
I'm unfamiliar with the specifics of the error you're receiving and unfortunately can't reproduce it, but I believe that the troubles you are experiencing with the tutorial at this moment could also be related to a new release of the tutorial that has been put out. 

It may take the tutorial awhile to refresh after it has been redeployed. For instance, if you reload the tutorial at this moment, you may see different versions of `odo` are installed. I will keep an eye on that state of it and get back to you on when it appears to be ready again.

**Comment by kenuenoibm** [comment]
@danielhelfand 
Hello.
I just created a new environment and it had Java in it.  So, I will use a new environment to move forward.
