### ISSUE TITLE
error: only a partial match was found for "kubernetes/guestbook"

### ISSUE THREAD

**Issue by kenuenoibm** [openshift-labs/learn-katacoda#479]
Hello.

I am working on the scenario "Using OpenShift metrics" and having an issue at Step 2 of 5.
Could you please take a look at the error message below and let me know how to solve it?

$ oc new-app kubernetes/guestbook
error: Errors occurred while determining argument types:

kubernetes/guestbook as a local directory pointing to a Git repository:  stat kubernetes/guestbook: no such file or directory

Errors occurred during resource creation:
error: only a partial match was found for "kubernetes/guestbook": "docker.io/kubernetes/guestbook:latest"

The argument "kubernetes/guestbook" only partially matched the following Docker image, OpenShift image stream, or template:

* Docker image "docker.io/kubernetes/guestbook:latest", 7dc61f8, from local, 11.827mb
  Use --docker-image="docker.io/kubernetes/guestbook:latest" to specify this image or template

$

**Comment by malcolmm83** [comment]
I changed to unwornmoon/guestbook and that worked fine.  I don't understand the previous comment.    I did manage to figure out how to run the cached image, but you should modify the instructions to include that.
