### ISSUE TITLE
HTTP requests should be redirected to HTTPS

### ISSUE THREAD

**Issue by ebosnic** [openshift-labs/learn-katacoda#482]
hi there... I believe there is no 301 redirect on learn.openshift.com , but im a just a n00b, maybe it should be like that... I just feel it like lets report it... 

https://www.whynopadlock.com/results/ff404236-7236-44be-9c53-5f82f012fabe

**Comment by BenHall** [comment]
Thanks. This was due to a recent load balancer change. If a user visits the homepage on HTTP then they'll be moved to HTTPS when they load a scenario, but we should force HTTPS.
