### ISSUE TITLE
Operator Workshop - Amsterdam

### ISSUE THREAD

**Issue by mhrivnak** [openshift-labs/learn-katacoda#484]
There will be an operator workshop June 6-7, 9am-6pm both days, local time in Amsterdam with 15 attendees.

We especially need both of these scenarios in addition to the usual operator scenarios:
* Ansible Kubernetes Modules
* Ansible Operator Overview

Thanks!

**Comment by mhrivnak** [comment]
@BenHall

**Comment by BenHall** [comment]
This has been setup
