### ISSUE TITLE
Operator SDK with Go

### ISSUE THREAD

**Issue by nebijju** [openshift-labs/learn-katacoda#487]
Error when adding a new Custom Resource Definition(CRD) API called PodSet, with APIVersion 

operator-sdk add api --api-version=app.example.com/v1alpha1 --kind=PodSet

![Screen Shot 2019-06-03 at 4 48 49 PM](https://user-images.githubusercontent.com/49096638/58834007-45d25b00-8620-11e9-892a-0e28ee59bd75.png)

**Comment by madorn** [comment]
Hi @nebijju,

I don't see an error in your uploaded screenshot. I was able to run `operator-sdk add api --api-version=app.example.com/v1alpha1 --kind=PodSet` successfully.

What error are you seeing?

![Screen Shot 2019-06-03 at 7 17 52 PM](https://user-images.githubusercontent.com/4207880/58842533-60163400-8634-11e9-9183-c7afcad3c53b.png)

**Comment by nebijju** [comment]
Attached is the Screen Shot. It happened multiple times for me

**Comment by madorn** [comment]
@nebijju I don't see a screenshot attached to your last message.

Can you write out the error you see?

**Comment by madorn** [comment]
@nebijju checking in to see if you could report the error. thanks.

**Comment by madorn** [comment]
Please close @BenHall
