### ISSUE TITLE
https://learn.openshift.com/introduction/getting-started/

### ISSUE THREAD

**Issue by dtaylor113** [openshift-labs/learn-katacoda#489]
Command Line and Console do not seem to be working.

"We are sorry but we encountered a problem with the connection.
Please refresh and try again.
Tue Jun 04 2019 10:41:55 GMT-0400 (Eastern Daylight Time)
transport close"

**Comment by danielhelfand** [comment]
This also occurred earlier with `Developing with odo` under introduction. I've run through `Getting Started with OpenShift for Developers` and didn't experience this, so it appears to be resolved at this moment.

**Comment by BenHall** [comment]
We've made a series of changes that should increase the connection reliability. Hopefully you should face this in future.
