### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by jpdade** [openshift-labs/learn-katacoda#495]
Would like to see how to have a container application (like .net core or java) connect to an external database like oracle or mysql. Is that possible?

**Comment by danielhelfand** [comment]
@jpdade We do have a couple tutorials with Spring Boot and PostgreSQL: 
• [Spring Data with JPA/Hibernate](https://learn.openshift.com/middleware/courses/middleware-spring-boot/spring-db-access)
• [Spring Rest](https://learn.openshift.com/middleware/courses/middleware-spring-boot/spring-rest-services)

Would these be helpful to you, or was there something else you were looking for? 

They are a little difficult to find, so apologies about that.

**Comment by danielhelfand** [comment]
Going to close this for now, but feel free to reopen.
