### ISSUE TITLE
Typo on https://learn.openshift.com/introduction/using-metrics/ step 2

### ISSUE THREAD

**Issue by steven1046** [openshift-labs/learn-katacoda#506]
It is **requied** to modify the deploymentconfig to force to use the cached image instead pulling it again:

should be required

**Comment by rbaumgar** [comment]
oc new-app does not work
$ oc new-app kubernetes/guestbook
error: Errors occurred while determining argument types:

kubernetes/guestbook as a local directory pointing to a Git repository:  stat kubernetes/guestbook: no such file or directory

Errors occurred during resource creation:
error: only a partial match was found for "kubernetes/guestbook": "docker.io/kubernetes/guestbook:latest"

The argument "kubernetes/guestbook" only partially matched the following Docker image, OpenShift image stream, or template:

* Docker image "docker.io/kubernetes/guestbook:latest", 7dc61f8, from local, 11.827mb
  Use --docker-image="docker.io/kubernetes/guestbook:latest" to specify this image or template

kubernetes/guestbook image is not available!

**Comment by Guarrdon** [comment]
You recommended image @rbaumgar worked for me.  Thanks!

**Comment by rbaumgar** [comment]
@Guarrdon it still doesn't work

**Comment by Guarrdon** [comment]
Using the fully qualified image you specified (docker.io/kubernetes/guestbook:latest), I was able to run the activity and see the metrics (cpu/mem/...).
I was not able to see it following the built in instructions using kubernetes/guestbook (as you describe).

I'll double check, but I believe the only way I would have seen those metrics is if I had used a valid image.

**Comment by BenHall** [comment]
Thanks for the feedback. We've made some changes to make this more straightforward and remove the error.
