### ISSUE TITLE
Getting Started with OpenShift for Developers step 2 console does not open

### ISSUE THREAD

**Issue by vrvignesh** [openshift-labs/learn-katacoda#511]
Getting Started with OpenShift for Developers step 2 console does not open . I tried opening the url https://2886795335-8443-cykoria05.environments.katacoda.com/ in the different tab  but the same result

**Comment by BenHall** [comment]
Sorry about this @vrvignesh. Does it display an error?

**Comment by vrvignesh** [comment]
In Firefox just white blank screen but in chrome I get HTTP 502 error

**Comment by danielhelfand** [comment]
@vrvignesh To clarify, this is for the OpenShift Web Console on `Step 2 - Exploring The Web Console`, correct?

**Comment by vrvignesh** [comment]
Yes

**Comment by danielhelfand** [comment]
I can't reproduce this at this time. I am able to go through the tutorial as expected, but I too have experienced this with the web console from time to time. Not sure if this is related to capacity or something else.

**Comment by BenHall** [comment]
I also can't reproduce it, but will investigate more about why the console sometimes is dropping and not rendering correctly.

**Comment by vrvignesh** [comment]
Now console is loading

**Comment by BenHall** [comment]
@vrvignesh That's great to hear. We will check the logs and see what happened in the meantime. 

Thanks for letting us know and getting in touch. If you need anything else, please let us know.
