### ISSUE TITLE
Error while starting session

### ISSUE THREAD

**Issue by ravishgithub** [openshift-labs/learn-katacoda#518]
Sorry, we encountered a problem. Support has been alerted.
This is potentially due to a HTTP Proxy blocking Websockets.
Websocket Error - Connection Failed. Reload the page to try again.

**Comment by ravishgithub** [comment]
i get this on Getting Started with OpenShift for Developers

**Comment by BenHall** [comment]
Sorry you hit an error. This occurs when an internal firewall or VPN is blocking websocket connections.

**Comment by ravishgithub** [comment]
It's very old ticket and how do I check what issue it was? I don't see old log reference

**Comment by BenHall** [comment]
@ravishgithub When you access https://learn.openshift.com/playgrounds/openshift36/ are you still having the same error?
