### ISSUE TITLE
A way to get people to load prereqs without starting a scenario

### ISSUE THREAD

**Issue by thesteve0** [openshift-labs/learn-katacoda#52]
We are about to write and launch some scenarios that require some pre-requisites on the users machine. We don't want to "waste" the hour we are given waiting for the user to install the necessary pieces (like JBoss Developer Studio). 
We would like to find some way to indicate to the user BEFORE they start the scenario that they should go do some steps. We were thinking something on the homepage, maybe a mouseover or some additional text next to a scenario... but those are just ideas. 

The solution does not need to be fancy, just clear and before they actually start the scenario. Can we try to figure out and implement a solution soon.

Let's try to brainstorm the layout here

@GrahamDumpleton @mhausenblas @BenHall

**Comment by BenHall** [comment]
The branded UI should be able to cope with this. It's a hugo static site (https://github.com/gohugoio/hugo) so additional content can be added around where Katacoda is embedded.

I put together an example of having headings and multiple dashboards embedded into a single page. This could also include the required pre-requisites.

https://learn.openshift.com/category-example/

The underlying page is in the repo @ https://github.com/openshift-evangelists/intro-katacoda/blob/master/branded-ui/katacoda/layouts/indexes/category-example.html

Another approach is that Katacoda could host JBoss Developer Studio directly...

**Comment by mhausenblas** [comment]
Seems stale, please re-open if it persists.
