### ISSUE TITLE
learn.openshift.com doesn't work anymore

### ISSUE THREAD

**Issue by eldomar** [openshift-labs/learn-katacoda#526]
Hi,
trying to access the labs from learn.openshift.com. but the tiles aren't showing up. there seem to be a problem with the site scripts.

**Comment by ryanj** [comment]
What browser and OS are you using? Any error reports available in the console?

**Comment by ryanj** [comment]
Possible duplicate: https://github.com/openshift-labs/learn-katacoda/issues/523

**Comment by BenHall** [comment]
We believe we have finally resolved the root cause. Please check and try
again.

**Comment by stephan-volz** [comment]
Works for me now (tested with Chrome on Linux).

**Comment by eldomar** [comment]
Yes, now it works. Thanks.
