### ISSUE TITLE
SSE connections to running apps fails to connect

### ISSUE THREAD

**Issue by jamesfalkner** [openshift-labs/learn-katacoda#530]
Server-sent events appear to not work properly. Here's an easy way to reproduce on any of the OpenShift scenarios:

```sh
oc new-project foo
oc new-app --name=sse nodejs~https://github.com/kljensen/node-sse-example
oc expose svc/sse
oc get routes
```
The example app is a simple page that opens up an SSE connection to `/events`. Opening the app using its exposed route renders a blank web page, and never shows the incoming streamed data as expected.

However, if you rsh into the running pod, and execute `curl -i http://localhost:8080/events` you can clearly see the SSE is working properly on the server side:

```console
sh-4.2$ curl -i http://localhost:8080/events
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/event-stream
Cache-Control: no-cache
Connection: keep-alive
Date: Tue, 13 Aug 2019 13:01:29 GMT
Transfer-Encoding: chunked


data: 0.5501102780793552

data: 0.8622476600428495

data: 0.8434024010707935
```
The 'data' is spit out every 2 seconds. But this never shows up in the browser page, and using the Developer Console you can see the SSE connection is failing to get established. I'm guessing some proxy setting is needed to allow this?

**Comment by BenHall** [comment]
The root cause relates to the proxy buffering the response. As it's such a small snippet, it takes a while to fill up the buffer.

When the pod is deleted, the connection is closed and the buffer is streamed to the client. 

Now we know the cause, we can get this fixed.

**Comment by BenHall** [comment]
This has now been deployed.

**Comment by garciapacho** [comment]
> This has now been deployed.

Hi @BenHall, 
Can you explain how you fix it? 
Thanks

**Comment by appiepollo14** [comment]
@BenHall I'm running into a similar issue on OC with SSE. I believe the stream is buffered as well in my case and not released until pod is deleted. Can you share with us the steps you took to fix this?

**Comment by dawid-sliwa** [comment]
@jamesfalkner @BenHall How did you end up fixing that?

**Comment by jamesfalkner** [comment]
I'll defer to @BenHall as he did the fix (and it was almost 4 years ago so you may need to be patient :) )

**Comment by dawid-sliwa** [comment]
@jamesfalkner sure thanks for the response i'm more than happy to kindly wait

**Comment by BenHall** [comment]
@dawid-sliwa Sadly I no longer have access to the repo so I can't fully remember the details. 

However, I assume it was nginx and `proxy_buffering` and `proxy_max_temp_file_size` of the proxy infront of Openshift than was disabled.

**Comment by dawid-sliwa** [comment]
@BenHall First of thanks for the answer, my problem is that openshift by default uses ha proxy as it's ingress do you remember by any chance if you swapped to nginx?

**Comment by BenHall** [comment]
@dawid-sliwa I don't believe we changed Openshift. We had a independent proxy in front of OpenShift too which was the issue. It was running outside the cluster.
