### ISSUE TITLE
console error, stopped working

### ISSUE THREAD

**Issue by dombrowa** [openshift-labs/learn-katacoda#534]
We are sorry but we encountered a problem with the connection.
Please refresh and try again.
Mon Aug 19 2019 15:34:12 GMT-0400 (Eastern Daylight Time)
transport close

2)
Extra Interactive Bash Terminal

We are sorry but we encountered a problem with the connection.
Please refresh and try again.
Mon Aug 19 2019 15:34:12 GMT-0400 (Eastern Daylight Time)
transport close

**Comment by dombrowa** [comment]
Google Chrome 75.0.3770.90  Linux i3770k 5.1.8-200.fc29.x86_64 #1 SMP Sun Jun 9 17:20:17 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by BenHall** [comment]
Sorry for the delay in responding. This happens when the connection between your local browser and Katacoda is broken. Did the Wifi drop?

**Comment by dombrowa** [comment]
I used a corporate wired network, no WiFi.
