### ISSUE TITLE
web console

### ISSUE THREAD

**Issue by dombrowa** [openshift-labs/learn-katacoda#535]
Loading the web console does not work (Waiting >10 min)

**Comment by dombrowa** [comment]
Google Chrome 75.0.3770.90  Linux i3770k 5.1.8-200.fc29.x86_64 #1 SMP Sun Jun 9 17:20:17 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by BenHall** [comment]
Could you please let us know which scenario you had an issue with? We've tried to reproduce but have been unable to.

If the problem continues, please let us know and re-open the issue.
