### ISSUE TITLE
password should be generated new per session

### ISSUE THREAD

**Issue by dombrowa** [openshift-labs/learn-katacoda#536]

**Comment by dombrowa** [comment]
Google detects:

Change your password
The Password Checkup extension detected that your password for 2886795280-8443-frugo02.environments.katacoda.com is no longer safe due to a data breach.

**Comment by dombrowa** [comment]
Google Chrome 75.0.3770.90  Linux i3770k 5.1.8-200.fc29.x86_64 #1 SMP Sun Jun 9 17:20:17 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by BenHall** [comment]
Thanks for the suggestion. We'll keep this in mind going forward
