### ISSUE TITLE
Missing functions in web console

### ISSUE THREAD

**Issue by dombrowa** [openshift-labs/learn-katacoda#537]
After logging in to the web console, you'll see a blue button labeled Create Project in the top right corner of your screen that is shown below. Click this button to get started.

The button for Create Project is not visible, I  assume it is covered with errors such as:
Unable to load all content for the catalog. Error loading templates.
￼ CloseerrorAn error occurred connecting to the server.
 Failed to list templates/template.openshift.io/v1 (status 403)
Refresh
Search Catalog￼
Browse Catalog
Deploy Image  Import YAML / JSON  Select from Project
All
Languages
Databases
Middleware
CI/CD
Other
￼Filter 
8 Items
amp-apicast-wildcard-router
amp-pvc
￼
Nginx HTTP server and a reverse proxy
￼
Nginx HTTP server and a reverse proxy (nginx)
￼
Redis
￼
Redis (Ephemeral)
registry-console
system
￼ Create Project
My Projects
1 of 1 Projects View All
￼
default
created 2 hours ago

Getting Started
￼ Take Home Page Tour
Documentation
Interactive Learning Portal
Local Development
YouTube
Blog

Unable to load all content for the catalog. Error loading templates.
￼ CloseerrorAn error occurred connecting to the server.
 Failed to list templates/template.openshift.io/v1 (status 403)
Refresh
Search Catalog￼
Browse Catalog
Deploy Image  Import YAML / JSON  Select from Project
All
Languages
Databases
Middleware
CI/CD
Other
￼Filter 
8 Items
amp-apicast-wildcard-router
amp-pvc
￼
Nginx HTTP server and a reverse proxy
￼
Nginx HTTP server and a reverse proxy (nginx)
￼
Redis
￼
Redis (Ephemeral)
registry-console
system
￼ Create Project
My Projects
1 of 1 Projects View All
￼
default
created 2 hours ago

Getting Started
￼ Take Home Page Tour
Documentation
Interactive Learning Portal
Local Development
YouTube
Blog

Reloading the page results in:

https://2886795280-8443-frugo02.environments.katacoda.com/console/catalog

**Comment by dombrowa** [comment]
Google Chrome 75.0.3770.90  Linux i3770k 5.1.8-200.fc29.x86_64 #1 SMP Sun Jun 9 17:20:17 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by BenHall** [comment]
I've tried to reproduce this since you raised the issue but been unable to. 

Could you have another attempt and see if you are see seeing the same error?
