### ISSUE TITLE
filter does not return results when searching for my userid

### ISSUE THREAD

**Issue by dombrowa** [openshift-labs/learn-katacoda#538]
see title

**Comment by dombrowa** [comment]
Issues -> Filter -> userid -> 0 results

**Comment by dombrowa** [comment]
Google Chrome 75.0.3770.90  Linux i3770k 5.1.8-200.fc29.x86_64 #1 SMP Sun Jun 9 17:20:17 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by BenHall** [comment]
I believe you are referring to the Github issues filter?

If so, the search should be `is:open is:issue author:dombrowa`

**Comment by BenHall** [comment]
This is how GitHub works and not within our control.
