### ISSUE TITLE
Developing with odo : command fails

### ISSUE THREAD

**Issue by dombrowa** [openshift-labs/learn-katacoda#543]
$ odo login -u developer -p developer
/usr/local/bin/odo: line 1: Not: command not found
$ odo project create myproject
/usr/local/bin/odo: line 1: Not: command not found
$

**Comment by coriaedu** [comment]
I had the same issue. Apparently the installed `odo` is corrupt or something. 
I removed `/usr/local/bin/odo` and installed it again following the instructions here: https://github.com/openshift/odo#installing-odo

```
$ curl -L https://github.com/openshift/odo/raw/master/scripts/installer.sh | bash
```

**Comment by BenHall** [comment]
Thanks for letting us know.

It looks like ODO binary referenced has been removed. We've added a temp workaround while we rebuild with the latest version

https://github.com/openshift-labs/learn-katacoda/commit/de308473dda16746c6b3d9be5ef1c44b03473010
