### ISSUE TITLE
Logging in to an OpenShift Cluster : command fails

### ISSUE THREAD

**Issue by dombrowa** [openshift-labs/learn-katacoda#544]
Your Interactive Learning Environment Bash Terminal

$ ~/.launch.sh
Starting OpenShift
Waiting for OpenShift to start... This may take a couple of moments
OpenShift started.
Configuring... OpenShift Ready
$ oc login https://2886795272-8443-simba02.environments.katacoda.com
oc login https://2886795272-8443-simba02.environments.katacoda.com
oc login https://2886795272-8443-simba02.environments.katacoda.com
Authentication required for https://2886795272-8443-simba02.environments.katacoda.com:443 (openshift)
Username: Password:
error: username oc login https://2886795272-8443-simba02.environments.katacoda.com is invalid for basic auth
$

**Comment by GrahamDumpleton** [comment]
To execute the command you click on it once, no need to try and cut and paste it. Here it appears it has been clicked multiple times and thus a second copy of the command was input as the username, which isn't going to be correct, and was thus rejected.

**Comment by dombrowa** [comment]
On IBM Cloud the similar sign only copies the text into the buffer. Here it transfers it directly into the console window. I did no pay attention and just now see a text "Run Command: popping up when hovering over the command text. Human Error.
