### ISSUE TITLE
JBoss BRMS Loan Application on OpenShift: obsolete template and IS links

### ISSUE THREAD

**Issue by jiri-fiala** [openshift-labs/learn-katacoda#547]
The [JBoss BRMS Loan Application on OpenShift](https://learn.openshift.com/middleware/brms-loan-application/) course needs to be updated in regards of where to download the required template and image stream from. Attempting to download the JBoss BRMS 6.4 template and IS from the [old location](https://github.com/jboss-openshift/application-templates/commit/eb4a8b32eb065f3c7726ba7092c6602f4864016a) results in an incompletely prepared environment.

```
$ oc create -f https://raw.githubusercontent.com/jboss-openshift/application-templates/master/decisionserver/decisionserver64-image-stream.json -n openshift
error: unable to read URL "https://raw.githubusercontent.com/jboss-openshift/application-templates/master/decisionserver/decisionserver64-image-stream.json", server reported 404 Not Found, status code=404
$ oc create -f https://raw.githubusercontent.com/jboss-openshift/application-templates/master/decisionserver/decisionserver64-basic-s2i.json -n openshift
error: unable to read URL "https://raw.githubusercontent.com/jboss-openshift/application-templates/master/decisionserver/decisionserver64-basic-s2i.json", server reported 404 Not Found, status code=404
```

It looks like these assets moved again since [the last `env-init.sh` update](https://github.com/openshift-labs/learn-katacoda/commit/49b4daa87433aeace36db2e906e6a1d64605e8ed#diff-3754ccf8658be08df61c53a7c7a5c4ed). Additionally to the `env-init.sh`, the links are noted in [`deploying-to-openshift.md`](https://github.com/openshift-labs/learn-katacoda/blob/a4e1f34c17f8639896c3c1c8987bc08e31f7aa9d/middleware/brms-loan-application/deploying-to-openshift.md) (step 12) too.

**Comment by BenHall** [comment]
Thanks @jiri-fiala we've now pinned the files instead of using master.
