### ISSUE TITLE
502 Bad Gateway for step 2 of 6 in introductory tutorial

### ISSUE THREAD

**Issue by docktermj** [openshift-labs/learn-katacoda#548]
```
502 Bad Gateway
nginx/1.15.5
```

**Comment by docktermj** [comment]
Tutorial:  https://learn.openshift.com/introduction/getting-started/

**Comment by docktermj** [comment]
![Screenshot from 2019-08-26 09-45-25](https://user-images.githubusercontent.com/9219602/63695774-59d4c580-c7e7-11e9-834f-d9177a6e7747.png)

**Comment by BenHall** [comment]
@docktermj Sorry, one of the servers is having a problem and we've removed it from the scheduler.

If you refresh it should have fixed itself.

**Comment by BenHall** [comment]
We believe this is no longer a problem, but if you continue to experience any issues, please let me know.
