### ISSUE TITLE
odo Version Does Not Align with the Tutorial

### ISSUE THREAD

**Issue by danielhelfand** [openshift-labs/learn-katacoda#550]
The `odo` scenario was developed to work with `v1.0.0-beta2`, but this [commit](https://github.com/openshift-labs/learn-katacoda/commit/de308473dda16746c6b3d9be5ef1c44b03473010) changed it so that the scenario downloads  `v1.0.0-beta3`. The output from `odo` commands no longer aligns with the workshop content because of this.

As reported in #549, this may have also broken the tutorial as well. The tutorial should be switched back to version `v1.0.0-beta2` as was done previously:

```
curl -L https://github.com/redhat-developer/odo/releases/download/v1.0.0-beta2/odo-linux-amd64 -o /usr/local/bin/odo && sudo chmod +x /usr/local/bin/odo
```

**Comment by BenHall** [comment]
The problem is this beta2 CLI has been deleted.

Any way we can get it back?
