### ISSUE TITLE
Operator Workshop - September 26, 2019 - 7:30am to 6pm EDT

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#553]
@BenHall 

Hi Ben,

We have an Operator Workshop scheduled for September 26, 2019, 7:30am to 6pm EDT. 130 attendees.

The modules we need on the `/training` site are:

* `/ansibleop/ansible-k8s-modules/`
* `/ansibleop/ansible-operator-overview/`
* and we will most likely have one more which we should be committing soon. I will update this issue with the information.

Thanks!
@mhrivnak @mrhillsman @chris-short @tima

**Comment by BenHall** [comment]
Great. Please let me know when the new content is ready :)

**Comment by madorn** [comment]
One tiny update to the modules that should be featured on the site (in this order):

* `/operatorframework/k8s-api-fundamentals/`
* `/operatorframework/etcd-operator/`
* `/ansibleop/ansible-k8s-modules/`
* `/ansibleop/ansible-operator-overview/`
* `(new content to come)`

**Comment by madorn** [comment]
@BenHall New exercise at #568.

Thanks!

**Comment by BenHall** [comment]
@madorn We need to have the pathway updated too.

Please update with the scenarios and order: 

https://github.com/openshift-labs/learn-katacoda/blob/master/training/operatorframework-pathway.json

https://github.com/openshift-labs/learn-katacoda/blob/master/training/ansibleop-pathway.json
