### ISSUE TITLE
errata corrige on local container filesystem changes

### ISSUE THREAD

**Issue by vernetto** [openshift-labs/learn-katacoda#555]
"changes to the local container filesystem are discarded when the container is stopped": this is not true, you can stop and start a container and the changes are retained. Of course if you create a new container from the image, it can't see the changes made in another container...

in https://learn.openshift.com/introduction/transferring-files/

**Comment by cedricclyburn** [comment]
Hello @vernetto! Just working through issues currently, I double-checked and this content has been removed from the lab, thank you for reporting still!
