### ISSUE TITLE
Operator-SDK lessons are outdated

### ISSUE THREAD

**Issue by camilamacedo86** [openshift-labs/learn-katacoda#559]
The lessons are outdated. Following some points that need to be updated

- It is using version 0.6 when it is 0.10
- Now it is using go mods instead of deps 

<img width="1606" alt="Screenshot 2019-09-12 at 12 12 20" src="https://user-images.githubusercontent.com/7708031/64797779-d43c6e00-d579-11e9-9a4c-a1f629ac55a2.png">

**Comment by camilamacedo86** [comment]
Hi @GrahamDumpleton, 

The vendor dir was removed and mod getting started to be used at 0.9.0 ( see its [CHANGELOG](https://github.com/operator-framework/operator-sdk/blob/master/CHANGELOG.md#v090)

Also, is the image of the Minishift, which is very big downloaded every time for each new classroom?  I do not think so. In this way, I understand that it could be solved in the same way. Note that if the modules already are in the env they will not be downloaded again, it just occurs once.

**Comment by madorn** [comment]
In the process of updating it to newly released `v0.11.0` which will reflect new controller-runtime `v0.2.0`.
