### ISSUE TITLE
script error in the step 1 while Linux Container Internals 2.0 - Lab 5: Container Orchestration

### ISSUE THREAD

**Issue by mins926lee** [openshift-labs/learn-katacoda#566]
the following error came out to:

$ make -C ~/labs/lab2-step4/
make: *** /root/labs/lab2-step4/: No such file or directory.  Stop.
$ docker tag wordpress wordpress:csc
Error response from daemon: no such id: wordpress

**Comment by BenHall** [comment]
@fatherlinux Looks like a timing issue?
