### ISSUE TITLE
Errors in Linux Container Internals 2.0 labs (Error reading manifest latest in registry.access.redhat.com/fedora: name unknown: Repo not found)

### ISSUE THREAD

**Issue by garypicher** [openshift-labs/learn-katacoda#567]
I'm trying to run several of the Linux Container Internals labs and each one has errors performing basic pull and run commands.  For example, in Lab 1, the very first 2 commands fail as follows:

Container host is now ready.
$ podman pull fedora
Trying to pull registry.access.redhat.com/fedora...ERRO[0000] Error pulling image ref //registry.access.redhat.com/fedora:latest: Error initializing source docker://registry.access.redhat.com/fedora:latest: Error reading manifest latest in registry.access.redhat.com/fedora: name unknown: Repo not found
Failed
Trying to pull docker.io/library/fedora...Getting image source signatures
Copying blob 5a915a173fbc done
Copying config e9ed59d2ba done
Writing manifest to image destination
Storing signatures
e9ed59d2baf72308f3a811ebc49ff3f4e0175abf40bf636bea0160759c637999
$ podman run -t fedora cat /etc/redhat-release
ERRO[0000] Error adding network: CNI request failed with status 400: 'pods "affectionate_bohr" not found
                                                                                                        '
ERRO[0000] Error while adding pod to CNI network "openshift-sdn": CNI request failed with status 400: 'pods "affectionate_bohr" not found
                                                                                                                                         '
Error: error configuring network namespace for container f3ad649f5938b1c11d281c2e8a62c9d7ece8b7f363df066bf57a37c9db14d361: CNI request failed with status 400: 'pods "affectionate_bohr" not found

Other labs have very similar failures.  This looks exactly like:

https://github.com/openshift-labs/learn-katacoda/issues/541

...but #541 was closed 6 days ago as resolved.

However, I am still getting that error.  Any ideas?

**Comment by BenHall** [comment]
Thanks @garypicher 

Let me investigate

**Comment by garypicher** [comment]
Thanks, @BenHall !

Here's some more information that might help...  In Lab 4: Container Hosts, the exact same container can be run with docker but not with podman:

Container host is now ready.
$ docker run -td registry.access.redhat.com/ubi7/ubi top
b8f31e3204f58634883ed913c8534b36f7262d3af596f63aa6d46e81bf80db3d
$ docker run -td registry.access.redhat.com/ubi7/ubi top
cc8af0193743955c4c6616a2df2bff73037b8022671f322fcebc1a10c651265d
$ podman run -td registry.access.redhat.com/ubi7/ubi top
ERRO[0000] Error adding network: CNI request failed with status 400: 'pods "recursing_mcclintock" not found
'
ERRO[0000] Error while adding pod to CNI network "openshift-sdn": CNI request failed with status 400: 'pods "recursing_mcclintock" not found
'
Error: error configuring network namespace for container 0cd58551c54554476d911c88b150a43ff60b77039e1d8b11a685b0e11ebeae1b: CNI request failed with status 400: 'pods "recursing_mcclintock" not found

**Comment by BenHall** [comment]
The issue seems to be that `yum versionlock podman-1.3.2` is no longer being applied.

cc'ing @fatherlinux for assistance.

**Comment by BenHall** [comment]
@garypicher Sorry for the delay on this. It has now been fixed.

**Comment by garypicher** [comment]
@BenHall Yep, works great now!  Thanks so much for the help!!
