### ISSUE TITLE
Developing with ODO Step 3

### ISSUE THREAD

**Issue by b1naryZen** [openshift-labs/learn-katacoda#571]
Concerning the backend: The mvn package runs without fail. However, the odo push fails; timing out with terminal message: "waiting for component to start"

**Comment by danielhelfand** [comment]
Hey @b1naryZen! I am unfortunately not able to reproduce this. The `odo push` in step 3 worked for me. We do occasionally experience capacity issues with learn.openshift.com, and it's possible the environment for your tutorial didn't load properly.

If you wouldn't mind trying again, would really appreciate confirmation that the tutorial is working as expected for you.

**Comment by b1naryZen** [comment]
Confirmed - no issue today. Thank you!
