### ISSUE TITLE
Operator SDK with Helm: Adjust version number in command

### ISSUE THREAD

**Issue by javajon** [openshift-labs/learn-katacoda#575]
In this scenario: Operator SDK with Helm
https://learn.openshift.com/operatorframework/helm-operator/

In step 7 of 9 change this line:

`oc get pods -l chart=cockroachdb-2.1.11
`
to this

`oc get pods -l chart=cockroachdb-2.1.13`

This problem also exists on the first two commands of step 8 of 9.

Perhaps query could be made version independent.

**Comment by BenHall** [comment]
Thanks @javajon 

@madorn Could you review please? Thanks!

**Comment by madorn** [comment]
@javajon thank you!!

Updated in #584 

@BenHall

**Comment by javajon** [comment]
Retested and behaves great. Sanity restored.
