### ISSUE TITLE
Lab 5 update to awk commands

### ISSUE THREAD

**Issue by cooper-rh** [openshift-labs/learn-katacoda#577]
In steps 1, 2 and 3 whenever the tutorial instructs to run the command `oc get svc` it returns the type of IP throwing out the original awk command, for example:
`$ curl http://$(oc get svc | grep wpfrontend | awk '{print $2}')/wp-admin/install.php
curl: (6) Could not resolve host: LoadBalancer; Unknown error`

Running `oc get svc` returns:
```
$ oc get svc
NAME               TYPE           CLUSTER-IP      EXTERNAL-IP                     PORT(S)                   AGE
docker-registry    ClusterIP      172.30.178.4    <none>                          5000/TCP                  5h
kubernetes         ClusterIP      172.30.0.1      <none>                          443/TCP,53/UDP,53/TCP     5h
mysql              ClusterIP      172.30.90.157   <none>                          3306/TCP                  14s
registry-console   ClusterIP      172.30.31.236   <none>                          9000/TCP                  5h
router             ClusterIP      172.30.172.33   <none>                          80/TCP,443/TCP,1936/TCP   5h
wpfrontend         LoadBalancer   172.30.49.188   172.29.180.221,172.29.180.221   80:31888/TCP              13s
```
The command should be:
`$ curl http://$(oc get svc | grep wpfrontend | awk '{print $3}')/wp-admin/install.php`

Will add pull request.

**Comment by ryanj** [comment]
Thanks for the contribution, @cooper-rh!
