### ISSUE TITLE
Update FIS example to use the Ui instead of all the command-lines

### ISSUE THREAD

**Issue by apupier** [openshift-labs/learn-katacoda#58]
command-lines is for advanced users when they need to debug, script or access advanced functionalities not available in UI (or old-timer developer).
Please leverage the web UI in the FIS example to deploy images, start builds, check for logs and everything that is possible

My feeling is that if a user si ready to use command-line he.she will be ready to install something on his/her laptop so we don't reach our target audience of this learning.openshift.com platform

**Comment by mhausenblas** [comment]
Seems stale, please re-open if it persists.

**Comment by apupier** [comment]
I don"t have rights to reopen it.

the enhancement request is still valid.

**Comment by mhausenblas** [comment]
OK. We need something more actionable here …

**Comment by apupier** [comment]
> OK. We need something more actionable here …

What about "remove all command-line usage from the tutorial" ?

**Comment by mhausenblas** [comment]
I'm against removing all CLI usage.

**Comment by apupier** [comment]
> I'm against removing all CLI usage.

why?

see my thoughts on the targeted person with these katacoda in first comment https://github.com/openshift-labs/learn-katacoda/issues/58#issue-255321692

**Comment by mhausenblas** [comment]
Let's step back a bit. Are you suggesting removing CLI usage from this scenario or everywhere @apupier?

**Comment by apupier** [comment]
> Let's step back a bit. Are you suggesting removing CLI usage from this scenario or everywhere @apupier?

I think the best is from all examples but as I'm working on Fuse, doing it for the Fuse examples will be a good start.

**Comment by mhausenblas** [comment]
OK, thanks for the clarification @apupier. You can do in your scenario more or less what you want, but again, we will certainly not remove all CLI usage throughout.
