### ISSUE TITLE
Console link not working on container-internals-lab-2-0-part-5

### ISSUE THREAD

**Issue by njr-11** [openshift-labs/learn-katacoda#581]
Steps to reproduce:

Step through this lab:
https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-5

On step 1 where it asks you to log into the console with admin/admin and provides a link,
https://2886795303-8443-cykoria05.environments.katacoda.com/console/project/default/browse/builds
the following error appears when you log in with admin/admin,

```
Error
Access denied
The project default does not exist or you are not authorized to view it.

Return to the console.
```

Fails with both Chrome and Firefox on Mac

**Comment by dagrayvid** [comment]
I also ran into this issue, with Chrome on Fedora.
