### ISSUE TITLE
Developing with Odo: Step 2 of 7 - Creating a service account

### ISSUE THREAD

**Issue by tschultz1216** [openshift-labs/learn-katacoda#582]
Mac OS Mojave 10.14.5
Safari 12.1.1

At this stage(see title) in the tutorial the user is prompted to use the `Dashboard` tab within the web frame to login with a username and password of `developer`. When this action is performed the login prompt throws an error reading: `Could not check CSRF token. Please try again.`

<img width="859" alt="Screen Shot 2019-10-02 at 11 52 22 AM" src="https://user-images.githubusercontent.com/17972464/66060113-20405a00-e50b-11e9-8e9f-3143ff5a97e5.png">

**Comment by BenHall** [comment]
@tschultz1216 Thanks for letting us know. Does this happen every time you attempt to login?

Are you using any browser extensions or proxies which could block cookies?

**Comment by tschultz1216** [comment]
I am using base safari, however I am accessing the page from the IBM enterprise network which directs public internet traffic through a set of trusted proxies. I also experienced this issue when connecting over VPN. Will try to replicate on public internet this evening.

**Comment by BenHall** [comment]
@tschultz1216 That would be great if you can! Thank you.

**Comment by jankleinert** [comment]
Tracking this in https://github.com/openshift-labs/learn-katacoda/issues/658
