### ISSUE TITLE
Operator Workshop - October 10th and 11th, 2019 - 8am to 5pm Central

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#583]
Operator Workshop - October 10th and 11th, 2019 - 8am to 5pm Central

20 attendees.

Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

Thank you!

@BenHall @mrhillsman

**Comment by BenHall** [comment]
This has been organised. If you need anything, please let me know.
