### ISSUE TITLE
Operator Workshop/Meetup - October 17th, 2019 - 6pm to 10pm Central

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#587]
Operator Workshop/Meetup - October 17th, 2019 - 6pm to 10pm Central

75 attendees.

Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

Thank you!

@BenHall

**Comment by BenHall** [comment]
This is confirmed and ready.
