### ISSUE TITLE
Error on Linux Container Internals 2.0 - Lab 5: Container Orchestration

### ISSUE THREAD

**Issue by lpsguilloul** [openshift-labs/learn-katacoda#589]
Hello, 
I'm working on Linux Container Internals 2.0 - Lab 5: Container Orchestration but I cannot finish it. 
There's an error with executing the command "make -C ~/labs/lab2-step4/" :

_Status: Downloaded newer image for docker.io/centos:latest
 ---> 0f3e07c0138f
Step 2/7 : MAINTAINER fatherlinux <scott.mccarty@gmail.com>
 ---> Running in 5d0d754e5f57
 ---> 67fb4d1fb86c
Removing intermediate container 5d0d754e5f57
Step 3/7 : ENV COREBUILD_VERSION 7.2
 ---> Running in 0292766d1a21
 ---> 220494ae8b27
Removing intermediate container 0292766d1a21
Step 4/7 : RUN yum install -y --setopt=tsflags=nodocs yum-utils &&     yum clean all &&     rm -rf /var/cache/yum/*
 ---> Running in 84cf095c9935

**CentOS-8 - AppStream                            0.0  B/s |   0  B     00:30
CentOS-8 - Base                                 0.0  B/s |   0  B     00:30
CentOS-8 - Extras                               0.0  B/s |   0  B     00:30
Failed to synchronize cache for repo 'AppStream', ignoring this repo.
No match for argument: yum-utils
Failed to synchronize cache for repo 'BaseOS', ignoring this repo.
Failed to synchronize cache for repo 'extras', ignoring this repo.
Error: Unable to find a match
The command '/bin/sh -c yum install -y --setopt=tsflags=nodocs yum-utils &&     yum clean all &&    rm -rf /var/cache/yum/*' returned a non-zero code: 1
make: *** [corebuild.o] Error 1**
make: Leaving directory `/root/labs/lab2-step4'_

It's trying to use CentOS-8 repository pour centos 7 image.

Could you please analyse this problem?  Is there a way for me to fix it so I can continue with the exercise?

Thanks a lot for your help.

Best Regards,

Lourdes

**Comment by BenHall** [comment]
Thanks for letting us know.

@fatherlinux Could you help please?

**Comment by BenHall** [comment]
I believe this is currently being worked on at https://github.com/openshift-labs/learn-katacoda/pull/595
