### ISSUE TITLE
Getting error while log in via web console

### ISSUE THREAD

**Issue by TriptiT** [openshift-labs/learn-katacoda#590]
I am working on "https://learn.openshift.com/middleware/fuse-hello-world".
After log in via console I'm getting this:
*********************************
Error
Invalid request
The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.

Return to the console.
********************************

**Comment by BenHall** [comment]
@TriptiT Thanks for letting us know and sorry for the trouble. We are actively trying to identify and reproduce the issue.

Couple you help with:
1) Could you be on a network blocking the use of cookies?
2) Do you have any browser ad-blockers
3) Do you have the console window open in multiple tabs?

**Comment by TriptiT** [comment]
No. I worked on other scenarios and never had any such issue.

**Comment by BenHall** [comment]
@TriptiT Thanks, that is helpful. If you refresh and use a another session, does the problem correct itself?

**Comment by ryanj** [comment]
Thanks for reporting @TriptiT!

I believe we have removed the fuse content from our site index.  New users shouldn't be able to reach the content (or the error)
