### ISSUE TITLE
Operator Workshop at Open Source Summit EU - Lyon, France - October 29th, 2019 - 13:00 - 23:00 CET

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#592]
Operator Workshop at Open Source Summit EU - Lyon, France - October 29th, 2019 - 13:00 - 23:00 CET

150 attendees.

Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

Thank you!

@BenHall

**Comment by BenHall** [comment]
Confirmed and booked.

Are you sure you need the capacity until that late into the evening? Leaving the machines running incurs a significant increase in the bill. Maybe one for email ;)

I'll be attending Open Source Summit EU so it would be great to meet.
