### ISSUE TITLE
Operator Workshop at CERN, Switzerland - October 31st, 2019 - 10:00 - 18:00 CET, November 1st, 2019 - 10:00 - 18:00 CET

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#593]
Operator Workshop at CERN, Switzerland - October 31st, 2019 - 10:00 - 18:00 CET, November 1st, 2019 - 10:00 - 18:00 CET

170 attendees.

Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

Thank you!

@BenHall

**Comment by BenHall** [comment]
Done!
