### ISSUE TITLE
servicemesh/8-egress makes reference to now.httpbin.org in doc

### ISSUE THREAD

**Issue by komish** [openshift-labs/learn-katacoda#612]
This workshop: https://learn.openshift.com/servicemesh/8-egress Makes a reference in the documentation text to `now.httpbin.org`, but I _believe_ this was changed to worldclockapi.com 

https://github.com/openshift-labs/learn-katacoda/blob/master/servicemesh/8-egress/2istioize-egress.md

Wanted to be sure before I submitted a PR to make the change or bundled it into #610

**Comment by BenHall** [comment]
@komish 

Thanks for pointing this out. Please add to #610. I'll check and merge this soon.

**Comment by komish** [comment]
@BenHall Done and done. Thanks!
