### ISSUE TITLE
OpenShift Workshop - 11th November, 2019 - 12:-00pm to 4pm AEST (UTC+10:00) Melbourne time

### ISSUE THREAD

**Issue by bfarr-rh** [openshift-labs/learn-katacoda#615]
Hi

We have a BHP workshop to use the following labs from learn.openshift.com for 20 people if you can please help.

Foundations of Openshift:
Getting Started with OpenShift for Developers - 30 mins
Logging in to an OpenShift Cluster - 10 mins
Deploying Applications From Images - 15 mins
Deploying Applications From Source - 30 mins
Connecting to a DB Using Port Forwarding - 15 mins
Using OpenShift metrics - 30 mins

Building Applications On OpenShift:
Spring Boot development on OpenShift - 15 minutes
Getting Started with Quarkus - 10 minutes

Thanks

Ben

**Comment by BenHall** [comment]
@bfarr-rh Thanks for letting us know. Given the day and timezone, there should be enough capacity available.
