### ISSUE TITLE
Error on Dashboard

### ISSUE THREAD

**Issue by leroysallie** [openshift-labs/learn-katacoda#616]
Hi 

I receive the below error when trying to access the dashboard.

Error
Invalid request
The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.

Return to the console.

**Comment by jankleinert** [comment]
@leroysallie Which scenario is giving you this error? Can you provide the URL of the page where you're seeing this problem?

**Comment by ryanj** [comment]
Hi @leroysallie - this should be fixed now.

Feel free to reopen the ticket if you're still seeing this issue
