### ISSUE TITLE
Unable claim a persistent volume

### ISSUE THREAD

**Issue by tonymalynn9** [openshift-labs/learn-katacoda#619]
Foundations of OpenShift

Transferring Files in and out of Containers
- Topic 5 - Copying Files to a Persistent Volume

Unable to claim a persistent volume and mount it against our dummy application (step 4), as no persistent volumes available for this claim and no storage class is set...

**Comment by jankleinert** [comment]
@tonymalynn9 This scenario was updated to OpenShift 4.2 today. Can you please try now and see if it's working as expected?

**Comment by tonymalynn9** [comment]
@jankleinert PVC is working correctly thanks! :-)
