### ISSUE TITLE
Operator Workshop at Kubecon, San Diego, CA, US - November 21, 2019 -  3:00pm - 7:00pm PT

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#620]
Operator Workshop at Kubecon, San Diego, CA, US - November 21, 2019 -  3:00pm - 7:00pm PT

200 attendees.

Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

Thank you!

@BenHall
@mhrivnak
@mrhillsman

**Comment by BenHall** [comment]
Confirmed.

`Thursday 21-11-2019 at 23:00 UTC until Friday 22-11-2019 at 03:00 UTC`
