### ISSUE TITLE
Error - The content owner's account has reached capacity. Please try again in 10 minutes

### ISSUE THREAD

**Issue by gr8nilesh** [openshift-labs/learn-katacoda#622]
Errors Appearing while starting the scenario on https://learn.openshift.com/playgrounds/openshift39/
Error --> "The content owner's account has reached capacity. Please try again in 10 minutes"

**Comment by BenHall** [comment]
Sorry for the error. We believe this was due to a spike in traffic. It should be available for you to use now.
