### ISSUE TITLE
Workshops 

### ISSUE THREAD

**Issue by anurag-saran** [openshift-labs/learn-katacoda#624]
I will be hosting 3 sessions i.e. on Dec 4,5 and 10th - 9 am EST to 4 PM EST) and would use the below modules. Please ensure this scales up to 30 users.

https://learn.openshift.com/introduction/
https://learn.openshift.com/middleware/courses/middleware-quarkus/getting-started

@BenHall

**Comment by BenHall** [comment]
@anurag-saran Do you know which scenarios within the introduction course you are hoping to run?

**Comment by anurag-saran** [comment]
@BenHall : I am planning to run the first 9 labs on all the three days(Dec 4,5 and 10th ): i.e.
Getting Started with OpenShift for Developers
Logging in to an OpenShift Cluster
Developing with odo
Deploying Applications From Images
Deploying Applications From Source
Using the CLI to Manage Resource Objects
Connecting to a Database Using Port Forwarding
Transferring Files in and out of Containers
Exploring and using metrics and HPAs

**Comment by anurag-saran** [comment]
@BenHall Are we all set. Please confirm.

**Comment by BenHall** [comment]
As we don't have the scale-out capability for 4.2 yet as it's only just been added, we've added more capacity to the on-demand which will hopefully give you enough capacity.
