### ISSUE TITLE
OpenShift workshop at DBS Bank, Singapore on Dec 3rd

### ISSUE THREAD

**Issue by kgshukla** [openshift-labs/learn-katacoda#627]
Hi,

Could you please reserve following labs for DBS Bank. We would be running the same set of labs in morning and afternoon and each session would have 40 folks. Here are the labs -

Lab 1
https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-1

Lab 2
https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-2

Lab 3
https://learn.openshift.com/introduction/getting-started/

Lab 4
https://learn.openshift.com/introduction/resource-objects/

Lab 5
https://learn.openshift.com/introduction/using-metrics/

Lab 6
https://learn.openshift.com/introduction/developing-with-odo/

**Comment by jankleinert** [comment]
@BenHall

**Comment by kgshukla** [comment]
Hi @BenHall 

Could you please confirm whether this will be provisioned on time?

**Comment by BenHall** [comment]
Hi,

Each of these environments is using a different version of OpenShift (3.6, 3.11 and 4.2). We currently don't have 3.6 (Metrics) and 4.2 available with additional scale-out capacity.

I'll need to check to see how much capacity is available for these via the on-demand platform.

In the meantime, could you please confirm the time for the two workshops.

**Comment by kgshukla** [comment]
Hi @BenHall,

I can leave Metrics workshop. But the others are needed.

The workshop is repeated twice on Dec 3rd, starting at 9:30am Singapore Time and ends 4:30pm Singapore time. Basically 2 sessions on Dec 3rd. Each session will have up to 40 folks.

**Comment by BenHall** [comment]
As we don't have the scale-out capability for 4.2 yet as it's only just been added, we've added more capacity to the on-demand which will hopefully give you enough capacity.
