### ISSUE TITLE
Trying to use tutorial and on console login get an error and can't log in to the console

### ISSUE THREAD

**Issue by jsaulman** [openshift-labs/learn-katacoda#629]
![Screen Shot 2019-11-27 at 3 28 49 PM](https://user-images.githubusercontent.com/2637562/69760647-af907500-112a-11ea-983c-28b744729491.png)

**Comment by jafloresg** [comment]
I have the same issue

**Comment by jafloresg** [comment]
I have seen there is a workaround:https://github.com/openshift-labs/learn-katacoda/issues/41#issuecomment-317872754

**Comment by jankleinert** [comment]
Tracking this in https://github.com/openshift-labs/learn-katacoda/issues/658
