### ISSUE TITLE
Lab setup fails when i tries to launch scenario

### ISSUE THREAD

**Issue by alibaba1975** [openshift-labs/learn-katacoda#630]
When I tries to launch scenario (https://learn.openshift.com/middleware/fuse-hello-world/ ) to do the hands on, setup fails with the following error.
 "The content owner's account has reached capacity. Please try again in 10 minutes"

it appears some clean up seems needed.

Please fix the issue

Thanks

**Comment by BenHall** [comment]
We believe this was due to a peak in traffic. The scenario appears to be accessible now, please let us know if you continue to have problems.
