### ISSUE TITLE
Operator Workshop at Red Hat office, Sunnyvale, CA, US - December 16 an 17, 2019 - 8am to 5pm PT

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#632]
Operator Workshop at Red Hat office, Sunnyvale, CA, US - December 16 an 17, 2019 - 8am to 5pm PT

50 attendees.

Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

Thank you!

@BenHall
@mrhillsman

**Comment by BenHall** [comment]
Ready!
