### ISSUE TITLE
Kubernetes Forum Sydney: Attendee Access to Katacoda

### ISSUE THREAD

**Issue by hatmarch** [openshift-labs/learn-katacoda#633]
Hello,

The [Sydney Kubernetes Forum](http://bit.ly/347bLKb) is running from **8am-6pm 12 Dec AEDT**.  Red Hat is a platinum sponsor at this event and we will have a few terminals setup at the booth for conference attendees to play with the different labs.  Attendees are expected to be from both Ops and Development backgrounds so many of the labs are expected to get some traffic.

While we expect increased interest in Katacoda at this time, we will only have 3 terminals setup at the booth dedicated to Katacoda tutorials.  I don't know how this impacts scaling plans but I thought I should let you guys know.

Cheers,
Marc

**Comment by BenHall** [comment]
Thanks for letting us know Marc. We've added some additional capacity to
ensure that you can use the labs on the booth. If you have any questions,
or need anything, please let us know.
