### ISSUE TITLE
Operator Workshop - Remote - December 19 an 20, 2019 - 7am to 6pm Central Time

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#634]
Operator Workshop - Remote - December 19 an 20, 2019 - 7am to 6pm Central Time

30 attendees

Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

Thank you!

@BenHall
@mrhillsman

**Comment by BenHall** [comment]
Ready!
