### ISSUE TITLE
Externalized Configuration tutorial - Error with fabric8

### ISSUE THREAD

**Issue by tbizouerne** [openshift-labs/learn-katacoda#636]
Hi,

There is an error when executing the following command of the tutorial "Externalized Configuration" : 
 > mvn package fabric8:deploy -Popenshif

We see the error (during maven build) : 
[ERROR] No plugin found for prefix 'fabric8' in the current project and in the plugin groups

**Comment by jamesfalkner** [comment]
Fixed with https://github.com/openshift-katacoda/rhoar-getting-started/pull/70
