### ISSUE TITLE
Developer Workshop - using learn.openshift.com

### ISSUE THREAD

**Issue by tnscorcoran** [openshift-labs/learn-katacoda#643]
We have a team of approximately 15 developers from our customer ANZ Bank who will be hitting
the following http://learn.openshift.com labs between 11am and 1.30pm AEST Wednesday 15th January. These labs in particular:

- Foundations of Openshift
- Getting Started with OpenShift for Developers
- Logging in to an OpenShift Cluster 
- Deploying Applications From Images
- Deploying Applications From Source

Please ensure system is active and can take this demand during this period.

@ Ben Hall

**Comment by jankleinert** [comment]
@BenHall

**Comment by BenHall** [comment]
We'll check and confirm depending on how much the current traffic and capacity levels are at.

**Comment by BenHall** [comment]
To confirm this doesn't be a problem.
