### ISSUE TITLE
All topics in "Subsystems, Components, and Internals" is inaccessible: missing button "start scenario"

### ISSUE THREAD

**Issue by bravosierrasierra** [openshift-labs/learn-katacoda#645]
All topics in "Subsystems, Components, and Internals" https://learn.openshift.com/subsystems/ is inaccessible: missing button "start scenario"

**Comment by bravosierrasierra** [comment]
Button "start scenario" present only in first lesson

**Comment by BenHall** [comment]
Thanks @bravosierrasierra we've just deployed a fix to the CSS
