### ISSUE TITLE
Terminal availability

### ISSUE THREAD

**Issue by AlbertoRebolloRequena** [openshift-labs/learn-katacoda#646]
Hi!
Could you please check terminal availability?
At 'https://learn.openshift.com/introduction/getting-started/' lab, on last 2 days, I´ve found next error: "We are currently at capacity with no additional nodes available. Please check back in 10 minutes.".
Thanks and regards!

**Comment by BenHall** [comment]
Thanks for reporting the issue. We had a reduced capacity over the weekend while we completed some maintenance work. This been completed and the full capacity should be available.

If you continue to have issues, please let us know.
