### ISSUE TITLE
Cannot start the scenarios Linux Container Internals 2.0 - Lab 6 and Lab 7

### ISSUE THREAD

**Issue by akhil-rane** [openshift-labs/learn-katacoda#651]
I am unable to start this scenario as there in no "Start Scenario" button for the following scenarios
1) Linux Container Internals 2.0 - Lab 6: Container Standards
2) Linux Container Internals 2.0 - Lab 7: Container Tools Ecosystem

**Comment by BenHall** [comment]
Thanks, this has been fixed.
