### ISSUE TITLE
Error logging into OC

### ISSUE THREAD

**Issue by medircz** [openshift-labs/learn-katacoda#652]
I cannot login to OC:
![image](https://user-images.githubusercontent.com/23638560/73304670-4e465a00-41de-11ea-8477-42d1180e7640.png)

**Comment by jankleinert** [comment]
@medircz which scenario did this happen on?

**Comment by jankleinert** [comment]
Tracking this in https://github.com/openshift-labs/learn-katacoda/issues/658
