### ISSUE TITLE
Deprecated command: `operator-sdk generate openapi` used in module "Operator SDK with Go"

### ISSUE THREAD

**Issue by harishsurf** [openshift-labs/learn-katacoda#653]
"Operator SDK with Go" tutorial (https://learn.openshift.com/operatorframework/go-operator-podset/) 
uses a deprecated command:  operator-sdk generate openapi.  (seen in step 3)

Expected: The tutorial should be updated to use the new command : operator-sdk generate crds

**Comment by madorn** [comment]
Thanks @HarishSandbox - we will be updating these modules soon!

**Comment by madorn** [comment]
@harishsurf Operator-SDK exercise has been updated here: https://learn.openshift.com/operatorframework/go-operator-podset/

@BenHall this issue can be closed.

**Comment by madorn** [comment]
@jankleinert this issue can be closed. Thanks!
