### ISSUE TITLE
Feedback on Linux Container Internals 2.0 - Lab 5: Container Orchestration

### ISSUE THREAD

**Issue by peterf-work** [openshift-labs/learn-katacoda#654]
Thank you for providing these labs.
For this lab in MS Edge, the video could not be viewed.  The window never opened enough to see it.
For Step 1, it references opening Terminal 2, but there are not instructions on how to do this.
It is not obvious that the + "Web Preview" button opens a new terminal.
Thank You,
Peter

**Comment by fatherlinux** [comment]
@peterf-work thanks for the feedback. I've actually overhauled the lab quite a bit and removed some of the weird stuff you had to do with multiple terminals. I'd like to invite you back to take a look and give me feedback about the way it's structured now. Here's the link for convenience: https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-5
