### ISSUE TITLE
Postgres Image required by Tutorial "Spring Boot Development on Openshift" not found

### ISSUE THREAD

**Issue by mastawit** [openshift-labs/learn-katacoda#656]
While Step 5 of 5 ill try to execute oc new app .. for providing a postgres DB on OSCP with th following result:
![grafik](https://user-images.githubusercontent.com/48478990/74149021-0cb6a580-4c07-11ea-82ca-b23fa2f9d0b7.png)

**Comment by jamesfalkner** [comment]
Fixed in https://github.com/openshift-labs/learn-katacoda/commit/ba356dd72d1a3d4ef05895c5041ff277dcf98cfa#diff-5991dc00f18447df38568c8b599a19658165072f8ee06bab903f3446b6ba6769 (and further updated all around in subsequent fixes).
