### ISSUE TITLE
Problem logging into Web Console section of learn.openshift.com

### ISSUE THREAD

**Issue by sgerritz** [openshift-labs/learn-katacoda#658]
Hello, In order to learn the OCP demo, I have logged into learn.openshift.com .   I was able to login successfully to the CLI screen using userid: developer pw: developer... .....hooray.

When I try and log into the Web Console with the same userid & pw (per the instructions) , the system comes back with "Could not check CSRF token" .

I have attached a screen shot as well.

I like this tutorial, learn.openshift.com  but it won't let me advance through the Web console portion.

Any thoughts on how to get through this issue?

Thanks

[Learn.openshift.com screen shot.pdf](https://github.com/openshift-labs/learn-katacoda/files/4187577/Learn.openshift.com.screen.shot.pdf)

**Comment by ejeklint** [comment]
I have the same problem with Safari browser.

Workaround: use Chrome or Edge instead. 🙀

**Comment by jankleinert** [comment]
I was able to reproduce this in Safari. 

@BenHall This error happens with the Safari browser for the 4.2 scenarios. It works fine (error does not happen) for 3.11 scenarios. It also works fine for a regular 4.2 cluster (i.e. not within katacoda). Can you take a look please. I'm not sure if it's something related to katacoda or if it might be something related to the version of 4.2 being used.

**Comment by BenHall** [comment]
Thanks @jankleinert . We've identified the issue and are testing a fix. The problem is due to 3rd party cookies, the iframe and the default Safari security. When the console link is opened in a separate tab it works as expected.

**Comment by BenHall** [comment]
FYI: This went live last week.

**Comment by jankleinert** [comment]
@ejeklint @sgerritz Could one of you please confirm if this is working for you now?

**Comment by ejeklint** [comment]
It works now. But... clicking on the Console tab now opens three new Safari tabs! Guess we can't have enough of them. :)

**Comment by btannous** [comment]
thanks for the fix @BenHall
