### ISSUE TITLE
Multi-user workspace using jupyterhub scenario is pulling the wrong version of an image

### ISSUE THREAD

**Issue by jankleinert** [openshift-labs/learn-katacoda#662]
It's trying to use quay.io/jupyteronopenshift/s2i-minimal-notebook-py35:2.5.0 which doesn't exist. Need to try 2.5.1 and test to make sure it works.

**Comment by jankleinert** [comment]
![Image from iOS (2)](https://user-images.githubusercontent.com/651728/75346320-702e0d80-586c-11ea-9724-d05fd3471051.jpg)

**Comment by BenHall** [comment]
@jankleinert Do you need anything from me to help with this?

**Comment by jankleinert** [comment]
@BenHall No, this is something my team will address :)
