### ISSUE TITLE
OpenShift Meetup: February March 26th 6-8pm AEDT

### ISSUE THREAD

**Issue by hatmarch** [openshift-labs/learn-katacoda#664]
Hello,

Just in an excess of caution I wanted to advise you all that we will have up to 35 people hitting katacoda from 6-8pm AEDT for an OpenShift Meetup that we will be running that night in Melbourne, Australia.  We expect them to be hitting the introductory OpenShift demos under: https://learn.openshift.com/introduction/

If any capacity allowances need to be made, can you please plan accordingly?

Please let me know if you need more information.

Cheers,
Marc

**Comment by BenHall** [comment]
Thanks for letting us know. We'll plan accordingly.
