### ISSUE TITLE
Playground (OpenShift 3.11) certificate error during login

### ISSUE THREAD

**Issue by aroyatibm** [openshift-labs/learn-katacoda#668]
$ launch.sh
Starting OpenShift
Waiting for OpenShift to start... This may take a couple of minutes
OpenShift started.
Configuring...
OpenShift Ready
$ oc login -u developer -p developer
error: x509: certificate signed by unknown authority

**Comment by 4n4nd** [comment]
I had a similar issue, adding the following worked for me:
```bash
curl -LO https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem > /dev/null 2>&1
oc login -u developer -p developer --certificate-authority=lets-encrypt-x3-cross-signed.pem --insecure-skip-tls-verify=true > /dev/null 2>&1
```
I found it [here](https://github.com/openshift-labs/learn-katacoda/blob/master/introduction/getting-started-311/set-env.sh#L3-L4)

**Comment by ryanj** [comment]
This should be resolved now.  Feel free to open another ticket if you encounter a similar issue
