### ISSUE TITLE
Openshift web console inoperative in Chrome

### ISSUE THREAD

**Issue by Monte-Christo** [openshift-labs/learn-katacoda#671]
In Chrome 80.0.3987.132, when i click on the Console tab in https://learn.openshift.com/introduction/getting-started/
I get a blank pane where the login box ought to be.
<img width="881" alt="empty-console" src="https://user-images.githubusercontent.com/8224318/76170931-d9742180-6186-11ea-980b-038d4641cc22.png">

**Comment by jankleinert** [comment]
If you resize your browser window, does. it solve the problem?
@BenHall FYI. I've seen this happen once or twice too.

**Comment by Monte-Christo** [comment]
I can resize until I am blue in the face. Unfortunately, no change. The login dialog box will not appear.

**Comment by btannous** [comment]
I believe this is fixed as per https://github.com/openshift-labs/learn-katacoda/issues/658
Closing, please reopen if the issue is not fixed.  Thank you!
