### ISSUE TITLE
Pre pull images for operator usage

### ISSUE THREAD

**Issue by 4n4nd** [openshift-labs/learn-katacoda#676]
Is there a way to pre pull images for the openshift 4.2 environment like the [openshift 3.11(https://github.com/openshift-labs/learn-katacoda/blob/master/environments/openshift-3-11/scripts/4_middleware-pull.sh) env?

We are trying to set up the [opendatahub operator](https://gitlab.com/opendatahub/opendatahub-operator/-/blob/master/docs/manual-installation.adoc), but the workshop user has to wait more than 10 minutes for the images to be pulled.

**Comment by BenHall** [comment]
Not at the moment but we are working on this.

**Comment by 4n4nd** [comment]
@BenHall If I add the images I need to the build directory [here](https://github.com/openshift-labs/learn-katacoda/tree/master/environments/openshift-4-2/master/build), would that do the job?

**Comment by ryanj** [comment]
Looks like this change is in place: https://github.com/openshift-labs/learn-katacoda/blob/master/environments/openshift-4-7/master/build/5_odh-pull.sh

Thanks @4n4nd - feel free to reopen if it's not working correctly
