### ISSUE TITLE
Could not load image metadata in Scenario: "Deploying Applications From Images" in course "Foundations of OpenShift" 

### ISSUE THREAD

**Issue by ashwinchandran13** [openshift-labs/learn-katacoda#677]
While entering the image name field inside add container image option in console  Could not load image metadata shows up.

Image attached is the output obtained: 
![image](https://user-images.githubusercontent.com/28646365/76696470-f0000880-66b1-11ea-994e-9238df43f74f.png)

**Comment by jankleinert** [comment]
I'm not able to reproduce the problem; it's working for me right now. It looks like you have the right image name. Can you try again and see if the issue is still happening for you?

**Comment by ashwinchandran13** [comment]
My apologies, if you can see in the screenshot I hadn't selected the project name so that was the reason for the error I think so. Thank you.
