### ISSUE TITLE
Console Login issue

### ISSUE THREAD

**Issue by sshekghub** [openshift-labs/learn-katacoda#678]
For the "Deploying Applications From Image" interactive learning Getting the following error when trying to login to console 

Could not check CSRF token. Please try again.

**Comment by sshekghub** [comment]
It seems this issue is across the interactive learning portal.

**Comment by BenHall** [comment]
Thanks for letting us know. Could you please let us know if you are running any anti-virus and ad-blocker browser extensions? Also please confirm your browser version and OS.

Does this happen if you load the console in a separate tab (by clicking the little icon to open a new window)

**Comment by sshekghub** [comment]
Google Chrome Version 80.0.3987.132 (Official Build) (64-bit) and Windows 10 1803 build.
Yes for Anti virus and No for ad-blocker extensions.

It did work fine when I loaded it in a separate tab. So for now will continue with that. Thanks !

**Comment by btannous** [comment]
I believe this is fixed as per https://github.com/openshift-labs/learn-katacoda/issues/658
Closing, please reopen if the issue is not fixed.  Thank you!
