### ISSUE TITLE
Logging Into Console

### ISSUE THREAD

**Issue by richie-atos** [openshift-labs/learn-katacoda#679]
Attempted to login through the console (_step 2 of the getting started with open shift for developers_) with the supplied username and password (_developer for both_) but the from displaying the console returned the message:

Could not check CSRF token. Please try again. 

![image](https://user-images.githubusercontent.com/12546251/76763403-f31af780-678a-11ea-8240-f63775787bc2.png)

**Comment by richie-atos** [comment]
Just noticed however clicking on the icon between the + and the refresh buttons, pulls out the console into another browser tab, this did for whatever reason allow me to login successfully. NOt doing this I would have been none the wiser and stopped where I was.

**Comment by jankleinert** [comment]
@BenHall It looks like this is starting to pop-up more frequently.
@richie-atos Which browser are you using?

**Comment by richie-atos** [comment]
Chrome

**Comment by btannous** [comment]
I believe this is fixed as per https://github.com/openshift-labs/learn-katacoda/issues/658
Closing, please reopen if the issue is not fixed.  Thank you!
