### ISSUE TITLE
Disconnected 

### ISSUE THREAD

**Issue by sanjaygeeky** [openshift-labs/learn-katacoda#685]
Hello
I got disconnected midway doing the session

**Comment by BenHall** [comment]
Sorry about this. Could you please let us know when scenario you where completing and how long you were connected for?

**Comment by sanjaygeeky** [comment]
Thanks for quick response Appreciated. I was attending a session https://www.meetup.com/Cloud-Pune-Meetup/events/269455414/ and proceeded to step after which the screen hanged

**Comment by ryanj** [comment]
Thanks for reporting @sanjaygeeky 
Hopefully this issue has been fixed - Feel free to reopen if you're still seeing the issue
