### ISSUE TITLE
Could not check CSRF token

### ISSUE THREAD

**Issue by diracsol** [openshift-labs/learn-katacoda#686]
Hi, I am at step 2 of getting started with Openshift interactive tutorial (https://learn.openshift.com/introduction/getting-started/_, where I have to login using "developer" login and password. I am able to login from CLI, but when I try console login, I am getting "Could not check CSRF token. Please try again."

**Comment by BenHall** [comment]
Hi @diracsol 

Sorry for the problem.

We've made a change, could you please try again and let us know if the issue continues?

If it does, please let us know your browser version and OS.

**Comment by diracsol** [comment]
Thanks a ton for your prompt help. It is working now
