### ISSUE TITLE
Operator Workshop - Remote - April 1st and 2nd, 2020 - 4pm to 9pm Central Time

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#694]
Operator Workshop - Remote - April 1st and 2nd, 2020 - 4pm to 9pm Central Time

20 attendees

Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

Thank you!

@BenHall
@mrhillsman

**Comment by BenHall** [comment]
This has been scheduled.
