### ISSUE TITLE
in lab "Messaging with OpenShift and Red Hat AMQ" there is no amq image

### ISSUE THREAD

**Issue by hugomelendez** [openshift-labs/learn-katacoda#700]
See 'oc new-app -h' for examples.
$ oc new-app amq-broker-71-basic -p AMQ_PROTOCOL=openwire,amqp,stomp,mqtt -p AMQ_USER=amquser -p AMQ_PASSWORD=amqpassword -p AMQ_QUEUES=example
error: Errors occurred while determining argument types:

amq-broker-71-basic as a local directory pointing to a Git repository:  stat amq-broker-71-basic: no such file or directory

Errors occurred during resource creation:
error: no match for "amq-broker-71-basic"

The 'oc new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet.

See 'oc new-app -h' for examples.
$

**Comment by hugomelendez** [comment]
$ oc new-app amq-broker-71-basic -p AMQ_PROTOCOL=openwire,amqp,stomp,mqtt -p AMQ_USER=amquser -p AMQ_PASSWORD=amqpassword -p AMQ_QUEUES=example
error: Errors occurred while determining argument types:

amq-broker-71-basic as a local directory pointing to a Git repository:  stat amq-broker-71-basic: no such file or directory

Errors occurred during resource creation:
error: no match for "amq-broker-71-basic"

The 'oc new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet.

See 'oc new-app -h' for examples.
$

**Comment by jankleinert** [comment]
@jamesfalkner Could you assign someone to take a look at this one please? When I look at the console logs in the browser, it looks like the env-init.sh steps are failing: 

```
Background Output bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
Now using project "openshift" on server "https://172.17.0.16:8443".
**error: the path "/opt/amq-broker-71-basic.yaml" does not exist
error: the path "/opt/amq-7-image-streams.json" does not exist**
��
================================================================================
================================================================================

                              DEPRECATION WARNING                            

  Node.js 8.x LTS Carbon is no longer actively supported!

  You will not receive security or critical stability updates for this version.

  You should migrate to a supported version of Node.js as soon as possible.
  Use the installation script that corresponds to the version of Node.js you
  wish to install. e.g.

   * https://deb.nodesource.com/setup_10.x — Node.js v10 LTS "Dubnium" (recommended)
   * https://deb.nodesource.com/setup_12.x — Node.js v12 LTS "Erbium"

  Please see https://github.com/nodejs/Release for details about which
  version may be appropriate for you.

  The NodeSource Node.js distributions repository contains
  information both about supported versions of Node.js and supported Linux
  distributions. To learn more about usage, see the repository:
    https://github.com/nodesource/distributions

================================================================================
================================================================================

Continuing in 20 sec
```

**Comment by jamesfalkner** [comment]
@hguerrero can you take a look?

**Comment by hguerrero** [comment]
this script is not running: https://github.com/hguerrero/learn-katacoda/blob/master/middleware/amq-getting-started-broker/env-init.sh

**Comment by hguerrero** [comment]
was not the script, in fact the script is running and that's why @jankleinert was receiving the error. So I added the files to the client and the host01. That made it work again in my environment. HEre is the PR https://github.com/openshift-labs/learn-katacoda/pull/724
