### ISSUE TITLE
Debezium Deployment

### ISSUE THREAD

**Issue by abdraziquesdi** [openshift-labs/learn-katacoda#701]
In the 2nd Step, Embed Debezium into Connect, url needs to be changed

Maven Repository needs to be changed from :
http://central.maven.org/maven2/io/debezium/debezium-connector-mysql/0.10.0.Final/debezium-connector-mysql-0.10.0.Final-plugin.tar.gz

to 
https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/0.10.0.Final/debezium-connector-mysql-0.10.0.Final-plugin.tar.gz

**Comment by jankleinert** [comment]
fixed via https://github.com/openshift-labs/learn-katacoda/pull/722
