### ISSUE TITLE
Open Shift Container Platform 4 Troubleshooting: Ingress Controller.

### ISSUE THREAD

**Issue by ravi-kulkarni26** [openshift-labs/learn-katacoda#713]
This is  on role website and related to the learning subscription.  Note: We are trying to Break-fix the issues which has been provided in open Shift Container Platform 4 Troubleshooting: Ingress Controller.

Why we are not able to achieve the output. Please help us to complete the same. 
Update Certificates in the Lab Environment RHOCP 4 handles certificate renewal automatically using the openshift-controller-manager
•	Assumption: the cluster will remain online during periods of certificate renewal
•	In you lab environment: this was installed some time ago. It is possible that the environment was offline during its scheduled automatic certificate renewal.
Before starting the break-fix exercise, make sure this environment is online and in a Ready state:
(1) Become user1 on the classroom VM:
[root@classroom ~]# su - user1
[user1@classroom ~]$ echo $KUBECONFIG
/home/user1/training1/auth/kubeconfig
(2) Run oc get nodes and inspect the STATUS for each of the cluster nodes:
[user1@classroom ~]$ oc get nodes
NAME      STATUS   ROLES    AGE    VERSION
master0   Ready    master   3d1h   v1.13.4+c3617b99f
worker0   Ready    worker   3d1h   v1.13.4+c3617b99f
worker1   Ready    worker   3d1h   v1.13.4+c3617b99f"

**Comment by jankleinert** [comment]
@ravi-kulkarni26 Is this related to a scenario on learn.openshift.com, or is it related to something else?

**Comment by ravi-kulkarni26** [comment]
@jankleinert : Yes this is related to lab scenario on https://labs.opentlc.com

I am getting error while doing lab practice for open Shift Container Platform 4 Troubleshooting: Ingress Controller topic 

Can you plz help me so that i can install the certificate

**Comment by jankleinert** [comment]
@ravi-kulkarni26 This repository is unrelated to the labs on labs.opentlc.com. I'm trying to find out the right channel for you to raise this issue, and I'll update once I hear back.

**Comment by ajblum** [comment]
Hello @ravi-kulkarni26 ,

I'm on the Red Hat team responsible for this content.  Prior to 4/16 control plane certificates on the OCP cluster in the learning environment were expired resulting in messages like 'Unable to connect to the server: x509: certificate has expired or is not yet valid'.  We have renewed those certificates and refreshed the catalog item on labs.opentlc.com.  

Can you delete the catalog service item and re-provision in labs.opentlc.com ?

Also, just an FYI, this isn't the right place to log issues with content in labs.opentlc.com.   Please use one of the methods mentioned here: https://connect.redhat.com/en/support 

Regards,

Andrew Blum
PnTAE Training
Red Hat

**Comment by ravi-kulkarni26** [comment]
@ajblum - https://connect.redhat.com/en/support 
I have raised the case against this issue. (Case Number : 02629648), As per the suggested by your team to raise a concern here! Anyway, let me retry the process & come back to you.! Thank you so much :)
