### ISSUE TITLE
"Operator SDK with Go" scenario has version problems

### ISSUE THREAD

**Issue by cziesman** [openshift-labs/learn-katacoda#717]
Following the instructions in the scenario to create the operator skeleton produces this output:
<pre>
$ operator-sdk new podset-operator --type=go --skip-git-init
INFO[0000] Creating new Go operator 'podset-operator'.
INFO[0000] Created cmd/manager/main.go
INFO[0000] Created build/Dockerfile
INFO[0000] Created build/bin/entrypoint
INFO[0000] Created build/bin/user_setup
INFO[0000] Created deploy/service_account.yaml
INFO[0000] Created deploy/role.yaml
INFO[0000] Created deploy/role_binding.yaml
INFO[0000] Created deploy/operator.yaml
INFO[0000] Created pkg/apis/apis.go
INFO[0000] Created pkg/controller/controller.go
INFO[0000] Created version/version.go
INFO[0000] Created .gitignore
INFO[0000] Created Gopkg.toml
INFO[0000] Run dep ensure ...
Root project is "github.com/redhat/podset-operator"
 4 transitively valid internal packages
 21 external packages imported from 9 projects
(0)   ✓ select (root)
(1)     ? attempt k8s.io/gengo with 1 pkgs; 1 versions to try
(1)         try k8s.io/gengo@master
(1)     ✓ select k8s.io/gengo@master w/5 pkgs
(2)     ? attempt github.com/spf13/pflag with 1 pkgs; 9 versions to try
(2)         try github.com/spf13/pflag@v1.0.5
(2)     ✓ select github.com/spf13/pflag@v1.0.5 w/1 pkgs
(3)     ? attempt k8s.io/klog with 1 pkgs; 14 versions to try
(3)         try k8s.io/klog@v2.0.0
(4)     ✗   k8s.io/klog at v2.0.0 has problem subpkg(s):
(4)             k8s.io/klog/v2 is missing; required by k8s.io/gengo@master.
(3)         try k8s.io/klog@v1.0.0
(4)     ✗   k8s.io/klog at v1.0.0 has problem subpkg(s):
(4)             k8s.io/klog/v2 is missing; required by k8s.io/gengo@master.
(3)         try k8s.io/klog@v0.4.0
(4)     ✗   k8s.io/klog at v0.4.0 has problem subpkg(s):
(4)             k8s.io/klog/v2 is missing; required by k8s.io/gengo@master.
(3)         try k8s.io/klog@v0.3.3
(4)     ✗   k8s.io/klog at v0.3.3 has problem subpkg(s):
(4)             k8s.io/klog/v2 is missing; required by k8s.io/gengo@master.
(3)         try k8s.io/klog@v0.3.2
(4)     ✗   k8s.io/klog at v0.3.2 has problem subpkg(s):
(4)             k8s.io/klog/v2 is missing; required by k8s.io/gengo@master.
(3)         try k8s.io/klog@v0.3.1
(4)     ✗   k8s.io/klog at v0.3.1 has problem subpkg(s):
(4)             k8s.io/klog/v2 is missing; required by k8s.io/gengo@master.
(3)         try k8s.io/klog@v0.3.0
(4)     ✗   k8s.io/klog at v0.3.0 has problem subpkg(s):
(4)             k8s.io/klog/v2 is missing; required by k8s.io/gengo@master.
(3)         try k8s.io/klog@v0.2.0
(4)     ✗   k8s.io/klog at v0.2.0 has problem subpkg(s):
(4)             k8s.io/klog/v2 is missing; required by k8s.io/gengo@master.
(3)         try k8s.io/klog@v0.1.0
(4)     ✗   k8s.io/klog at v0.1.0 has problem subpkg(s):
(4)             k8s.io/klog/v2 is missing; required by k8s.io/gengo@master.
(3)         try k8s.io/klog@v2.0.0-rc.1
(4)     ✗   k8s.io/klog at v2.0.0-rc.1 has problem subpkg(s):
(4)             k8s.io/klog/v2 is missing; required by k8s.io/gengo@master.
(3)         try k8s.io/klog@master
(4)     ✗   k8s.io/klog at master has problem subpkg(s):
(4)             k8s.io/klog/v2 is missing; required by k8s.io/gengo@master.
(3)         try k8s.io/klog@fix_typo
(4)     ✗   k8s.io/klog at fix_typo has problem subpkg(s):
(4)             k8s.io/klog/v2 is missing; required by k8s.io/gengo@master.
(3)         try k8s.io/klog@flag_defaults
(4)     ✗   k8s.io/klog at flag_defaults has problem subpkg(s):
(4)             k8s.io/klog/v2 is missing; required by k8s.io/gengo@master.
(3)         try k8s.io/klog@release-1.x
(4)     ✗   k8s.io/klog at release-1.x has problem subpkg(s):
(4)             k8s.io/klog/v2 is missing; required by k8s.io/gengo@master.
(3)       ← no more versions of k8s.io/klog to try; begin backtrack
(2)     ← backtrack: no more versions of github.com/spf13/pflag to try
(1)     ← backtrack: no more versions of k8s.io/gengo to try
(1)     ← backtrack: no more versions of k8s.io/gengo to try
  ✗ solving failed

Solver wall times by segment:
     b-list-versions: 9.465703503s
         b-list-pkgs: 6.735888803s
     b-source-exists: 4.118819933s
              b-gmal: 1.205845805s
  b-deduce-proj-root: 287.080904ms
             satisfy:  12.822242ms
         select-atom:   1.720456ms
            new-atom:   1.143384ms
            unselect:    995.352µs
         select-root:    961.719µs
               other:    101.719µs
           backtrack:     86.128µs

  TOTAL: 21.831169948s

Solving failure: No versions of k8s.io/klog met constraints:
        v2.0.0: Could not introduce k8s.io/klog@v2.0.0, as its subpackage k8s.io/klog/v2 is missing. (Package is required by k8s.io/gengo@master.)
        v1.0.0: Could not introduce k8s.io/klog@v1.0.0, as its subpackage k8s.io/klog/v2 is missing. (Package is required by k8s.io/gengo@master.)
        v0.4.0: Could not introduce k8s.io/klog@v0.4.0, as its subpackage k8s.io/klog/v2 is missing. (Package is required by k8s.io/gengo@master.)
        v0.3.3: Could not introduce k8s.io/klog@v0.3.3, as its subpackage k8s.io/klog/v2 is missing. (Package is required by k8s.io/gengo@master.)
        v0.3.2: Could not introduce k8s.io/klog@v0.3.2, as its subpackage k8s.io/klog/v2 is missing. (Package is required by k8s.io/gengo@master.)
        v0.3.1: Could not introduce k8s.io/klog@v0.3.1, as its subpackage k8s.io/klog/v2 is missing. (Package is required by k8s.io/gengo@master.)
        v0.3.0: Could not introduce k8s.io/klog@v0.3.0, as its subpackage k8s.io/klog/v2 is missing. (Package is required by k8s.io/gengo@master.)
        v0.2.0: Could not introduce k8s.io/klog@v0.2.0, as its subpackage k8s.io/klog/v2 is missing. (Package is required by k8s.io/gengo@master.)
        v0.1.0: Could not introduce k8s.io/klog@v0.1.0, as its subpackage k8s.io/klog/v2 is missing. (Package is required by k8s.io/gengo@master.)
        v2.0.0-rc.1: Could not introduce k8s.io/klog@v2.0.0-rc.1, as its subpackage k8s.io/klog/v2 is missing. (Package is required by k8s.io/gengo@master.)
        master: Could not introduce k8s.io/klog@master, as its subpackage k8s.io/klog/v2 is missing. (Package is required by k8s.io/gengo@master.)
        fix_typo: Could not introduce k8s.io/klog@fix_typo, as its subpackage k8s.io/klog/v2 is missing. (Package is required by k8s.io/gengo@master.)
        flag_defaults: Could not introduce k8s.io/klog@flag_defaults, as its subpackage k8s.io/klog/v2 is missing. (Package is required by k8s.io/gengo@master.)
        release-1.x: Could not introduce k8s.io/klog@release-1.x, as its subpackage k8s.io/klog/v2 is missing. (Package is required by k8s.io/gengo@master.)
Error: failed to exec []string{"dep", "ensure", "-v"}: exit status 1
Usage:
  operator-sdk new <project-name> [flags]

Flags:
      --api-version string          Kubernetes apiVersion and has a format of $GROUP_NAME/$VERSION (e.g app.example.com/v1alpha1) - used with "ansible" or "helm" types
      --cluster-scoped              Generate cluster-scoped resources instead of namespace-scoped
      --generate-playbook           Generate a playbook skeleton. (Only used for --type ansible)
      --helm-chart string           Initialize helm operator with existing helm chart (<URL>, <repo>/<name>, or local path)
      --helm-chart-repo string      Chart repository URL for the requested helm chart
      --helm-chart-version string   Specific version of the helm chart (default is latest version)
  -h, --help                        help for new
      --kind string                 Kubernetes CustomResourceDefintion kind. (e.g AppService) - used with "ansible" or "helm" types
      --skip-git-init               Do not init the directory as a git repository
      --type string                 Type of operator to initialize (choices: "go", "ansible" or "helm") (default "go")
</pre>

**Comment by madorn** [comment]
@cziesman See #707

**Comment by madorn** [comment]
@cziesman we have updated this exercise with a newer version of operator-sdk. See https://learn.openshift.com/operatorframework/go-operator-podset/

This issue can be closed. @BenHall
