### ISSUE TITLE
Lab setup at https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-6 fails

### ISSUE THREAD

**Issue by peter-hansteen-at-ibm** [openshift-labs/learn-katacoda#721]
as per the title, the lab setup at https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-6 fails, apparently due to the directory /var/lib/openshift and its content for some reason not having been created.

I really wish I had figured out a way to cut and paste text from the lab environment, I'll try attaching a screenshot that shows the last messages up to and including the failure.
![Screenshot from 2020-04-20 16-25-17](https://user-images.githubusercontent.com/64023114/79763062-d8a4e280-8323-11ea-9be3-bd44d7f7755d.png)

**Comment by btannous** [comment]
@fatherlinux 
https://github.com/openshift-labs/learn-katacoda/blob/9a4749182365dd21d79ab73ecc0f4d096e44519d/subsystems/container-internals-lab-2-0-part-6/foreground.sh#L17 : Looks like this should use `/usr/bin/oc` instead?

**Comment by btannous** [comment]
@fatherlinux checking?

**Comment by btannous** [comment]
I reached out, and Scott mentioned he will check this out in the coming week.

**Comment by fatherlinux** [comment]
That said, I don't think this affects lab 6.

**Comment by fatherlinux** [comment]
@peter-hansteen-at-ibm hey, I wanted to let you know that I fixed up the foreground script on this lab and updated the content. If you'd like check it out now and let me know what you think: https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-6

Feel free to ping me on Twitter @fatherlinux
