### ISSUE TITLE
sql-server-cstore

### ISSUE THREAD

**Issue by tcloud-ua** [openshift-labs/learn-katacoda#745]
**In what katacoda scenario did this bug occur?**
https://developers.redhat.com/courses/red-hat-enterprise-linux/sql-server-cstore/

**At what step of the scenario did this happen?**
Step 1

**Describe the bug**
The SQL Server background task fails due to missing dependencies and the lab is unable to execute the first step.

**Logs or error messages**
See screenshot below.

**Screenshots**
![sql-server-cstore-error](https://user-images.githubusercontent.com/64489607/80513524-cb4faf80-8944-11ea-9ee8-e4ce142fb7ae.png)

**Additional context**
N/A

**Comment by jankleinert** [comment]
moved to the repo where this scenario lives
