### ISSUE TITLE
containers-buildah

### ISSUE THREAD

**Issue by tcloud-ua** [openshift-labs/learn-katacoda#746]
**In what katacoda scenario did this bug occur?**
https://developers.redhat.com/courses/red-hat-enterprise-linux/containers-buildah/

**At what step of the scenario did this happen?**
Step 5

**Describe the bug**
When attempting to install httpd in the working-continer (Step 5) it throws an error. "There are no enabled repos." This prevents finishing the course.

**Logs or error messages**
See screenshot below.

**Screenshots**
![containers-buildah-error](https://user-images.githubusercontent.com/64489607/80514011-8710df00-8945-11ea-99ea-abdcf665520a.png)

**Additional context**
N/A

**Comment by jankleinert** [comment]
Moved to the repo where this scenario lives
