### ISSUE TITLE
ansible-getting-started

### ISSUE THREAD

**Issue by tcloud-ua** [openshift-labs/learn-katacoda#747]
**In what katacoda scenario did this bug occur?**
https://developers.redhat.com/courses/ansible/getting-started/

**At what step of the scenario did this happen?**
Step 2

**Describe the bug**
Ansible is not installed on control, host02, and host03.

**Logs or error messages**
See screenshot below.

**Screenshots**
![ansible-getting-started-error](https://user-images.githubusercontent.com/64489607/80514653-69904500-8946-11ea-9924-3f5584cb2831.png)

**Additional context**
N/A

**Comment by jankleinert** [comment]
moved to the repo where this scenario lives
