### ISSUE TITLE
indefinitely downloads 

### ISSUE THREAD

**Issue by ramakris** [openshift-labs/learn-katacoda#750]
https://learn.openshift.com/servicemesh/1-introduction

**Comment by btannous** [comment]
This is a duplicate of: https://github.com/openshift-labs/learn-katacoda/issues/760

Looks like issues with the init script not running, investigating it, but closing this to consolidate.  Please comment/track that one.  

Thank you!

**Comment by btannous** [comment]
see: https://github.com/openshift-labs/learn-katacoda/issues/760#issuecomment-625881686
