### ISSUE TITLE
Minor error in lab "Quarkus for Spring Boot Developers"

### ISSUE THREAD

**Issue by kgshukla** [openshift-labs/learn-katacoda#752]
Hi,

The first step in the above mentioned lab is to create maven project. The user is in the directory /root. So, the "fruit-taster" project is created in the /root directory. however, it must be created in "/root/project/quarkus" directory. Rest of the lab becomes unusable and it may be difficult for first time users to figure out the issue. 

Need to add "cd /root/project/quarkus" command as the first command in this lab.

**Comment by kgshukla** [comment]
Here is the lab url

https://learn.openshift.com/middleware/courses/middleware-quarkus/spring

**Comment by btannous** [comment]
@sshaaf @jamesfalkner I think I recall us grabbing more memory for the hosts here, but that was sometime last week, i think...
Any idea what is going on here?

**Comment by jamesfalkner** [comment]
When I start this scenario I start in the `/root/projects/quarkus` directory. 
![image](https://user-images.githubusercontent.com/861894/81425203-1e83e800-9125-11ea-84c7-fc6ceb11647d.png) and so the scenario works for me.

**Comment by sshaaf** [comment]
I am unable to reproduce this issue: 
Following is the output, quite similar to @jamesfalkner 

```
$ pwd
/root/projects/quarkus
$ ls -la
total 12
drwxr-xr-x 3 root root 4096 May 11 11:05 .
drwxr-xr-x 3 root root 4096 May 11 11:04 ..
drwxr-xr-x 4 root root 4096 May 11 11:05 fruit-taster

```

**Comment by kgshukla** [comment]
I see a different behavior here. I tested on firefox v76 (both incognito and normal modes) and chrome v81.0.4044.113 and still see that the starting directory is /root. screenshots attached. 
[quarkus_springboot_lab_screenshots.pdf](https://github.com/openshift-labs/learn-katacoda/files/4612653/quarkus_springboot_lab_screenshots.pdf)

**Comment by jamesfalkner** [comment]
Yeah that's weird - in Firefox I start in a different directory! @BenHall any ideas why different browsers cause it to start in a different directory?

I'll add a `cd` step right up front just to make sure. Thanks for reporting!
