### ISSUE TITLE
Multi-cluster GitOps with OpenShift doesn't start

### ISSUE THREAD

**Issue by proxi73** [openshift-labs/learn-katacoda#758]
The lab seems to be broken, only the Web console tab seems to work, the other tabs (Terminal, ArgoCD Server and Gogs Servers don't start the applications

**Comment by btannous** [comment]
@mvazquezc do you mind taking a look?

**Comment by mvazquezc** [comment]
@BenHall It seems contents from assets folder are not being copied over the VM instance: 

https://github.com/openshift-labs/learn-katacoda/tree/master/introduction/gitops-introduction/assets

Has anything changed wrt copying assets to envs?

**Comment by BenHall** [comment]
@mvazquezc Let me check

**Comment by mvazquezc** [comment]
@BenHall any news on this?

**Comment by proxi73** [comment]
Hello, any news? I'm trying to access but I always fall into the same issue.
thanks

**Comment by BenHall** [comment]
We are currently testing a fix. I will update when it's live.

**Comment by btannous** [comment]
I might have ran into a similar problem.   It seems that the script might run before some assets are copied over.
I placed a workaround in my script to wait for the files:
https://github.com/btannous/learn-katacoda/blob/ffcfefd4231b5d0fdcd965ff531255faaade489e/middleware/serverless/set-env.sh#L3-L7
(might be useful @mvazquezc )

**Comment by mvazquezc** [comment]
@btannous thanks for the pointer. We have a similar solution in place:

https://github.com/openshift-labs/learn-katacoda/blob/master/introduction/gitops-multicluster/set-env.sh#L11

@BenHall do you have an ETA for the fix?

Thanks,

**Comment by BenHall** [comment]
@mvazquezc The fix should be live

**Comment by mvazquezc** [comment]
@proxi73 The fix is live as Ben said. Let us know if you need anything else.

**Comment by btannous** [comment]
Closing this.  Please reopen or create a new issue and reference this one if the issue still persists.
