### ISSUE TITLE
Potential security issue regarding internet access

### ISSUE THREAD

**Issue by mazzystr** [openshift-labs/learn-katacoda#765]
Hello,
I was able to install the KubeVirt community product into the OpenShift 4.2 playground by applying yaml's directly from the internet 

This begs the question what else can be installed into the playground environment.

**Comment by btannous** [comment]
I’d go as far to say that this is by design.

The environments are ephemeral and unique to your instance.
They go away when you close the tab.
They also only are allowed to be ran for an hour and have limited resources available.

**Comment by BenHall** [comment]
Thanks for bringing this up. Yes, this is intentional and by design.
