### ISSUE TITLE
Some issues with the Openshift Pipeline Course

### ISSUE THREAD

**Issue by gbenhaim** [openshift-labs/learn-katacoda#786]
1. The example describes the usage of `PipelineResources` even though it's discouraged https://github.com/tektoncd/pipeline/blob/master/docs/migrating-v1alpha1-to-v1beta1.md#replacing-pipelineresources-with-tasks

2. Step 6 - It was stated that the pipeline should be generic and reusable, but the name of the DeploymentConfig was hardcoded in it.

3. Step 6 - `oc rollout latest nodejs-ex` the explanation of this step can be a bit misleading, 

```
This command deploys an image called nodejs-ex that has the tag latest associated with it, meaning the most recently pushed version of the image.
```
It will fetch the latest image that was tagged into the image stream, with the tag that was referenced in the DC, in our case it's the `latest` tag, but it's not always true.

**Comment by jankleinert** [comment]
@joellord can you take a look please?

**Comment by joellord** [comment]
OpenShift Pipelines still uses version v1alpha1, which uses PipelineResources. 

The suggested changes will be kept in mind when the new version comes out.

Thank you for your feedback!

**Comment by joellord** [comment]
Lab will be updated soon, closing this issue for now.
