### ISSUE TITLE
Podman doesn't show the base image id on history.

### ISSUE THREAD

**Issue by Saurabh-tcs** [openshift-labs/learn-katacoda#789]
Course - https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-2
Fact-   Notice that that the first image ID (bottom) listed in the output matches the
--- below is the output of podman history --- 

D             CREATED         CREATED BY                                      SIZE      COMMENT
de97a63953fb   4 minutes ago   /bin/sh -c echo "Hello world" > /tmp/newfile5   165B
<missing>      4 minutes ago   /bin/sh -c echo "Hello world" > /tmp/newfile4   2.56kB
<missing>      4 minutes ago   /bin/sh -c echo "Hello world" > /tmp/newfile3   2.56kB
<missing>      4 minutes ago   /bin/sh -c echo "Hello world" > /tmp/newfile2   2.56kB
<missing>      4 minutes ago   /bin/sh -c echo "Hello world" > /tmp/newfile    3.584kB
<missing>      4 minutes ago   /bin/sh -c #(nop) MAINTAINER scott.mccarty...   3.584kB
<missing>      3 weeks ago                                                     20.48kB
<missing>      3 weeks ago                                                     215.3MB   Imported from -

**Comment by fatherlinux** [comment]
This is a bug in Podman 1.6.4 and is fixed in newer versions.

**Comment by ryanj** [comment]
Thanks for reporting - This should be fixed now
