### ISSUE TITLE
Prometheus deployment update fails in introduction scenario

### ISSUE THREAD

**Issue by saifshaikh48** [openshift-labs/learn-katacoda#800]
In Step 2 of [Deploying Prometheus and Grafana on OpenShift](https://learn.openshift.com/introduction/deploy-prometheus-grafana/), under the _Deploy Prometheus with new configuration_ subheading, the user is told to "Update the Prometheus deployment using the following command:
 `oc rollout latest dc/prometheus-demo -n pad-monitoring`"

The following error prevents the user from proceeding: 
`Error from server (NotFound): deploymentconfigs.apps.openshift.io "prometheus-demo" not found`

**Comment by jankleinert** [comment]
@4n4nd can you take a look at this please?

**Comment by rbaumgar** [comment]
see #817

**Comment by joshix** [comment]
Duplicated by #817 and #820. Fix in #829.
