### ISSUE TITLE
Operator Workshop - June 25 and 26, 2020

### ISSUE THREAD

**Issue by mrhillsman** [openshift-labs/learn-katacoda#801]
Operator Workshop - June 25 and 26, 2020
7am to 5pm Central Time.
50 attendees

Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

Environments will need to be on 4.2.

@BenHall
@madorn

**Comment by mrhillsman** [comment]
@BenHall I put the wrong dates, apologies, dates have been corrected

**Comment by BenHall** [comment]
@mrhillsman Thanks, we'll get this ready and scheduled

**Comment by BenHall** [comment]
This has been scheduled.

Thursday 25-06-2020 at 12:00 UTC until Thursday 25-06-2020 at 22:00 UTC

Number of expected attendees: 50

Environment: openshift-4-2

---

Friday 26-06-2020 at 12:00 UTC until Friday 26-06-2020 at 22:00 UTC

Number of expected attendees: 50

Environment: openshift-4-2
