### ISSUE TITLE
Prometheus / Grafana Learning-module - Provisioning doesn't work

### ISSUE THREAD

**Issue by skraft-redhat** [openshift-labs/learn-katacoda#817]
Hello!

The provisioning doesn't seem to work, obviously there are some error messages as objects can't be created (unfortunately, the error message just appear very short-term)

=> the consequence is that in step ("oc rollout latest dc/promotheus-demo -n pad-monitoring") on Step 2/4, an error message is displayed 

Thanks for checking & fixing!

BR,
Stephan

**Comment by rbaumgar** [comment]
as a workaround deploy Prometheus by hand after provisioning

``` 
oc process -f /home/scrapbook/tutorial/deploy-prometheus.yaml | oc apply -n pad-monitoring -f -
```

**Comment by joshix** [comment]
duplicates #800
