### ISSUE TITLE
Operator Workshop - July 16 and 17, 2020

### ISSUE THREAD

**Issue by mrhillsman** [openshift-labs/learn-katacoda#823]
Operator Workshop - July 16 and 17, 2020
8am to 5pm Central Time.
40 attendees

Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

Environments will need to be on 4.4

@BenHall
@madorn

**Comment by BenHall** [comment]
Thursday 16-07-2020 at 13:00 UTC until Thursday 16-07-2020 at 22:00 UTC

Number of expected attendees: 30

Environment: openshift-4-4

---

Friday 17-07-2020 at 13:00 UTC until Friday 17-07-2020 at 22:00 UTC

Number of expected attendees: 30

Environment: openshift-4-4
