### ISSUE TITLE
Operator Workshop - July 30 and 31, 2020

### ISSUE THREAD

**Issue by mrhillsman** [openshift-labs/learn-katacoda#824]
Operator Workshop - July 30 and 31, 2020
8am to 5pm Central Time.
30 attendees

Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

Environments will need to be on 4.4

@BenHall
@madorn

**Comment by BenHall** [comment]
Thursday 30-07-2020 at 13:00 UTC until Thursday 30-07-2020 at 22:00 UTC

Number of expected attendees: 30

Environment: openshift-4-4

---

Friday 31-07-2020 at 13:00 UTC until Friday 31-07-2020 at 22:00 UTC

Number of expected attendees: 30

Environment: openshift-4-4
