### ISSUE TITLE
OLM scenerio is outdated and does not work

### ISSUE THREAD

**Issue by dlbewley** [openshift-labs/learn-katacoda#831]
https://learn.openshift.com/operatorframework/operator-lifecycle-manager/

Things begin to malfunction at step 2 of the scenario.

It should be updated or pulled down.

**Comment by jankleinert** [comment]
@madorn Can you take a look please?

**Comment by btannous** [comment]
Fixed via https://github.com/openshift-labs/learn-katacoda/pull/835
