### ISSUE TITLE
Summit Lab - Building Kubernetes Operators with Ansible - Tuesday, July 14, 2230 UTC to 0230 UTC July 15th

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#833]
Operator Workshop - Tuesday, July 14, 2230 UTC to 0230 UTC July 15th
100 attendees

Environments will need to be on 4.4

@BenHall
@mrhillsman
@mhrivnak
@chris-short

**Comment by BenHall** [comment]
Done

Tuesday 14-07-2020 at 22:30 UTC until Wednesday 15-07-2020 at 02:30 UTC

Number of expected attendees: 100

Environment: openshift-4-4


FYI: It looks like one of the environments in the pathway is still using 4.2
