### ISSUE TITLE
Summit Lab - Building Kubernetes Operators with Ansible - Wednesday, July 15, 15:30 UTC to 1930 UTC

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#834]
Operator Workshop - Wednesday, July 15, 15:30 UTC to 1930 UTC
100 attendees

Environments will need to be on 4.4

@BenHall
@mrhillsman
@mhrivnak
@chris-short

**Comment by BenHall** [comment]
Wednesday 15-07-2020 at 15:30 UTC until Wednesday 15-07-2020 at 19:30 UTC

Number of expected attendees: 100

Environment: openshift-4-4
