### ISSUE TITLE
Service Mesh Scenario 1 with no available disk capacity 

### ISSUE THREAD

**Issue by jack17529** [openshift-labs/learn-katacoda#841]
I refreshed several times but it did not work.  
https://www.katacoda.com/openshift/courses/servicemesh/1-introduction  

```
Oops! Sorry, we had a problem. Please refresh and try again.
Error - Not enough disk capacity available: 0
We are sorry but we encountered a problem with the connection.
Please refresh and try again.
```

**Comment by btannous** [comment]
Thank you for the report.  Closing as this seems to have been a service availability issue and the scenario at https://learn.openshift.com/servicemesh/1-introduction is working for me. 
Please let us know if it still is acting up on your end.  Thank you!
