### ISSUE TITLE
Login into web console not possible

### ISSUE THREAD

**Issue by panomarix** [openshift-labs/learn-katacoda#842]
Hi, 

I am currently doing the openshift training. 
The oc client is working but as soon as I am waked to use the web console; I can add the user name and password.
But then I get an error.

Is this training unavailable?

used training: https://learn.openshift.com/introduction/cluster-access

regards

Frank

**Comment by jankleinert** [comment]
@BenHall I was able to reproduce this. This seems to be happening for multiple scenarios that are based on the 4.4 image. Can you take a look please and see what might be going wrong?

**Comment by BenHall** [comment]
@jankleinert Taking a look. The certificate rotation started this morning so might be related.

**Comment by BenHall** [comment]
@jankleinert I'm unable to reproduce this. I wonder if there were some old nodes still left that hadn't been removed correctly this morning so the certificates had expired and where still running so not renewed.

Could you try again please? If you continue to see an issue, can you provide the full URL for the console you are accessing to help us debug.

**Comment by BenHall** [comment]
We deployed a fix yesterday which appears to have corrected this issue that was related to a timing bug.
