### ISSUE TITLE
Not able to login to Openshift console using "Developer" account

### ISSUE THREAD

**Issue by Ganesh0412** [openshift-labs/learn-katacoda#843]
I am trying to login to openshift console url from below course using "developer" account,  but it is automatically getting logout everytime.

**COURSE LINK:** https://learn.openshift.com/introduction/getting-started

**Openshift console url:** https://oauth-openshift-2886795280-443-host19nc.environments.katacoda.com/login?then=%2Foauth%2Fauthorize%3Fclient_id%3Dconsole%26redirect_uri%3Dhttps%253A%252F%252Fconsole-openshift-console-2886795280-443-host19nc.environments.katacoda.com%252Fauth%252Fcallback%26response_type%3Dcode%26scope%3Duser%253Afull%26state%3D7fccbe0c

**Comment by BenHall** [comment]
We deployed a fix yesterday which appears to have corrected this issue that was related to a timing bug. If you could please retry that would be great.

**Comment by Ganesh0412** [comment]
Thanks @BenHall its working now
