### ISSUE TITLE
Can not complete the S2I python lab of creating the django blog app deployment due to error

### ISSUE THREAD

**Issue by jarcher** [openshift-labs/learn-katacoda#849]
![image](https://user-images.githubusercontent.com/190277/89677627-68f73b00-d8b3-11ea-8583-d2efa433ac6a.png)

Danger alert:An error occurred
Error "Forbidden: this image is prohibited by policy: this image is prohibited by policy (changed after admission)" for field "spec.template.spec.containers[0].image".

**Comment by btannous** [comment]
I also cannot reproduce this.  Please confirm and reopen the issue if it is still on going.  
Thank you!
