### ISSUE TITLE
Receiving error: "Could not check CSRF token. Please try again."

### ISSUE THREAD

**Issue by dshays** [openshift-labs/learn-katacoda#850]
In topic 3, when attempting to login to the web console, the following error is given and login is denied:
"Could not check CSRF token. Please try again."

Unable to access web console to complete lab.

**Comment by BenHall** [comment]
Thank you for reporting. We are investigating a fix for this due to same site cookies issues in the browser.

**Comment by btannous** [comment]
Closing as this seems to be OK on my end.  Please let me know if the issue is ongoing by reopening the issue.
