### ISSUE TITLE
Operator Workshop - August 18 and 19, 2020

### ISSUE THREAD

**Issue by mrhillsman** [openshift-labs/learn-katacoda#851]
Operator Workshop - August 18 and 19, 2020
8am to 5pm Central Time.
25 attendees

Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

Environments will need to be on 4.4

@BenHall
@madorn

**Comment by BenHall** [comment]
This has been completed:

Wednesday 18-08-2020 at 13:00 UTC until Wednesday 19-08-2020 at 22:00 UTC

Wednesday 19-08-2020 at 13:00 UTC until Wednesday 19-08-2020 at 22:00 UTC
