### ISSUE TITLE
Guide doesn't match OpenShift Option

### ISSUE THREAD

**Issue by NikolasKomonen** [openshift-labs/learn-katacoda#853]
I'm on the introduction tutorial: https://learn.openshift.com/introduction/getting-started/

On Step 4, 'Application "Self Healing"', there is an 'Actions' dropdown menu that is out of date.

**Comment by btannous** [comment]
Hey!
Thank you for the issue.  I think that you might have missed a step.
`On the Resources tab where you viewed the list of pods after scaling to 2 replicas, open one of the pods by clicking its name in the list.`

If you click the action menu for the deployment you can see the menu is quite a bit larger, but the action menu for one of the pods matches the screenshot, therefore I am going to close this issue.

Please re-open if I have missed something! Thank you again!
