### ISSUE TITLE
Use reliable katacoda instance for Webinar

### ISSUE THREAD

**Issue by jwerak** [openshift-labs/learn-katacoda#863]
I will be delivering webinar using live Katacoda demos, namely https://learn.openshift.com/ansibleop/ansible-k8s-modules/ and https://learn.openshift.com/ansibleop/ansible-operator-overview/.

The demo will be on August 27th between 9:00 - 10:00 AM UTC. 

What can I do to ensure reliable katacoda environment/instance?

**Comment by jankleinert** [comment]
@BenHall

**Comment by btannous** [comment]
Closing as this is now over.
