### ISSUE TITLE
Operator Workshop - September 2 and 3, 2020

### ISSUE THREAD

**Issue by mrhillsman** [openshift-labs/learn-katacoda#867]
Operator Workshop - September 2 and 3, 2020
8am to 5pm Central Time.
20 attendees

Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

Environments will need to be on 4.4

@BenHall
@madorn

**Comment by mrhillsman** [comment]
Bump

@BenHall

**Comment by gsoria** [comment]
Hi folks!, 👋   This has been completed.

Pathway file: _operatorframework-pathway.json_, 20 attendees for each workshop:

- Wednesday 02-09-2020 at 13:00 UTC until Wednesday 02-09-2020 at 22:00 UTC
- Thursday 03-09-2020 at 13:00 UTC until Thursday 03-09-2020 at 22:00 UTC

**Comment by mrhillsman** [comment]
Thanks @gsoria
