### ISSUE TITLE
On the "Transferring Files in and out of Containers" creating variables line has an error

### ISSUE THREAD

**Issue by navarq** [openshift-labs/learn-katacoda#870]
to create a POD variable in interactive shell use:
```{sh shell}
export $POD='<command goes here>'
```

The command mistakenly uses 
```
$POD='...'
```

Which is alright for shell scripts but not here

**Comment by btannous** [comment]
Hey! Thank you for the report. 
Where is this not working in this scenario specifically?

Doing this in bash is ok
```bash
POD=bar
echo $POD
```

doing something like this is not (which I don't believe we are doing) and should not work
```bash
echo "echo ${FOO}" > script.sh
chmod +x script.sh
FOO=bar
./script.sh
```

but doing something like this would work
```bash
echo "echo ${FOO}" > script.sh
chmod +x script.sh
export FOO=bar
./script.sh
```

But in the scenario I only see the first case.

**Comment by navarq** [comment]
Using Openshift 
on the above mentioned tutorial 
Transferring Files in and out of Containers
`It is on step 2" 
1/2 way down approxiate

**Comment by btannous** [comment]
The use of the POD variable is OK in this situation and those specific steps work for me running through the scenario.
