### ISSUE TITLE
Workshop - Sep 16 & Sep 17 - 9 am EST to 6 PM EST

### ISSUE THREAD

**Issue by nmalvankar** [openshift-labs/learn-katacoda#874]
Hi @BenHall, 
I will be hosting all day sessions on Sep 16th & Sep 17th - 9 am EST to 6 PM EST and would use the below scenarios. Please ensure that this can support up to 60 users.   

We would also like to have this environment available on Sep 14th - 12 PM EST to 1 PM EST for a dry run if thats possible. 

**Using Openshift** 
- Logging in to an Openshift Cluster
-  Transferring Files in and out of Containers 
- Deploying Applications from Images

**Developing on Openshift**  

- Getting Started with Openshift for Developers 
- Deploying Applications from Source 
- Getting Started with Helm 3 on Openshift
-  Getting Started with OpenShift Serverless 

**Enterprise Java Development** 

**Developing with Quarkus** 

**Developing with Spring and SpringBoot** 

**CI/CD & Application Delivery**

- Introduction to GitOps with Openshift

**Adding Persistence to OpenShift** 

- Making Persistent Storage Calls in your Application

**AI and ML on OpenShift**
- Deploying a Jupyter Notebook Image

Please let me know if you require any further details. Thanks for your help!

Regards,
Nikhil Malvankar

**Comment by jankleinert** [comment]
@BenHall

**Comment by jankleinert** [comment]
I'll enter this via the katacoda admin interface. Per an update from Nikhil today, the env is needed for the dry run Sept 14 from noon - 1pm ET and Sept 17 from 8:30am - 6:00pm ET

**Comment by jankleinert** [comment]
Closing since this has been entered through the admin interface.
