### ISSUE TITLE
Deploying Prometheus and Grafana on OpenShift - Can't log in to Grafana interface

### ISSUE THREAD

**Issue by oveee92** [openshift-labs/learn-katacoda#881]
When following the lab Deploying Prometheus and Grafana on OpenShift, I try to log into the Grafana interface with admin/admin. The tutorial says to skip changing the password for now, but clicking skip directs me back to the initial login. Trying to change the password gives me an "Unauthorized" error.

Identical results on Chrome and Firefox.

Logs from grafana after trying to skip changing password.
```
t=2020-09-20T09:54:07+0000 lvl=info msg="Successful Login" logger=http.server User=admin@localhost
t=2020-09-20T09:54:09+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=35.198.154.152 time_ms=0 size=29 referer=http://grafana-pad-monitoring.2886795288-80-kota01.environments.katacoda.com/login
```

**Comment by btannous** [comment]
I don't experience this issue here, clicking skip seems to take me to the grafana console. 

do you mind trying again? maybe trying an incognito window? possibly some other localized issue?

please reopen this if you still cannot access for some reason.
