### ISSUE TITLE
Developing with Odo 311 asset dir incorrect

### ISSUE THREAD

**Issue by jboxman** [openshift-labs/learn-katacoda#889]
```
./introduction/developing-with-odo-311/06-making-changes-to-source-code.md:![Application Title](../../assets/introduction/developing-with-odo/app-name.png)
```

The link isn't correct. The updated asset directory appears to be:

```
ls assets/introduction/developing-with-odo-*
assets/introduction/developing-with-odo-311:
app-name.png          membership.png        view-membership.png
frontend-console.png  okd-login.png
```

**Comment by btannous** [comment]
this scenario is old and unsupported.
curious as to how did you found it?

https://learn.openshift.com/introduction/developing-with-odo/ is the current version. please try that.

**Comment by jboxman** [comment]
@btannous cloned the repo, was experimenting with building locally so I can just consume the scenarios without interactivity.
