### ISSUE TITLE
Getting Started with JBoss EAP on OpenShift: SessionScoped country always "en"

### ISSUE THREAD

**Issue by sharpedavid** [openshift-labs/learn-katacoda#890]
I'm working on the tutorial "Getting Started with JBoss EAP on OpenShift" at https://learn.openshift.com/middleware/middleware-javaee8/. I'm on step 4, "Basics of CDI". The `SelectedCountry` SessionScoped bean doesn't seem to be working.

The tutorial is overall excellent so I really hope it can be fixed so that I can refer it to my teammates.

**You should be able to reproduce the issue simply by following the tutorial. I've reproduced it twice.**

When I click a country flag in the web app, it always returns the data for England. I can see that the country code is in the PUT request, but the API always returns England.

![image](https://user-images.githubusercontent.com/1767127/94387645-9f0caa80-00ff-11eb-94b3-d66280dfc4bb.png)

I added some `System.out` statements to the Java beans. With them, I can see that `SelectedCountry` is called and the country I selected is set (`fr` or `us`), but when the bean is injected in `WeatherService` it always get the default value `en` (England).

Here are the relevant files. I've compared them to the [solution branch](https://github.com/tqvarnst/weather-app/tree/solution), and they look the same. The only changes I made were to add the `System.out` statements.

```java
package com.redhat.example.weather;

import javax.enterprise.context.SessionScoped;
import java.io.Serializable;

@SessionScoped
public class SelectedCountry implements Serializable {

    private String code = "en";

    public String getCode() {
        System.out.println("Getting code: " + code);
        return code;
    }

    public void setCode(String code) {
        // **** Here I can see the country I selected is set!
        System.out.println("Setting code: " + code);
        this.code = code;
    }
}
```

```java
package com.redhat.example.weather;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import java.util.Arrays;

@RequestScoped
@Path("weather")
public class WeatherService {

    @Inject
    SelectedCountry selectedCountry;

    @PersistenceContext(unitName = "primary")
    EntityManager em;

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public Country getList() {
        // **** This always returns "en"!
        System.out.println("Country getList(): " + selectedCountry.getCode());
        return em.find(Country.class,selectedCountry.getCode());
    }
}
```

```java
package com.redhat.example.weather;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;

@RequestScoped
@Path("country")
public class CountryService {

    @Inject
    SelectedCountry selectedCountry;

    @PUT
    @Path("/{code}")
    public void setSelectedCountry(@PathParam("code") String countryCode) {
        System.out.println("setSelectedCountry(): " + countryCode);
        selectedCountry.setCode(countryCode);
    }
}
```

In the logs I see the following messages:

```txt
  | 03:20:09,092 INFO  [stdout] (default task-1) setSelectedCountry(): fr
  | 03:20:09,093 INFO  [stdout] (default task-1) Setting code: fr
  | 03:20:09,438 INFO  [stdout] (default task-1) Getting code: en
  | 03:20:09,438 INFO  [stdout] (default task-1) Country getList(): en
  | 03:20:09,439 INFO  [stdout] (default task-1) Getting code: en
  | 03:20:09,441 INFO  [stdout] (default task-1) Hibernate: select country0_.id as id1_1_0_, country0_.name as name2_1_0_, cities1_.Country_id as Country_1_2_1_, city2_.id as cities_i2_2_1_, city2_.id as id1_0_2_, city2_.humidity as humidity2_0_2_, city2_.maxTemp as maxTemp3_0_2_, city2_.minTemp as minTemp4_0_2_, city2_.name as name5_0_2_, city2_.temp as temp6_0_2_, city2_.tempFeelsLike as tempFeel7_0_2_, city2_.weatherType as weatherT8_0_2_, city2_.wind as wind9_0_2_ from Country country0_ left outer join Country_City cities1_ on country0_.id=cities1_.Country_id left outer join City city2_ on cities1_.cities_id=city2_.id where country0_.id=?
```

If I complete the tutorial by adding Postgres, the problem remains.

Don't take my word for it, take _six minutes_ to walk through the tutorial at https://learn.openshift.com/middleware/middleware-javaee8/.

**Comment by sharpedavid** [comment]
I realized the problem and fixed it locally. There is an issue in the tutorial and in the source code. See the mentioned issue for details.

**Comment by btannous** [comment]
thank you for the report!

**Comment by jamesfalkner** [comment]
Can you try it with the latest revision of the scenario: https://learn.openshift.com/middleware/middleware-javaee8/ - when I run through it with Chrome (latest) it seems to work as expected.

**Comment by sharpedavid** [comment]
Thanks @jamesfalkner, but I don't have time to spend on this. I'll close the issue. I'm glad to hear it's working now.
