### ISSUE TITLE
operator version old, some files not being created like in the tutorial in version 1.0

### ISSUE THREAD

**Issue by michael-niemand** [openshift-labs/learn-katacoda#892]
When running the tutorial, in step 5 the text says:

deploy | Contains a generic set of Kubernetes manifests for deploying this operator on a Kubernetes cluster.

the version of the operator-sdk in the tutorial seems to do that (0.15) but the current version offered for download (1.0) does not create those files.

**Comment by btannous** [comment]
hey Michael. good point.  We have some that are working on updating these scenarios to use the newer versions of the operator-sdk

cc @madorn

**Comment by dlbewley** [comment]
The outdated operator-sdk version is breaking other labs as well, such as ansible-operator-overview step 5.

**Comment by madorn** [comment]
@dlbewley @btannous 

There is currently a but that is preventing the labs from utilizing the environment file (includes op-sdk 1.0.1).

https://github.com/openshift-labs/learn-katacoda/blob/master/environments/openshift-4-5/client/build/3_op-sdk-setup.sh

@btannous is tracking.

**Comment by cedricclyburn** [comment]
Hello all, closing due to the operator now being on v1.5.2 generally and 1.9 where needed. Thank you for the report!
