### ISSUE TITLE
Environment expired after repeated attempts

### ISSUE THREAD

**Issue by BPMNhero** [openshift-labs/learn-katacoda#896]
I have been trying to use the:
Linux Container Internals 2.0 - Lab 5: Container Orchestration
exercise. This environment continually tells me this error:
"The environment has expired.

Please refresh to get a new environment."

I think something is broken.
Thanks,
M. Renner

**Comment by btannous** [comment]
please try again and let us know if you have any issues still.  looks like the capacity issue is resolved as of now for me at least.

**Comment by fatherlinux** [comment]
@BPMNhero Thanks for reporting the bug, I've actually made the lab more efficient by caching the image and not forcing the user to rebuild the whole supply chain in two different labs. I think this might help with the resource challenges. I'd like to invite you back to check out the new version: https://learn.openshift.com/subsystems/container-internals-lab-2-0-part-5
