### ISSUE TITLE
developing-with-odo v2.0 binary and content update

### ISSUE THREAD

**Issue by ryanj** [openshift-labs/learn-katacoda#897]
TODO:

- [x] update odo scenario to use openshift-4-5 base environment
- [x] update example commands (add `--s2i`)
- [x] update screenshots for 4.5
- [x] Make all of these changes to a copy (?)
    * keep an unaltered copy of the existing v1 content, make sure to hide it (after v2 is published)

**Comment by btannous** [comment]
odo 2.0 should now be included in the 4.5 image.

**Comment by ryanj** [comment]
yep.  Works well.  I have a branch I'm working in.  Mostly just need updated screenshots...
