### ISSUE TITLE
No nodes available

### ISSUE THREAD

**Issue by debrajbh** [openshift-labs/learn-katacoda#898]
When opening the URL https://learn.openshift.com/introduction/federated-clusters/ to learn "Introduction to Federated Clusters with Kubefed", I am always getting the below message:

We are currently at capacity with no additional nodes available. Please check back in 10 minutes.

**Comment by sfrevel** [comment]
I get a similar message with https://learn.openshift.com/introduction/gitops-multicluster/

**Comment by btannous** [comment]
This appears be resolved. Can you please confirm?

**Comment by debrajbh** [comment]
Hi Brian,
The issue is resolved now.

Thanks & regards,
Debraj Bhowmik

**Comment by btannous** [comment]
Thank you! Sorry for the issues. :)
