### ISSUE TITLE
gitops-multicluster in CICD & Application Delivery pathway does not start

### ISSUE THREAD

**Issue by sfrevel** [openshift-labs/learn-katacoda#902]
**In what katacoda scenario did this bug occur?**
https://github.com/openshift-labs/learn-katacoda/blob/master/cicd-application-delivery-pathway.json

https://learn.openshift.com/introduction/gitops-multicluster/

**At what step of the scenario did this happen?**
just press "Start Scenario" and the environment does not start - takes a while until the start process is interrupted with the following message

```
Your Interactive Learning Environment Bash Terminal

We are sorry but we encountered a problem with the connection.
Please refresh and try again.
Tue Oct 13 2020 11:02:15 GMT+0200 (Central European Summer Time)
io server disconnect
```

**Describe the bug**
see above

**Logs or error messages**
none

**Screenshots**
none

**Additional context**
none

**Comment by ryanj** [comment]
Thanks for reporting! 
We have removed this scenario from our site index in favor of newer content (available here): https://learn.openshift.com/gitops
