### ISSUE TITLE
Operator Workshop - October 19 - 22, 2020

### ISSUE THREAD

**Issue by mrhillsman** [openshift-labs/learn-katacoda#903]
Operator Workshop - October 19 - 22, 2020
6am to 12pm Central Time.
60 attendees

Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

Environments will need to be on 4.4

@BenHall
@madorn

**Comment by madorn** [comment]
We will put submitting a PR to update the Operator Framework exercises in a few days. 

This workshop should be on the new content in this PR.

Stand by. Thanks.

@mrhillsman @btannous @BenHall

**Comment by btannous** [comment]
@jdob

**Comment by gsoria** [comment]
Hi folks!, 👋   the workshops are scheduled:

Pathway file: operatorframework-pathway.json, environment: openshift-4-4, 60 attendees for each one:

- Monday 19-10-2020 at 12:00 UTC until Monday 19-10-2020 at 18:00 UTC
- Tuesday 20-10-2020 at 12:00 UTC until Tuesday 20-10-2020 at 18:00 UTC
- Wednesday 21-10-2020 at 12:00 UTC until Wednesday 21-10-2020 at 18:00 UTC
- Thursday 22-10-2020 at 12:00 UTC until Thursday 22-10-2020 at 18:00 UTC

**Comment by mrhillsman** [comment]
thx @gsoria
