### ISSUE TITLE
Unable to open OpenShift terminal

### ISSUE THREAD

**Issue by Rasika-Deodhar** [openshift-labs/learn-katacoda#904]
Unable to open OpenShift free terminal provided - shows the following message. Tried reloading the page many times, still no progress. What to do? KIndly help. Thanks

Your Interactive Learning Environment Bash Terminal

We are currently at capacity with no additional nodes available. Please check back in 10 minutes.

**Comment by btannous** [comment]
Hi thank you for the report, which lab is this?

**Comment by jonhorton** [comment]
We also experienced this today on the Service Mesh katacoda. It's resolved now, but heads up that it happened.

**Comment by bsteffensmeier** [comment]
I am experiencing this problem on "Linux Container Internals 2.0 - Lab 1: Introduction to Containers". After many refreshes over a few days I always get the message: "We are currently at capacity with no additional nodes available. Please check back in 10 minutes."

**Comment by ryanj** [comment]
Closing this ticket. Feel free to open another if you hit the same issue
