### ISSUE TITLE
olm web console oauth URL uses inaccessible console-openshift-console.apps-crc.testing

### ISSUE THREAD

**Issue by dlbewley** [openshift-labs/learn-katacoda#909]
**In what katacoda scenario did this bug occur?**
OLM lab https://learn.openshift.com/operatorframework/operator-lifecycle-manager/

**At what step of the scenario did this happen?**
Step 3

**Describe the bug**
Opening the console as instructed takes one to eg https://console-openshift-console-2886795288-443-host01nc.environments.katacoda.com/

The console draws then attempts to redirect the browser to authenticate. 

The OAuth URL is invalid (can not be resolved in DNS) https://console-openshift-console.apps-crc.testing/auth/login

**Additional context**
It is not possible to perform Step3 given above issue.

**Comment by dlbewley** [comment]
Upon refreshing my expired environment this issue was no longer experienced.

Perhaps there is an inconsistency in the provisioning process?

**Comment by btannous** [comment]
It's possible an issue came from some provisioning error. Please let is know if you have any other issues! thank you!
