### ISSUE TITLE
Operator SDK with Go: Error: unknown command "init" for "operator-sdk"

### ISSUE THREAD

**Issue by dometdemont** [openshift-labs/learn-katacoda#911]
The 'Operator SDK with Go' scenario suggests a failing command in step 1:

$ operator-sdk init --domain=example.com --repo=github.com/redhat/podset-operator
Error: unknown command "init" for "operator-sdk"
Run 'operator-sdk --help' for usage.

**Comment by worsco** [comment]
Indeed and confirming.

The operator-sdk version in the Terminal does not have an "init" command:
```
$ operator-sdk version
operator-sdk version: "v0.15.2", commit: "ffaf278993c8fcb00c6f527c9f20091eb8dd3352", go version: "go1.13.3 linux/amd64"
$ which operator-sdk
/root/tutorial/go/bin/operator-sdk
```

```
$ operator-sdk --help
An SDK for building operators with ease

Usage:
  operator-sdk [command]

Available Commands:
  add             Adds a controller or resource to the project
  build           Compiles code and builds artifacts
  bundle          Work with operator bundle metadata and bundle images
  cleanup         Delete and clean up after a running Operator
  completion      Generators for shell completions
  generate        Invokes a specific generator
  help            Help about any command
  migrate         Adds source code to an operator
  new             Creates a new operator application
  olm             Manage the Operator Lifecycle Manager installation in your cluster
  print-deps      Print Golang packages and versions required to run the operator
  run             Run an Operator in a variety of environments
  scorecard       Run scorecard tests
  test            Tests the operator
  version         Prints the version of operator-sdk

Flags:
  -h, --help      help for operator-sdk
      --verbose   Enable verbose logging

Use "operator-sdk [command] --help" for more information about a command.
```

**Comment by worsco** [comment]
The operator-sdk is now release version v1.1.0:
  https://github.com/operator-framework/operator-sdk/releases

This issue mentions that someone is updating/rewriting the Operator-SDK lab.
  https://github.com/openshift-labs/learn-katacoda/issues/892

**Comment by worsco** [comment]
Meanwhile, if you still want to learn the latest operator-sdk +1.0 with helm:
  https://sdk.operatorframework.io/docs/building-operators/helm/tutorial/

And with golang:
  https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/

**Comment by madorn** [comment]
@worsco @dometdemont 

There is currently a bug that is preventing the labs from utilizing the environment file (includes op-sdk 1.0.1).

https://github.com/openshift-labs/learn-katacoda/blob/master/environments/openshift-4-5/client/build/3_op-sdk-setup.sh

@btannous is tracking.

**Comment by madorn** [comment]
This issue should now be resolved @worsco , thanks!
