### ISSUE TITLE
Operator Workshop - October 27 - 30, 2020

### ISSUE THREAD

**Issue by mrhillsman** [openshift-labs/learn-katacoda#918]
Operator Workshop - October 27 - 30, 2020
7am to 12pm Central Time.
60 attendees

Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

Environments will need to be on 4.4

@BenHall
@gsoria 
@madorn

**Comment by mrhillsman** [comment]
Bumping this; apologies for the late request as I was out a few days sick and got behind. @gsoria

**Comment by keg** [comment]
Hello, the workshops have been scheduled.

Pathway file: operatorframework-pathway.json, environment: openshift-4-4, 60 attendees for each:

- Tuesday Oct 27th 11:00 UTC - 17:00 UTC
- Wednesday Oct 28th 11:00 UTC - 17:00 UTC
- Thursday Oct 29th 11:00 UTC - 17:00 UTC
- Friday Oct 30th 11:00 UTC - 17:00 UTC

**Comment by mrhillsman** [comment]
Thanks @keg
