### ISSUE TITLE
Step 1 init gives unknown command

### ISSUE THREAD

**Issue by darint00** [openshift-labs/learn-katacoda#931]
Trying to run through the tutorial and the step 1, where you run operator-sdk init.....  Produces an error operator-sdk init unknown command.  I tried to replace it with "new" that didn't work either.  Trying to learn operators and not sure what to do here.

**Comment by madorn** [comment]
@darint00 this issue should now be resolved - environment now includes operator-sdk v1.0.1 which features the `init` command.
