### ISSUE TITLE
'Linux Container Internals 2.0 - Lab 1: Introduction to Containers ' uses `kubectl` instead of `oc`?

### ISSUE THREAD

**Issue by cfergeau** [openshift-labs/learn-katacoda#939]
At Step 5/6, this tutorial starts using `kubectl` while `oc` would work equally well as far as I can tell, not sure why a different command needs to be used here?

**Comment by ryanj** [comment]
Thanks for the feedback, @cfergeau 

I've replaced the `kubectl` examples with `oc`

This should be fixed now
