### ISSUE TITLE
Pod in "Error" state in 'Linux Container Internals 2.0 - Lab 1: Introduction to Containers '

### ISSUE THREAD

**Issue by cfergeau** [openshift-labs/learn-katacoda#940]
Right after creating the instance, `oc get pods` has:
```
NAME                 READY STATUS
registry-console-1-deploy 0/1 Error
```
which is annoying as step 5/6 tells us to :
> Wait until all pods are are in status "RUNNING".

**Comment by ryanj** [comment]
Thanks for reporting - I think this is fixed.

Feel free to reopen if you hit this issue again
