### ISSUE TITLE
pom.xml is incomplete

### ISSUE THREAD

**Issue by KevinDeWire** [openshift-labs/learn-katacoda#942]
In the training at the following link the pom.xml file is incomplete preventing the "mvn package fabric8:deploy -Popenshift" command from completing successfully.

https://learn.openshift.com/middleware/courses/middleware-spring-boot/microservices-1

**Comment by cedricclyburn** [comment]
Hello @KevinDeWire! Thank you for the report, we've updated the pom.xml and the mvn deployment command to get things functional again! Feel free to reopen if this problem persists 👍
