### ISSUE TITLE
Operator Tutorial does not work

### ISSUE THREAD

**Issue by bwillusibmcom** [openshift-labs/learn-katacoda#944]
I am trying to go through the GOLAN Operator Tutorial at https://learn.openshift.com/operatorframework/go-operator-podset/

The first invocation of the operator-sdk command is

    operator-sdk init --domain=example.com --repo=github.com/redhat/podset-operator

However, in the tutorial environment, this command fails

/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:56:6: Xchguintptr redeclared in this block
        previous declaration at /usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:54:45
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:56:6: too many errors
Error: failed to initialize project with version "3-alpha": exit status 2

I would like to be able to run the Operator tutorial in the tutorial environment.

**Comment by madorn** [comment]
@bwillusibmcom See #911. This issue should now be resolved. Let us know if you experience any other issues.
