### ISSUE TITLE
Operator Workshop: November 16 - 17, 2020

### ISSUE THREAD

**Issue by mrhillsman** [openshift-labs/learn-katacoda#946]
Operator Workshop: November 16 - 17, 2020
7am to 5pm Central Time.
20 attendees

Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

Environments will need to be on 4.4

@BenHall
@gsoria
@madorn

**Comment by btannous** [comment]
I took a shot at scheduling this. Think everything is in there. Thanks for the notice!

@keg
