### ISSUE TITLE
Getting Started with Kubefed env missing kubefedclusters resource type

### ISSUE THREAD

**Issue by spoore1** [openshift-labs/learn-katacoda#952]
I'm trying to complete this lab:

https://learn.openshift.com/introduction/federated-clusters/

But, in step 3 of 6 I try to run this command:

`oc --context=cluster1 get kubefedclusters -n test-namespace`

And I see this error:

> error: the server doesn't have a resource type "kubefedclusters"

**Comment by ryanj** [comment]
Thanks for reporting.

Given issue #1060, I've removed it from the index: https://learn.openshift.com/introduction/ 

If I can find someone to fix the content, I'll add it back in
