### ISSUE TITLE
Transferring Files in and out of Containers - Docker pull rate limit

### ISSUE THREAD

**Issue by friday963** [openshift-labs/learn-katacoda#963]
Looks like  you've reached the pull rate limiter.
![Capture](https://user-images.githubusercontent.com/49578051/100267591-ebfada80-2f10-11eb-8b90-afa564cf4a5f.JPG)

**Comment by cedricclyburn** [comment]
Hello @friday963! Just working through issues currently. As this was near the day docker hub pull limitations went into effect, I believe it's been fixed now. Feel free to reopen if you experience otherwise!
