### ISSUE TITLE
Maven Verify Goals Fails in Getting Started with Spring

### ISSUE THREAD

**Issue by nexus-Six** [openshift-labs/learn-katacoda#972]
**In what katacoda scenario did this bug occur?**
Developing with Spring and Spring Boot > Getting Started with Spring (learn.openshift.com)

**At what step of the scenario did this happen?**
On page 2, chapter 6 the command > mvn verify fails 

**Describe the bug**
When executing the command there is a compile failure 

**Logs or error messages**
INFO] Compiling 1 source file to /root/projects/rhoar-getting-started/spring/spring-rhoar-intro/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /root/projects/rhoar-getting-started/spring/spring-rhoar-intro/src/test/java/com/example/ApplicationTest.java:[36,33] cannot find symbol
  symbol:   method findById(int)
  location: variable fruitRepository of type com.example.service.FruitRepository
[ERROR] /root/projects/rhoar-getting-started/spring/spring-rhoar-intro/src/test/java/com/example/ApplicationTest.java:[41,38] cannot find symbol
  symbol:   method findById(int)
  location: variable fruitRepository of type com.example.service.FruitRepository
[ERROR] /root/projects/rhoar-getting-started/spring/spring-rhoar-intro/src/test/java/com/example/ApplicationTest.java:[48,35] cannot find symbol
  symbol:   method findById(int)
  location: variable fruitRepository of type com.example.service.FruitRepository
[ERROR] /root/projects/rhoar-getting-started/spring/spring-rhoar-intro/src/test/java/com/example/ApplicationTest.java:[54,39] cannot find symbol
  symbol:   method findById(int)
  location: variable fruitRepository of type com.example.service.FruitRepository
[ERROR] /root/projects/rhoar-getting-started/spring/spring-rhoar-intro/src/test/java/com/example/ApplicationTest.java:[57,35] cannot find symbol
  symbol:   method findById(int)
  location: variable fruitRepository of type com.example.service.FruitRepository
[ERROR] /root/projects/rhoar-getting-started/spring/spring-rhoar-intro/src/test/java/com/example/ApplicationTest.java:[62,33] cannot find symbol
  symbol:   method findById(int)
  location: variable fruitRepository of type com.example.service.FruitRepository
[INFO] 6 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.338 s
[INFO] Finished at: 2020-12-09T17:44:26+00:00
[INFO] Final Memory: 26M/267M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project fruits: Compilation failure: Compilation failure:
[ERROR] /root/projects/rhoar-getting-started/spring/spring-rhoar-intro/src/test/java/com/example/ApplicationTest.java:[36,33] cannot find symbol
[ERROR] symbol:   method findById(int)
[ERROR] location: variable fruitRepository of type com.example.service.FruitRepository
[ERROR] /root/projects/rhoar-getting-started/spring/spring-rhoar-intro/src/test/java/com/example/ApplicationTest.java:[41,38] cannot find symbol
[ERROR] symbol:   method findById(int)
[ERROR] location: variable fruitRepository of type com.example.service.FruitRepository
[ERROR] /root/projects/rhoar-getting-started/spring/spring-rhoar-intro/src/test/java/com/example/ApplicationTest.java:[48,35] cannot find symbol
[ERROR] symbol:   method findById(int)
[ERROR] location: variable fruitRepository of type com.example.service.FruitRepository
[ERROR] /root/projects/rhoar-getting-started/spring/spring-rhoar-intro/src/test/java/com/example/ApplicationTest.java:[54,39] cannot find symbol
[ERROR] symbol:   method findById(int)
[ERROR] location: variable fruitRepository of type com.example.service.FruitRepository
[ERROR] /root/projects/rhoar-getting-started/spring/spring-rhoar-intro/src/test/java/com/example/ApplicationTest.java:[57,35] cannot find symbol
[ERROR] symbol:   method findById(int)
[ERROR] location: variable fruitRepository of type com.example.service.FruitRepository
[ERROR] /root/projects/rhoar-getting-started/spring/spring-rhoar-intro/src/test/java/com/example/ApplicationTest.java:[62,33] cannot find symbol
[ERROR] symbol:   method findById(int)
[ERROR] location: variable fruitRepository of type com.example.service.FruitRepository
[ERROR] -> [Help 1]

**Comment by robtha** [comment]
had the same issue. reason for this is, that the sample uses spring boot version 1.5.15 (why this old version?) but generates code for newer spring-data api.

**Comment by GAMST12** [comment]
Yes, I've got it also. It is caused because they use Spring Boot 1.5 and it doesn't have findById in Spring Data, only findOne (not Optional). If you rename method findById -> findOne and remove 'orElse' part it will work.

**Comment by jamesfalkner** [comment]
Same as https://github.com/openshift-labs/learn-katacoda/issues/1063
