### ISSUE TITLE
Topic :: Transferring Files in and out of Containers :: Giving an error

### ISSUE THREAD

**Issue by sverma-dev** [openshift-labs/learn-katacoda#975]
$ oc new-app openshiftkatacoda/blog-django-py --name blog
W1211 09:23:38.343396     818 dockerimagelookup.go:236] container image registry lookup failed: docker.io/openshiftkatacoda/blog-django-py:latest: toomanyrequests: You have reached your pull rate limit. You may increasethe limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
error:  local file access failed with: stat openshiftkatacoda/blog-django-py: no such file or directory
error: unable to locate any images in image streams, templates loaded in accessible projects, template files,local docker images with name "openshiftkatacoda/blog-django-py"

**Comment by cedricclyburn** [comment]
Hello @sverma-dev! Just working through issues currently. As this was near when docker hub pull limitations went into effect, I believe it's been fixed now. Feel free to reopen if you experience otherwise!
