### ISSUE TITLE
Provide a basic tutorial for Debezium deployment

### ISSUE THREAD

**Issue by jpechane** [openshift-labs/learn-katacoda#98]
The first exercise should just mimic creation of environment described in http://debezium.io/docs/tutorial/ using barnabas images and templates.
A MySQL database should be registered toi Debezium and changes in database will be recorded in Kafka broker and demonstrated using starndard Kafka tools.
When accepted a one more scenari will be developed that will demonstrate a legacy app creating database records, Debezium sourcing them to Kafka and a Camel application consimung the events.

**Comment by mhausenblas** [comment]
Seems stale, please re-open if it persists.

**Comment by jpechane** [comment]
Debezium now uses Strimzi project - this in version 0.2.0 requires OS 3.7 but Katacode is on version 3.6. We will continue when Katacoda will use a newer one.

**Comment by jpechane** [comment]
Is there something laki that for `openshift-middleware` image?

**Comment by jpechane** [comment]
@mhausenblas Hi, https://github.com/openshift-labs/learn-katacoda/pull/102 has been updated to use the latest Debezium, Strimzi and OS 3.7. I'd be grateful for review.
