### ISSUE TITLE
Interactive Learning Environment Bash Shell fails to start

### ISSUE THREAD

**Issue by justin-sun** [openshift-labs/learn-katacoda#980]
I'm seeing this error when attempting to open https://learn.openshift.com/persistence/persistent-intro/:

**We are currently at capacity with no additional nodes available. Please check back in 10 minutes.**

After waiting 10 minutes and trying again, the same error appears.

**Comment by tutsunom** [comment]
+1

**Comment by ryanj** [comment]
Thanks for alerting
We should be back in operation.  Feel free to open another issue if you see this again
