### ISSUE TITLE
impossible to start scenario

### ISSUE THREAD

**Issue by lmpro** [openshift-labs/learn-katacoda#986]
Hello,
Just to report that "We are currently at capacity with no more node available. PLease check back in 10 mn" 
I've been hung tight for now half a day :-(
and we are Sunday...
https://learn.openshift.com/playgrounds/openshift42

**Comment by lmpro** [comment]
Still hung tight 2 weeks later ...

**Comment by ryanj** [comment]
Thanks for reporting, @lmpro.  

Sorry for the slow response.  We removed the OpenShift 4.2 playground
