### ISSUE TITLE
OpenShift console not working

### ISSUE THREAD

**Issue by chandan-chopra** [openshift-labs/learn-katacoda#992]
When I launch OpenShift from learn.openshift.com, it launches the environment and I am able to work on Terminal, but when I open Console, I get below message in browser. I tried multiple times and waited for long but still same issue

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/77354383/104354802-c614ae00-552f-11eb-9673-f12f7aace86a.png">

**Comment by ryanj** [comment]
Thanks for the alert! Should be resolved now.  
Feel free to open another issue if you see it again.
