### ISSUE TITLE
Operator Workshop: January 26 - 28, 2021

### ISSUE THREAD

**Issue by madorn** [openshift-labs/learn-katacoda#996]
Operator Workshop: January 26 - 28, 2021
8am to 4pm Central Time.
50 attendees

Please use this pathway: https://github.com/openshift-labs/learn-katacoda/blob/master/operatorframework-pathway.json

@btannous
@BenHall

**Comment by gsoria** [comment]
Hi folks, the workshops have been scheduled.

Pathway file: operatorframework-pathway.json, environment: openshift-4-5, 50 attendees for each:

- Tuesday 26-01-2021 at 14:00 UTC until Tuesday 22:00 UTC 
- Wednesday 27-01-2021 at 14:00 UTC until Wednesday 22:00 UTC
- Thursday 28-01-2021 at 14:00 UTC until Thursday 22:00 UTC
