### ISSUE TITLE
Getting Started with JBoss EAP on OpenShift breaks 

### ISSUE THREAD

**Issue by dextro67** [openshift-labs/learn-katacoda#997]
1. weather-app is not copying under /root/projects/weather-app
2. command oc new-build fails since it is not able to find jboss-eap72-openshift:1.0 
3. Manually creating a wildfly project also fails from console.

**Comment by dextro67** [comment]
Seems like the [run-init.sh](https://github.com/openshift-labs/learn-katacoda/blob/master/middleware/middleware-javaee8/run-init.sh ) has some issues.

**Comment by jamesfalkner** [comment]
Fixed in https://github.com/openshift-labs/learn-katacoda/commit/c6bab3d14777c1f74750b013b2418131644e1e1c
